### ISSUE TITLE
Nomad has Process Handles leak after which it crashes

### ISSUE THREAD

**Issue by Settler** [hashicorp/nomad#10332]
### Nomad version
Nomad v1.0.4 (9294f35f9aa8dbb4acb6e85fa88e3e2534a3e41a)

### Operating system and Environment details
- Windows Server 2019
- raw_exec

### Issue
After several days of ideal work, our nomad client nodes started to crash.
Right before crash, we see those lines in client log files:
```
2021-04-08T12:29:01.667+0300 [DEBUG] client.alloc_runner.task_runner.task_hook.logmon: reattached plugin process exited: alloc_id=f0804328-3543-e75b-b9b0-6765f63a9427 task=XXX.exe
2021-04-08T12:29:01.682+0300 [DEBUG] client.alloc_runner.task_runner.task_hook.logmon: reattached plugin process exited: alloc_id=4e41d7da-75df-d782-6b03-51dee46a6289 task=YYY.exe
2021-04-08T12:29:01.689+0300 [DEBUG] client.alloc_runner.task_runner.task_hook.logmon: reattached plugin process exited: alloc_id=8a35595e-db58-fdb2-1b0c-9c3b0934a984 task=ZZZ.exe
... and so on ...
```
Also we see those:
```
2021-04-08T12:29:01.888+0300 [ERROR] client.host_stats: failed to collect disk stats: error="Insufficient system resources exist to complete the requested service."
2021-04-08T12:29:01.889+0300 [ERROR] client.host_stats: failed to find disk usage of alloc: alloc_dir=c:\ncv\nomad\data\alloc error="Insufficient system resources exist to complete the requested service."
```
And those:
```
2021-04-08T12:29:21.012+0300 [ERROR] client.alloc_runner.task_runner.task_hook: failed to launch logmon process: alloc_id=1c4eebd0-7853-4d05-ec4a-ac03736c1655 task=XXX.exe error="pipe: Insufficient system resources exist to complete the requested service."
2021-04-08T12:29:21.017+0300 [ERROR] client.alloc_runner.task_runner: prestart failed: alloc_id=1c4eebd0-7853-4d05-ec4a-ac03736c1655 task=XXX.exe error="prestart hook "logmon" failed: pipe: Insufficient system resources exist to complete the requested service."
2021-04-08T12:29:21.017+0300 [INFO]  client.alloc_runner.task_runner: restarting task: alloc_id=1c4eebd0-7853-4d05-ec4a-ac03736c1655 task=XXX.exe reason="Restart within policy" delay=17.159548411s
```
After around 5 minutes of trying to restart still working tasks, the nomad has crashed.

We started looking for which resources are not enough...
After deep dive into nomad code base we have found, that `failed to find disk usage of alloc` is logged when call [GetDiskFreeSpaceExW](https://github.com/hashicorp/nomad/blob/14568b3e002868fc5c83ee7d158a78394c1ea9c1/vendor/github.com/shirou/gopsutil/v3/disk/disk_windows.go#L50) returns an error.
So... When Windows API call could cause `Insufficient resources` error?
When something has ended in Windows... Memory? Ports? Handles?
We checked all of them and have found that one of our nomad client nodes _handles_ almost 12 million handles. Windows is limited up to 16 million handles btw. So this node will crash soon too...
We took handles statistics of nomad process and this is what we saw:
```
Handle type summary:
  ALPC Port       : 5
  Desktop         : 1
  Directory       : 2
  EtwRegistration : 60
  Event           : 342
  File            : 202
  IoCompletion    : 7
  IRTimer         : 8
  Key             : 47
  Mutant          : 2
  Process         : 11934692
  Section         : 2
  Semaphore       : 5
  Thread          : 189
  TpWorkerFactory : 4
  WaitCompletionPacket: 34
  WindowStation   : 2
```
Wow... Almost 12 million Process Handles. But we don't have so many process :)
So we researched a little bit more and found exact reproductions steps which are written below.

### Reproduction steps

1. Start nomad Windows Service
2. Run any service job
3. Waiting until allocation become healthy
4. Restart nomad Windows Service
5. See how newly born nomad process "eats" around 10 handles every 5 seconds

#### Expected Result
Successfully starts and doesn't keep Process Handles

#### Actual Result
Eats up to 16 000 000 handles and then crashes.

### Job file (if appropriate)
```
job "HandleLeak" {
  datacenters = ["DC"]
  namespace = "default"
  type = "service"
  
  constraint {
    attribute = "${attr.unique.hostname}"
    value = "TEST"
    operator = "regexp"
  }
  
  group "HandleLeak-Group" {
    count = 1
    
    task "HandleLeak-Task" {
      driver = "raw_exec"
      kill_timeout = "10s"
      
      config {
        command = "C:\\Windows\\System32\\notepad.exe"
      }
    }
  }
}
```

We think that something in reattachment logic is broken. Newly born nomad process begin to reattach to already run processes and something went wrong there...
But we don't know exactly what causes this process handles leak.
And this doesn't allow us to use nomad in full force and move to production stage.
@tgross Could I ask you to pay attention to this bug, please? This is very important for us and I'm ready to help you in any additional investigation process if necessary.

**Comment by shoenig** [comment]
Thanks for reporting, @Settler! At first glance it sounds like there may be an issue where the `logmon` copocess for each task is getting into a state where it is constantly launching new instances, at least that's the best idea I have so far. There are some `Trace` statements that would make it obvious if that's the case, if you're willing to endure some potentially very large logs :sweat_smile: Otherwise we'll try to reproduce this and investigate.

**Comment by Settler** [comment]
Hi @shoenig!
I'll do my best to get Trace logs. We have empty nodes where we reproduced that behavior. So I think it would be possible.

**Comment by Settler** [comment]
@shoenig I've set trace logging into `nomad-client.hcl`.
Allocation Id which was running: 24b83389-3c60-9494-adba-446ec8780f8c
Logs for this allocation:
```
2021-04-09T12:32:43.765+0300 [TRACE] client.alloc_runner: running pre-run hooks: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c start="2021-04-09 12:32:43.7658914 +0300 MSK m=+15.768009401"
2021-04-09T12:32:43.768+0300 [TRACE] client.alloc_runner: running pre-run hook: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c name=alloc_dir start="2021-04-09 12:32:43.7688733 +0300 MSK m=+15.770991301"
2021-04-09T12:32:43.770+0300 [TRACE] client.alloc_runner: finished pre-run hook: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c name=alloc_dir end="2021-04-09 12:32:43.7708707 +0300 MSK m=+15.772988701" duration=1.9974ms
2021-04-09T12:32:43.772+0300 [TRACE] client.alloc_runner: running pre-run hook: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c name=await_previous_allocations start="2021-04-09 12:32:43.7728873 +0300 MSK m=+15.775005301"
2021-04-09T12:32:43.773+0300 [TRACE] client.alloc_runner: finished pre-run hook: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c name=await_previous_allocations end="2021-04-09 12:32:43.7738722 +0300 MSK m=+15.775990201" duration=984.9µs
2021-04-09T12:32:43.773+0300 [TRACE] client.alloc_runner: running pre-run hook: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c name=migrate_disk start="2021-04-09 12:32:43.7738722 +0300 MSK m=+15.775990201"
2021-04-09T12:32:43.773+0300 [TRACE] client.alloc_runner: finished pre-run hook: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c name=migrate_disk end="2021-04-09 12:32:43.7738722 +0300 MSK m=+15.775990201" duration=0s
2021-04-09T12:32:43.773+0300 [TRACE] client.alloc_runner: running pre-run hook: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c name=alloc_health_watcher start="2021-04-09 12:32:43.7738722 +0300 MSK m=+15.775990201"
2021-04-09T12:32:43.773+0300 [TRACE] client.alloc_runner.runner_hook.alloc_health_watcher: not watching; already has health set: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c
2021-04-09T12:32:43.774+0300 [TRACE] client.alloc_runner: finished pre-run hook: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c name=alloc_health_watcher end="2021-04-09 12:32:43.7738722 +0300 MSK m=+15.775990201" duration=0s
2021-04-09T12:32:43.774+0300 [TRACE] client.alloc_runner: running pre-run hook: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c name=network start="2021-04-09 12:32:43.7748709 +0300 MSK m=+15.776988901"
2021-04-09T12:32:43.774+0300 [TRACE] client.alloc_runner: finished pre-run hook: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c name=network end="2021-04-09 12:32:43.7748709 +0300 MSK m=+15.776988901" duration=0s
2021-04-09T12:32:43.774+0300 [TRACE] client.alloc_runner: running pre-run hook: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c name=group_services start="2021-04-09 12:32:43.7748709 +0300 MSK m=+15.776988901"
2021-04-09T12:32:43.774+0300 [TRACE] client.alloc_runner: finished pre-run hook: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c name=group_services end="2021-04-09 12:32:43.7748709 +0300 MSK m=+15.776988901" duration=0s
2021-04-09T12:32:43.774+0300 [TRACE] client.alloc_runner: running pre-run hook: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c name=consul_grpc_socket start="2021-04-09 12:32:43.7748709 +0300 MSK m=+15.776988901"
2021-04-09T12:32:43.775+0300 [TRACE] client.alloc_runner: finished pre-run hook: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c name=consul_grpc_socket end="2021-04-09 12:32:43.7758704 +0300 MSK m=+15.777988401" duration=999.5µs
2021-04-09T12:32:43.775+0300 [TRACE] client.alloc_runner: running pre-run hook: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c name=consul_http_socket start="2021-04-09 12:32:43.7758704 +0300 MSK m=+15.777988401"
2021-04-09T12:32:43.775+0300 [TRACE] client.alloc_runner: finished pre-run hook: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c name=consul_http_socket end="2021-04-09 12:32:43.7758704 +0300 MSK m=+15.777988401" duration=0s
2021-04-09T12:32:43.775+0300 [TRACE] client.alloc_runner: running pre-run hook: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c name=csi_hook start="2021-04-09 12:32:43.7758704 +0300 MSK m=+15.777988401"
2021-04-09T12:32:43.775+0300 [TRACE] client.alloc_runner: finished pre-run hook: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c name=csi_hook end="2021-04-09 12:32:43.7758704 +0300 MSK m=+15.777988401" duration=0s
2021-04-09T12:32:43.775+0300 [TRACE] client.alloc_runner: finished pre-run hooks: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c end="2021-04-09 12:32:43.7758704 +0300 MSK m=+15.777988401" duration=9.979ms
2021-04-09T12:32:43.775+0300 [DEBUG] client.alloc_runner.task_runner: lifecycle start condition has been met, proceeding: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c task=HandleLeak-Task
2021-04-09T12:32:43.775+0300 [TRACE] client.alloc_runner.task_runner: running prestart hooks: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c task=HandleLeak-Task start="2021-04-09 12:32:43.7758704 +0300 MSK m=+15.777988401"
2021-04-09T12:32:43.775+0300 [TRACE] client.alloc_runner.task_runner: skipping done prestart hook: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c task=HandleLeak-Task name=validate
2021-04-09T12:32:43.776+0300 [TRACE] client.alloc_runner.task_runner: running prestart hook: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c task=HandleLeak-Task name=task_dir start="2021-04-09 12:32:43.7768699 +0300 MSK m=+15.778987901"
2021-04-09T12:32:43.776+0300 [TRACE] client.alloc_runner.task_runner: finished prestart hook: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c task=HandleLeak-Task name=task_dir end="2021-04-09 12:32:43.7768699 +0300 MSK m=+15.778987901" duration=0s
2021-04-09T12:32:43.777+0300 [TRACE] client.alloc_runner.task_runner: running prestart hook: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c task=HandleLeak-Task name=logmon start="2021-04-09 12:32:43.7778805 +0300 MSK m=+15.779998501"
2021-04-09T12:32:45.777+0300 [DEBUG] client.alloc_runner.task_runner.task_hook.logmon: reattached plugin process exited: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c task=HandleLeak-Task
2021-04-09T12:32:45.777+0300 [ERROR] client.alloc_runner.task_runner.task_hook: failed to start logmon: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c task=HandleLeak-Task error="plugin is shut down"
2021-04-09T12:32:45.777+0300 [WARN]  client.alloc_runner.task_runner.task_hook: logmon shutdown while making request: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c task=HandleLeak-Task error="plugin is shut down"
2021-04-09T12:32:45.777+0300 [WARN]  client.alloc_runner.task_runner.task_hook: logmon shutdown while making request; retrying: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c task=HandleLeak-Task attempts=1 error="plugin is shut down"
2021-04-09T12:32:45.777+0300 [DEBUG] client.alloc_runner.task_runner.task_hook.logmon: plugin exited: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c task=HandleLeak-Task
2021-04-09T12:32:46.779+0300 [DEBUG] client.alloc_runner.task_runner.task_hook.logmon: starting plugin: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c task=HandleLeak-Task path=C:\ncv\nomad\nomad.exe args=[C:\ncv\nomad\nomad.exe, logmon]
2021-04-09T12:32:46.781+0300 [DEBUG] client.alloc_runner.task_runner.task_hook.logmon: plugin started: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c task=HandleLeak-Task path=C:\ncv\nomad\nomad.exe pid=2036
2021-04-09T12:32:46.781+0300 [DEBUG] client.alloc_runner.task_runner.task_hook.logmon: waiting for RPC address: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c task=HandleLeak-Task path=C:\ncv\nomad\nomad.exe
2021-04-09T12:32:46.866+0300 [DEBUG] client.alloc_runner.task_runner.task_hook.logmon: using plugin: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c task=HandleLeak-Task version=2
2021-04-09T12:32:46.866+0300 [DEBUG] client.alloc_runner.task_runner.task_hook.logmon.nomad.exe: plugin address: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c task=HandleLeak-Task address=127.0.0.1:10000 network=tcp @module=logmon timestamp=2021-04-09T12:32:46.846+0300
2021-04-09T12:32:46.869+0300 [INFO]  client.alloc_runner.task_runner.task_hook.logmon.nomad.exe: opening fifo: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c task=HandleLeak-Task path=//./pipe/HandleLeak-Task-19aed429.stdout @module=logmon timestamp=2021-04-09T12:32:46.869+0300
2021-04-09T12:32:46.869+0300 [INFO]  client.alloc_runner.task_runner.task_hook.logmon.nomad.exe: opening fifo: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c task=HandleLeak-Task @module=logmon path=//./pipe/HandleLeak-Task-19aed429.stderr timestamp=2021-04-09T12:32:46.869+0300
2021-04-09T12:32:46.873+0300 [TRACE] client.alloc_runner.task_runner: finished prestart hook: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c task=HandleLeak-Task name=logmon end="2021-04-09 12:32:46.8730874 +0300 MSK m=+18.875209401" duration=3.0952109s
2021-04-09T12:32:46.873+0300 [TRACE] client.alloc_runner.task_runner: skipping done prestart hook: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c task=HandleLeak-Task name=dispatch_payload
2021-04-09T12:32:46.873+0300 [TRACE] client.alloc_runner.task_runner: running prestart hook: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c task=HandleLeak-Task name=volumes start="2021-04-09 12:32:46.8730874 +0300 MSK m=+18.875209401"
2021-04-09T12:32:46.873+0300 [TRACE] client.alloc_runner.task_runner: finished prestart hook: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c task=HandleLeak-Task name=volumes end="2021-04-09 12:32:46.8730874 +0300 MSK m=+18.875209401" duration=0s
2021-04-09T12:32:46.873+0300 [TRACE] client.alloc_runner.task_runner: skipping done prestart hook: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c task=HandleLeak-Task name=artifacts
2021-04-09T12:32:46.873+0300 [TRACE] client.alloc_runner.task_runner: skipping done prestart hook: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c task=HandleLeak-Task name=devices
2021-04-09T12:32:46.873+0300 [TRACE] client.alloc_runner.task_runner: running prestart hook: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c task=HandleLeak-Task name=script_checks start="2021-04-09 12:32:46.8730874 +0300 MSK m=+18.875209401"
2021-04-09T12:32:46.873+0300 [TRACE] client.alloc_runner.task_runner: finished prestart hook: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c task=HandleLeak-Task name=script_checks end="2021-04-09 12:32:46.8730874 +0300 MSK m=+18.875209401" duration=0s
2021-04-09T12:32:46.873+0300 [TRACE] client.alloc_runner.task_runner: finished prestart hooks: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c task=HandleLeak-Task end="2021-04-09 12:32:46.8730874 +0300 MSK m=+18.875209401" duration=3.097221s
2021-04-09T12:32:46.876+0300 [TRACE] client.alloc_runner.task_runner: running poststart hooks: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c task=HandleLeak-Task start="2021-04-09 12:32:46.8760872 +0300 MSK m=+18.878209201"
2021-04-09T12:32:46.877+0300 [TRACE] client.alloc_runner.task_runner: running poststart hook: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c task=HandleLeak-Task name=stats_hook start="2021-04-09 12:32:46.8770849 +0300 MSK m=+18.879206901"
2021-04-09T12:32:46.877+0300 [TRACE] client.alloc_runner.task_runner: finished poststart hooks: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c task=HandleLeak-Task name=stats_hook end="2021-04-09 12:32:46.8770849 +0300 MSK m=+18.879206901" duration=0s
2021-04-09T12:32:46.877+0300 [TRACE] client.alloc_runner.task_runner: running poststart hook: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c task=HandleLeak-Task name=consul_services start="2021-04-09 12:32:46.8770849 +0300 MSK m=+18.879206901"
2021-04-09T12:32:46.877+0300 [TRACE] client.alloc_runner.task_runner: finished poststart hooks: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c task=HandleLeak-Task name=consul_services end="2021-04-09 12:32:46.8770849 +0300 MSK m=+18.879206901" duration=0s
2021-04-09T12:32:46.877+0300 [TRACE] client.alloc_runner.task_runner: running poststart hook: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c task=HandleLeak-Task name=script_checks start="2021-04-09 12:32:46.8770849 +0300 MSK m=+18.879206901"
2021-04-09T12:32:46.877+0300 [TRACE] client.alloc_runner.task_runner: finished poststart hooks: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c task=HandleLeak-Task name=script_checks end="2021-04-09 12:32:46.8770849 +0300 MSK m=+18.879206901" duration=0s
2021-04-09T12:32:46.877+0300 [TRACE] client.alloc_runner.task_runner: finished poststart hooks: alloc_id=24b83389-3c60-9494-adba-446ec8780f8c task=HandleLeak-Task end="2021-04-09 12:32:46.8770849 +0300 MSK m=+18.879206901" duration=997.7µs
```

For other allocations which were run previously but still not collected by GC I see these events:
```
2021-04-09T12:32:47.774+0300 [WARN]  client.alloc_runner.task_runner.task_hook.logmon: plugin failed to exit gracefully: alloc_id=c86ee65f-79b6-fced-5002-2b1e7e8ef289 task=HandleLeak-Task
2021-04-09T12:32:48.771+0300 [DEBUG] client.alloc_runner.task_runner.task_hook.logmon: reattached plugin process exited: alloc_id=c86ee65f-79b6-fced-5002-2b1e7e8ef289 task=HandleLeak-Task
```

After initialization I see only these events in logs:
```
2021-04-09T12:32:48.979+0300 [TRACE] client: next heartbeat: period=15.654240867s
2021-04-09T12:32:49.032+0300 [DEBUG] client: state changed, updating node and re-registering
2021-04-09T12:32:49.044+0300 [DEBUG] client: updated allocations: index=56749 total=12 pulled=0 filtered=12
2021-04-09T12:32:49.044+0300 [DEBUG] client: allocation updates: added=0 removed=0 updated=0 ignored=12
2021-04-09T12:32:49.044+0300 [DEBUG] client: allocation updates applied: added=0 removed=0 updated=0 ignored=12 errors=0
2021-04-09T12:32:49.045+0300 [INFO]  client: node registration complete
2021-04-09T12:32:49.049+0300 [TRACE] client: next heartbeat: period=14.006522219s
2021-04-09T12:32:50.014+0300 [DEBUG] http: request complete: method=GET path=/v1/metrics?format=prometheus duration=9.0506ms
2021-04-09T12:32:50.081+0300 [DEBUG] http: request complete: method=GET path=/v1/agent/health?type=client duration=0s
2021-04-09T12:33:00.011+0300 [DEBUG] http: request complete: method=GET path=/v1/metrics?format=prometheus duration=6.4475ms
2021-04-09T12:33:00.084+0300 [DEBUG] http: request complete: method=GET path=/v1/agent/health?type=client duration=972.7µs
2021-04-09T12:33:03.063+0300 [TRACE] client: next heartbeat: period=17.137102798s
2021-04-09T12:33:10.013+0300 [DEBUG] http: request complete: method=GET path=/v1/metrics?format=prometheus duration=1.752ms
2021-04-09T12:33:10.085+0300 [DEBUG] http: request complete: method=GET path=/v1/agent/health?type=client duration=0s
2021-04-09T12:33:20.016+0300 [DEBUG] http: request complete: method=GET path=/v1/metrics?format=prometheus duration=1.3582ms
2021-04-09T12:33:20.087+0300 [DEBUG] http: request complete: method=GET path=/v1/agent/health?type=client duration=0s
2021-04-09T12:33:20.205+0300 [TRACE] client: next heartbeat: period=11.878856128s
2021-04-09T12:33:30.007+0300 [DEBUG] http: request complete: method=GET path=/v1/metrics?format=prometheus duration=2.5395ms
2021-04-09T12:33:30.089+0300 [DEBUG] http: request complete: method=GET path=/v1/agent/health?type=client duration=0s
2021-04-09T12:33:32.099+0300 [TRACE] client: next heartbeat: period=11.0606092s
2021-04-09T12:33:40.003+0300 [DEBUG] http: request complete: method=GET path=/v1/metrics?format=prometheus duration=996.8µs
2021-04-09T12:33:40.091+0300 [DEBUG] http: request complete: method=GET path=/v1/agent/health?type=client duration=1.0376ms
2021-04-09T12:33:43.167+0300 [TRACE] client: next heartbeat: period=12.251241173s
2021-04-09T12:33:50.024+0300 [DEBUG] http: request complete: method=GET path=/v1/metrics?format=prometheus duration=5.5071ms
2021-04-09T12:33:50.093+0300 [DEBUG] http: request complete: method=GET path=/v1/agent/health?type=client duration=405.1µs
2021-04-09T12:33:55.424+0300 [TRACE] client: next heartbeat: period=13.599779447s
```

I don't see any trace logs which could show why handles are leaking. But they are leaking...
One more thing. I tried to restart nomad several times because most of the time he killed running allocations on start instead of reattaching to them.

**Comment by tgross** [comment]
Had a test flake on an unrelated PR https://app.circleci.com/pipelines/github/hashicorp/nomad/15662/workflows/9d992c4d-43be-4aa2-b227-ddc6e7f9854b/jobs/149425 that seems like it could be related to this issue. Dropping the test output here in case it'd be useful:

<details>

```
Failed
=== RUN   TestFIFO
panic: test timed out after 10m0s

goroutine 11 [running]:
testing.(*M).startAlarm.func1()
	c:/go/src/testing/testing.go:1701 +0xe6
created by time.goFunc
	c:/go/src/time/sleep.go:180 +0x4b

goroutine 1 [chan receive]:
testing.(*T).Run(0xc00003b080, 0xb83391, 0x8, 0xb976a8, 0xa0600d)
	c:/go/src/testing/testing.go:1240 +0x2da
testing.runTests.func1(0xc00003af00)
	c:/go/src/testing/testing.go:1512 +0x7f
testing.tRunner(0xc00003af00, 0xc00010fde0)
	c:/go/src/testing/testing.go:1194 +0xef
testing.runTests(0xc000004168, 0xce0ea0, 0x2, 0x2, 0xc01538914d052cf8, 0x8bb2c97001, 0xceb700, 0xb85065)
	c:/go/src/testing/testing.go:1510 +0x310
testing.(*M).Run(0xc00007a100, 0x0)
	c:/go/src/testing/testing.go:1418 +0x1f5
main.main()
	_testmain.go:45 +0x145

goroutine 6 [semacquire]:
sync.runtime_Semacquire(0xc000011208)
	c:/go/src/runtime/sema.go:56 +0x49
sync.(*WaitGroup).Wait(0xc000011200)
	c:/go/src/sync/waitgroup.go:130 +0x6b
github.com/hashicorp/nomad/client/lib/fifo.TestFIFO(0xc00003b080)
	c:/gopath/src/github.com/hashicorp/nomad/client/lib/fifo/fifo_test.go:74 +0x525
testing.tRunner(0xc00003b080, 0xb976a8)
	c:/go/src/testing/testing.go:1194 +0xef
created by testing.(*T).Run
	c:/go/src/testing/testing.go:1239 +0x2b3

goroutine 7 [select]:
github.com/Microsoft/go-winio.(*win32PipeListener).makeConnectedServerPipe(0xc0000543c0, 0x0, 0xbce1c0, 0xcc1120)
	c:/gopath/src/github.com/hashicorp/nomad/vendor/github.com/Microsoft/go-winio/pipe.go:365 +0x139
github.com/Microsoft/go-winio.(*win32PipeListener).listenerRoutine(0xc0000543c0)
	c:/gopath/src/github.com/hashicorp/nomad/vendor/github.com/Microsoft/go-winio/pipe.go:395 +0x132
created by github.com/Microsoft/go-winio.ListenPipe
	c:/gopath/src/github.com/hashicorp/nomad/vendor/github.com/Microsoft/go-winio/pipe.go:482 +0x1e9

goroutine 8 [chan receive]:
github.com/Microsoft/go-winio.(*win32PipeListener).Accept(0xc0000543c0, 0x0, 0x0, 0xc00004bde0, 0xa548bd)
	c:/gopath/src/github.com/hashicorp/nomad/vendor/github.com/Microsoft/go-winio/pipe.go:505 +0x14c
github.com/hashicorp/nomad/client/lib/fifo.(*winFIFO).ensureConn(0xc00014e390, 0x0, 0x0, 0x0, 0x0)
	c:/gopath/src/github.com/hashicorp/nomad/client/lib/fifo/fifo_windows.go:28 +0xca
github.com/hashicorp/nomad/client/lib/fifo.(*winFIFO).Read(0xc00014e390, 0xc000158000, 0x200, 0x200, 0x97b51a, 0xce7560, 0x195136a89f8)
	c:/gopath/src/github.com/hashicorp/nomad/client/lib/fifo/fifo_windows.go:39 +0x36
bytes.(*Buffer).ReadFrom(0xc00014e360, 0x195136a89b8, 0xc00014e390, 0x195136a89f8, 0xc00014e360, 0xb5ee01)
	c:/go/src/bytes/buffer.go:204 +0xbe
io.copyBuffer(0xbcdbe0, 0xc00014e360, 0x195136a89b8, 0xc00014e390, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0)
	c:/go/src/io/io.go:409 +0x357
io.Copy(...)
	c:/go/src/io/io.go:382
github.com/hashicorp/nomad/client/lib/fifo.TestFIFO.func1(0xc000011200, 0xc0000041b0, 0xc000046f30, 0xc00003b080, 0xc00014e360)
	c:/gopath/src/github.com/hashicorp/nomad/client/lib/fifo/fifo_test.go:60 +0x167
created by github.com/hashicorp/nomad/client/lib/fifo.TestFIFO
	c:/gopath/src/github.com/hashicorp/nomad/client/lib/fifo/fifo_test.go:50 +0x2e6

goroutine 9 [syscall, locked to thread]:
syscall.Syscall6(0x7fff50546b90, 0x5, 0x154, 0xc00015ff9c, 0xc00015ffa0, 0xc00015ffa8, 0xffffffff, 0x0, 0x0, 0x0, ...)
	c:/go/src/runtime/syscall_windows.go:343 +0xf2
github.com/Microsoft/go-winio.getQueuedCompletionStatus(0x154, 0xc00015ff9c, 0xc00015ffa0, 0xc00015ffa8, 0xffffffff, 0x0, 0x0)
	c:/gopath/src/github.com/hashicorp/nomad/vendor/github.com/Microsoft/go-winio/zsyscall_windows.go:107 +0xd5
github.com/Microsoft/go-winio.ioCompletionProcessor(0x154)
	c:/gopath/src/github.com/hashicorp/nomad/vendor/github.com/Microsoft/go-winio/file.go:161 +0xb6
created by github.com/Microsoft/go-winio.initIo
	c:/gopath/src/github.com/hashicorp/nomad/vendor/github.com/Microsoft/go-winio/file.go:73 +0x85

goroutine 18 [select]:
github.com/Microsoft/go-winio.(*win32File).asyncIo(0xc00018c000, 0xc000180030, 0x0, 0x0, 0xbce1c0, 0xcb02a0, 0xc000161f88, 0x975d95, 0xc00000e8a0)
	c:/gopath/src/github.com/hashicorp/nomad/vendor/github.com/Microsoft/go-winio/file.go:188 +0x14b
github.com/Microsoft/go-winio.connectPipe(0xc00018c000, 0x0, 0x0)
	c:/gopath/src/github.com/hashicorp/nomad/vendor/github.com/Microsoft/go-winio/pipe.go:494 +0xe5
github.com/Microsoft/go-winio.(*win32PipeListener).makeConnectedServerPipe.func1(0xc000182120, 0xc00018c000)
	c:/gopath/src/github.com/hashicorp/nomad/vendor/github.com/Microsoft/go-winio/pipe.go:362 +0x32
created by github.com/Microsoft/go-winio.(*win32PipeListener).makeConnectedServerPipe
	c:/gopath/src/github.com/hashicorp/nomad/vendor/github.com/Microsoft/go-winio/pipe.go:361 +0xc5
```

</details>

**Comment by shoenig** [comment]
I haven't been able to get on a Windows box to try to reproduce yet, but perusing the code 2 things kinda stand out:
- Our version of `go-plugin` is old (~ Oct. 2019), and there have been a number of [new versions](https://github.com/hashicorp/go-plugin/tags) with bux fixes since then 
- There's at least one [error path](https://github.com/hashicorp/nomad/blob/main/client/allocrunner/taskrunner/logmon_hook.go#L129) where we don't call `.Kill` when bailing out of the logmon hook - that feels leaky

**Comment by shoenig** [comment]
Also @Settler maybe this would be too easy to work, but could we just ask Windows what the handles the Client are holding? e.g.

```
handle -a -p <nomad process>
```

**Comment by Settler** [comment]
@shoenig
I've already written that the Client holds Process Handles.
If we look into details, then we'll see this:
```
  5DC: Process       <Error Opening Process>
  5E0: Process       <Error Opening Process>
  5E4: Process       <Error Opening Process>
  5E8: Process       <Error Opening Process>
  5EC: Process       <Error Opening Process>
  5F0: Process       <Error Opening Process>
  5F4: Process       <Error Opening Process>
  5F8: Process       <Error Opening Process>
  5FC: Process       <Error Opening Process>
  600: Process       <Error Opening Process>
  604: Process       <Error Opening Process>
  608: Process       <Error Opening Process>
```
It seems that the Client keeps handles to nonexisting Processes... A lot of handles...
