### ISSUE TITLE
CLI panic in namespace status w/ quotas

### ISSUE THREAD

**Issue by tgross** [hashicorp/nomad#10619]
In Nomad 1.1.0, when querying the namespace status, the command line panics if the namespace has quotas. I've reproduced this on Nomad 1.1.0 and Nomad 1.1.0+ENT, but not on Nomad 1.0.6 or earlier. Most likely introduced by https://github.com/hashicorp/nomad/pull/10481

```
$ nomad --version
Nomad v1.1.0+ent (16a743460748174af378b165dc5a35b2ccd92865)

$ nomad namespace status default
Name        = default
Description = Default shared namespace
Quota       = test-quota

Quota Limits
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5fc3b2d]

goroutine 1 [running]:
github.com/hashicorp/nomad/command.formatQuotaLimits(0xc00084a000, 0xc000abee10, 0x19, 0xc000364880)
        github.com/hashicorp/nomad/command/quota_status.go:194 +0x46d
github.com/hashicorp/nomad/command.(*NamespaceStatusCommand).Run(0xc000035ef0, 0xc0001ba030, 0x1, 0x1, 0xc000549e90)
        github.com/hashicorp/nomad/command/namespace_status.go:97 +0x536
github.com/mitchellh/cli.(*CLI).Run(0xc000399b80, 0xc000399b80, 0xc00000f800, 0x3b)
        github.com/mitchellh/cli@v1.1.0/cli.go:260 +0x41a
main.RunCustom(0xc0001ba010, 0x3, 0x3, 0xc000190058)
        github.com/hashicorp/nomad/main.go:142 +0x49c
main.Run(...)
        github.com/hashicorp/nomad/main.go:87
main.main()
        github.com/hashicorp/nomad/main.go:83 +0x65
```

**Comment by tgross** [comment]
Looks like we never exercise this code path in https://github.com/hashicorp/nomad-enterprise/blob/main/e2e/quotas/quotas_ent.go, which would be nice to do as part of the fix here.

**Comment by tgross** [comment]
I've narrowed this down a bit: looks like this is only happening if I use Nomad 1.1.0/1.1.0+ent with a server that is Nomad 1.0.4+ent.
