### ISSUE TITLE
Panic when using `nomad job stop`

### ISSUE THREAD

**Issue by evandam** [hashicorp/nomad#10923]
### Nomad version

```
Nomad v1.1.2 (60638a086ef9630e2a9ba1e237e8426192a44244)
```

### Operating system and Environment details

Ubuntu 18.04

### Issue

Running `nomad job stop <job_id>` is causing panics when monitoring. This is being run in a CI environment, not an interactive shell (assuming related to the `.ttyMonitor` in the stacktrace.

Including `-detach` avoids the panic, but means we can't wait for the job to stop successfully before moving on.

### Nomad Client logs (if appropriate)

```
==> 2021-07-21T18:46:16Z: Monitoring evaluation "d27ca872"
    2021-07-21T18:46:16Z: Evaluation triggered by job "automation-frontend-web-w2-a960949"
==> 2021-07-21T18:46:17Z: Monitoring evaluation "d27ca872"
    2021-07-21T18:46:17Z: Evaluation within deployment: "22dcae3a"
    2021-07-21T18:46:17Z: Evaluation status changed: "pending" -> "complete"
==> 2021-07-21T18:46:17Z: Evaluation "d27ca872" finished with status "complete"
==> 2021-07-21T18:46:17Z: Monitoring deployment "22dcae3a"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x618 pc=0x2157862]
goroutine 102 [running]:
github.com/mitchellh/go-glint.tree(0x2fcebc0, 0xc0007b87e0, 0x0, 0x2f87de0, 0xc000480e80, 0x0)
	github.com/mitchellh/go-glint@v0.0.0-20201119015200-53f6eb3bf4d2/tree.go:39 +0x162
github.com/mitchellh/go-glint.tree(0x2fcebc0, 0xc0007b87e0, 0x0, 0x2f87e60, 0xc0007b6c78, 0xc000480d00)
	github.com/mitchellh/go-glint@v0.0.0-20201119015200-53f6eb3bf4d2/tree.go:32 +0x6c7
github.com/mitchellh/go-glint.(*Document).RenderFrame(0xc0008c5590)
	github.com/mitchellh/go-glint@v0.0.0-20201119015200-53f6eb3bf4d2/document.go:190 +0x1c5
github.com/mitchellh/go-glint.(*Document).Render(0xc0008c5590, 0x2fceb18, 0xc000482200)
	github.com/mitchellh/go-glint@v0.0.0-20201119015200-53f6eb3bf4d2/document.go:138 +0xc5
created by github.com/hashicorp/nomad/command.(*DeploymentStatusCommand).ttyMonitor
	github.com/hashicorp/nomad/command/deployment_status.go:218 +0x38e
```

**Comment by jrasell** [comment]
Hi @evandam and thanks for the report. This is something we will certainly look to try get fixed up in the next release.

**Comment by ulfdalen** [comment]
We have the same problem. Really looking forward to the fix.
