### ISSUE TITLE
Creating a Consul mesh gateway with host networking mode causes segfault

### ISSUE THREAD

**Issue by krarey** [hashicorp/nomad#11243]
### Nomad version
Nomad v1.1.5 (117a23d2cdf26a1837b21c84f30c8c0f3441e927)

### Operating system and Environment details
Ubuntu 20.04 LTS
Nomad OSS v1.1.5
Consul OSS v1.10.3
Nomad ACLs/TLS disabled

### Issue

When issuing a job containing a Consul mesh gateway, if the `network` mode is set to `host`, a segfault is triggered on the node that receives the allocation. Nodes then fail in sequence as the allocation is re-tried across the cluster.

### Reproduction steps
Issue the following job:
```hcl
job "consul-gw" {
  datacenters = ["dc1"]
  group "mesh" {
    network {
      mode = "host"
      port "mesh" {
        static = 8443
      }
    }
    service {
      name = "mesh-gateway"
      port = 8443

      connect {
        gateway {
          mesh {}
        }
      }
    }
  }
}
```
#### Expected Result
Either a mesh gateway job is successfully submitted, or validation fails and the job is rejected.

#### Actual Result
```
Sep 29 23:43:11 nomad-server-3 nomad[35258]: panic: runtime error: invalid memory address or nil pointer dereference
Sep 29 23:43:11 nomad-server-3 nomad[35258]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x186ed58]
Sep 29 23:43:11 nomad-server-3 nomad[35258]: goroutine 308 [running]:
Sep 29 23:43:11 nomad-server-3 nomad[35258]: github.com/hashicorp/nomad/command/agent/consul.(*ServiceClient).serviceRegs(0xc0008861e0, 0xc000522600, 0xc0007909c0, 0xc000945500, 0xc000945500, 0xc0, 0xc0)
Sep 29 23:43:11 nomad-server-3 nomad[35258]:         github.com/hashicorp/nomad/command/agent/consul/service_client.go:1113 +0xcb8
Sep 29 23:43:11 nomad-server-3 nomad[35258]: github.com/hashicorp/nomad/command/agent/consul.(*ServiceClient).RegisterWorkload(0xc0008861e0, 0xc000945500, 0xc00077cba0, 0xc000b4ada0)
Sep 29 23:43:11 nomad-server-3 nomad[35258]:         github.com/hashicorp/nomad/command/agent/consul/service_client.go:1214 +0x152
Sep 29 23:43:11 nomad-server-3 nomad[35258]: github.com/hashicorp/nomad/client/allocrunner.(*groupServiceHook).prerunLocked(0xc0008862d0, 0x41046a, 0x26f0fa0)
Sep 29 23:43:11 nomad-server-3 nomad[35258]:         github.com/hashicorp/nomad/client/allocrunner/groupservice_hook.go:113 +0x5e
Sep 29 23:43:11 nomad-server-3 nomad[35258]: github.com/hashicorp/nomad/client/allocrunner.(*groupServiceHook).Prerun(0xc0008862d0, 0x0, 0x0)
Sep 29 23:43:11 nomad-server-3 nomad[35258]:         github.com/hashicorp/nomad/client/allocrunner/groupservice_hook.go:104 +0x70
Sep 29 23:43:11 nomad-server-3 nomad[35258]: github.com/hashicorp/nomad/client/allocrunner.(*allocRunner).prerun(0xc00057cd80, 0x0, 0x0)
Sep 29 23:43:11 nomad-server-3 nomad[35258]:         github.com/hashicorp/nomad/client/allocrunner/alloc_runner_hooks.go:195 +0x1fc
Sep 29 23:43:11 nomad-server-3 nomad[35258]: github.com/hashicorp/nomad/client/allocrunner.(*allocRunner).Run(0xc00057cd80)
Sep 29 23:43:11 nomad-server-3 nomad[35258]:         github.com/hashicorp/nomad/client/allocrunner/alloc_runner.go:314 +0x105
Sep 29 23:43:11 nomad-server-3 nomad[35258]: created by github.com/hashicorp/nomad/client.(*Client).addAlloc
Sep 29 23:43:11 nomad-server-3 nomad[35258]:         github.com/hashicorp/nomad/client/client.go:2461 +0x8f0
Sep 29 23:43:11 nomad-server-3 systemd[1]: nomad.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

**Comment by krarey** [comment]
It is also worth noting, the same error occurs when using a proper named label in service.port as well.

**Comment by jrasell** [comment]
Hi @krarey, thanks for raising this issue and detailing a minimal jobspec to test the bug; I was able to reproduce this locally using current main.

**Comment by lgfa29** [comment]
Hi @krarey,

I think we're missing handling a `gateway` without `proxy` when the network mode is `host`. Could you try adding a `proxy` block to your config and see if that fixes the problem?

```diff
job "consul-gw" {
  datacenters = ["dc1"]
  group "mesh" {
    network {
      mode = "host"
      port "mesh" {
        static = 8443
      }
    }
    service {
      name = "mesh-gateway"
      port = 8443

      connect {
        gateway {
          mesh {}
+         proxy {}
        }
      }
    }
  }
}
```

**Comment by krarey** [comment]
Hey @lgfa29,

Tested adding the `proxy {}` stanza and it does allow this job to allocate and work as expected. Thanks!
