### ISSUE TITLE
CSI Plugin:  invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by cerias** [hashicorp/nomad#11405]
### Nomad version
Nomad v1.1.6 (b83d623fb5ff475d5e40df21e9e7a61834071078)

### Operating system and Environment details
Uubuntu 20.04

### Issue
Deploying the hetzner csi plugin as system job, deployment fails.

Or an missing configuration step on my site. :)

### Reproduction steps
My job config:

My Nomad Agent config:
```hcl
datacenter = "dc1"
data_dir   = "/opt/nomad"
bind_addr  = "{{vlan_ip}}"
advertise {
  http = "{{vlan_ip}}"
}
client {
  enabled = true
  server_join {
    retry_join = ["{{nomad_master_ip}}"]
  }
  network_interface = "ens10"

}
plugin "docker" {
  config {
    allow_privileged = true
  }
}
consul {
  token = "{{agent_token.stdout}}"
}
```

#### Expected Result
An running csi plugin :)

### Job file (if appropriate)
```hcl
job "node" {
  datacenters = ["dc1"]
  type = "system"

  group "node" {
    task "plugin" {
      driver = "docker"

      config {
        image = "hetznercloud/hcloud-csi-driver:1.5.3"
        privileged = true
      }

      env {
        CSI_ENDPOINT="unix:///csi/csi.sock"
        HCLOUD_TOKEN="<<token>>"
      }

      csi_plugin {
        id        = "csi.hetzner.cloud"
        type      = "monolith"
        mount_dir = "/csi"
      }
    }
  }
}
```

### Nomad Server logs 
```
Oct 28 19:55:03 server2 nomad[28513]:     2021-10-28T19:55:03.185+0200 [INFO]  client.driver_mgr.docker: created container: driver=docker container_id=356566afc702bec596d90d63c8c318fb8858fe8991eebfaf3435946ee3cd0713
Oct 28 19:55:03 server2 nomad[28513]:     2021-10-28T19:55:03.480+0200 [INFO]  client.driver_mgr.docker: started container: driver=docker container_id=356566afc702bec596d90d63c8c318fb8858fe8991eebfaf3435946ee3cd0713
Oct 28 19:55:03 server2 nomad[28513]:     2021-10-28T19:55:03.951+0200 [INFO]  client.alloc_runner.task_runner: restarting task: alloc_id=d46e294d-e4fa-bf9b-1c40-50d5a2690b06 task=plugin reason="Restart within policy" delay=17.142869217s
Oct 28 19:55:21 server2 nomad[28513]:     2021-10-28T19:55:21.097+0200 [INFO]  client.alloc_runner.task_runner.task_hook.logmon.nomad: opening fifo: alloc_id=d46e294d-e4fa-bf9b-1c40-50d5a2690b06 task=plugin @module=logmon path=/opt/nomad/alloc/d46e294d-e4fa-bf9b-1c40-50d5a2690b06/alloc/logs/.plugin.stdout.fifo timestamp=2021-10-28T19:55:21.097+0200
Oct 28 19:55:21 server2 nomad[28513]:     2021-10-28T19:55:21.097+0200 [INFO]  client.alloc_runner.task_runner.task_hook.logmon.nomad: opening fifo: alloc_id=d46e294d-e4fa-bf9b-1c40-50d5a2690b06 task=plugin @module=logmon path=/opt/nomad/alloc/d46e294d-e4fa-bf9b-1c40-50d5a2690b06/alloc/logs/.plugin.stderr.fifo timestamp=2021-10-28T19:55:21.097+0200
Oct 28 19:55:21 server2 nomad[28513]:     2021-10-28T19:55:21.160+0200 [INFO]  client.driver_mgr.docker: created container: driver=docker container_id=56542470486a3dd01e9fb34215c79495551037b0885c3a5caa4f87db1987350b
Oct 28 19:55:21 server2 nomad[28513]:     2021-10-28T19:55:21.424+0200 [INFO]  client.driver_mgr.docker: started container: driver=docker container_id=56542470486a3dd01e9fb34215c79495551037b0885c3a5caa4f87db1987350b
Oct 28 19:55:21 server2 nomad[28513]:     2021-10-28T19:55:21.805+0200 [INFO]  client.alloc_runner.task_runner: restarting task: alloc_id=d46e294d-e4fa-bf9b-1c40-50d5a2690b06 task=plugin reason="Restart within policy" delay=16.741832541s
Oct 28 19:55:38 server2 nomad[28513]:     2021-10-28T19:55:38.550+0200 [INFO]  client.alloc_runner.task_runner.task_hook.logmon.nomad: opening fifo: alloc_id=d46e294d-e4fa-bf9b-1c40-50d5a2690b06 task=plugin path=/opt/nomad/alloc/d46e294d-e4fa-bf9b-1c40-50d5a2690b06/alloc/logs/.plugin.stdout.fifo @module=logmon timestamp=2021-10-28T19:55:38.550+0200
Oct 28 19:55:38 server2 nomad[28513]:     2021-10-28T19:55:38.550+0200 [INFO]  client.alloc_runner.task_runner.task_hook.logmon.nomad: opening fifo: alloc_id=d46e294d-e4fa-bf9b-1c40-50d5a2690b06 task=plugin @module=logmon path=/opt/nomad/alloc/d46e294d-e4fa-bf9b-1c40-50d5a2690b06/alloc/logs/.plugin.stderr.fifo timestamp=2021-10-28T19:55:38.550+0200
Oct 28 19:55:38 server2 nomad[28513]:     2021-10-28T19:55:38.577+0200 [INFO]  client.driver_mgr.docker: created container: driver=docker container_id=f69152dcd04925e9a4bedd523c91625006308a846ddbc7f8b4fbfa551f8da366
Oct 28 19:55:38 server2 nomad[28513]:     2021-10-28T19:55:38.827+0200 [INFO]  client.driver_mgr.docker: started container: driver=docker container_id=f69152dcd04925e9a4bedd523c91625006308a846ddbc7f8b4fbfa551f8da366
Oct 28 19:55:39 server2 nomad[28513]:     2021-10-28T19:55:39.324+0200 [INFO]  client.alloc_runner.task_runner: not restarting task: alloc_id=d46e294d-e4fa-bf9b-1c40-50d5a2690b06 task=plugin reason="Exceeded allowed attempts 2 in interval 30m0s and mode is "fail""
Oct 28 19:55:39 server2 nomad[28513]:     2021-10-28T19:55:39.327+0200 [INFO]  client.gc: marking allocation for GC: alloc_id=d46e294d-e4fa-bf9b-1c40-50d5a2690b06
```

### Nomad alloc logs
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x905701]

goroutine 1 [running]:
main.main()
	/csi/cmd/driver/main.go:125 +0x12c1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x905701]

goroutine 1 [running]:
main.main()
	/csi/cmd/driver/main.go:125 +0x12c1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x905701]

goroutine 1 [running]:
main.main()
	/csi/cmd/driver/main.go:125 +0x12c1
```

**Comment by jrasell** [comment]
Hi @cerias, the panic fix has now been merged on the CSI plugin side. The logs don't indicate to me what the problem might be here, but it's not anything I believe to do with Nomad. I'd suggest raising this with `hetznercloud` as they will certainly be able to help and understand better.

**Comment by cerias** [comment]
Hmm yes, i will do that. Thanks for your help @jrasell . I will close the Issue for now and debug it with hetzner:)
