### ISSUE TITLE
data-race detected in state store

### ISSUE THREAD

**Issue by shoenig** [hashicorp/nomad#12098]
While messing around with running CI in GHA
```
WARNING: DATA RACE
Write at 0x00c00049a760 by goroutine 30:
  github.com/hashicorp/nomad/nomad/state.(*StateStore).upsertAllocsImpl()
      /home/runner/work/nomad/nomad/nomad/state/state_store.go:3378 +0x294
  github.com/hashicorp/nomad/nomad/state.(*StateStore).UpsertAllocs()
      /home/runner/work/nomad/nomad/nomad/state/state_store.go:3336 +0x129
  github.com/hashicorp/nomad/nomad/drainer.TestDrainingJobWatcher_DrainJobs()
      /home/runner/work/nomad/nomad/nomad/drainer/watch_jobs_test.go:192 +0xd6f
  testing.tRunner()
      /opt/hostedtoolcache/go/1.17.7/x64/src/testing/testing.go:1259 +0x22f
  testing.(*T).Run·dwrap·21()
      /opt/hostedtoolcache/go/1.17.7/x64/src/testing/testing.go:1306 +0x47

Previous read at 0x00c00049a760 by goroutine 62:
  github.com/hashicorp/nomad/nomad/drainer.(*drainingJobWatcher).getJobAllocsImpl()
      /home/runner/work/nomad/nomad/nomad/drainer/watch_jobs.go:466 +0x4f1
  github.com/hashicorp/nomad/nomad/drainer.(*drainingJobWatcher).getJobAllocsImpl-fm()
      /home/runner/work/nomad/nomad/nomad/drainer/watch_jobs.go:441 +0x59
  github.com/hashicorp/nomad/nomad/state.(*StateStore).BlockingQuery()
      /home/runner/work/nomad/nomad/nomad/state/state_store.go:308 +0xee
  github.com/hashicorp/nomad/nomad/drainer.(*drainingJobWatcher).getJobAllocs()
      /home/runner/work/nomad/nomad/nomad/drainer/watch_jobs.go:429 +0xfb
  github.com/hashicorp/nomad/nomad/drainer.(*drainingJobWatcher).watch()
      /home/runner/work/nomad/nomad/nomad/drainer/watch_jobs.go:151 +0x21e
  github.com/hashicorp/nomad/nomad/drainer.NewDrainingJobWatcher·dwrap·18()
      /home/runner/work/nomad/nomad/nomad/drainer/watch_jobs.go:88 +0x39
```

**Comment by tgross** [comment]
Two fixes for the CSI-related items: https://github.com/hashicorp/nomad/pull/12553 https://github.com/hashicorp/nomad/pull/12554

**Comment by tgross** [comment]
Another possible in https://app.circleci.com/pipelines/github/hashicorp/nomad/28486/workflows/88d021ae-09b1-47b3-a777-e53777ea08ad/jobs/314220.

**Comment by shoenig** [comment]
New race in CaptureFiles

```
    operator_debug_test.go:437: [TEST] Client for test TestDebug_CapturedFiles ready, id: df6ec249-b6bd-bbe3-e0d3-9e6857b0bd85, region: global
    operator_debug_test.go:439: serverName: TestDebug_CapturedFiles.global, clientID, df6ec249-b6bd-bbe3-e0d3-9e6857b0bd85
2022-08-02T13:07:14.945Z [TRACE] client/client.go:1919: client: next heartbeat: period=13.097315477s
2022-08-02T13:07:14.945Z [DEBUG] agent/http.go:579: http: request complete: method=GET path=/v1/nodes duration="171.768µs"
2022-08-02T13:07:14.946Z [DEBUG] agent/http.go:579: http: request complete: method=GET path=/v1/nodes?prefix=df6ec249-b6bd-bbe3-e0d3-9e6857b0bd85 duration="156.114µs"
2022-08-02T13:07:14.946Z [DEBUG] agent/http.go:579: http: request complete: method=GET path=/v1/agent/members duration="129.636µs"
2022-08-02T13:07:14.947Z [DEBUG] agent/http.go:579: http: request complete: method=GET path=/v1/status/leader duration="146.175µs"
fatal error: concurrent map read and map write

goroutine 39028 [running]:
runtime.throw({0x2abda8e?, 0x296a0a0?})
	/usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc005f789f0 sp=0xc005f789c0 pc=0x43c2f1
runtime.mapaccess2(0xc0094c4bb0?, 0xc001e9ec30?, 0x4588680?)
	/usr/local/go/src/runtime/map.go:476 +0x205 fp=0xc005f78a30 sp=0xc005f789f0 pc=0x412945
reflect.mapaccess(0x254a060?, 0xc0094c4bb0?, 0xc0094c4bb0?)
	/usr/local/go/src/runtime/map.go:1331 +0x19 fp=0xc005f78a58 sp=0xc005f78a30 pc=0x468f19
reflect.Value.MapIndex({0x24c5160?, 0xc001e9ec80?, 0xc005a26640?}, {0x254a060, 0xc0094c4bb0, 0x94})
	/usr/local/go/src/reflect/value.go:1616 +0x151 fp=0xc005f78ac8 sp=0xc005f78a58 pc=0x4e33b1
github.com/mitchellh/reflectwalk.walkMap({0x24c5160?, 0xc001e9ec80?, 0xc005a26640?}, {0x296a0a0, 0xc005a26640})
	/home/circleci/.go_workspace/pkg/mod/github.com/mitchellh/reflectwalk@v1.0.2/reflectwalk.go:252 +0x315 fp=0xc005f78ba8 sp=0xc005f78ac8 pc=0x702275
github.com/mitchellh/reflectwalk.walk({0x24c5160?, 0xc001e9ec80?, 0xc005a26640?}, {0x296a0a0, 0xc005a26640})
	/home/circleci/.go_workspace/pkg/mod/github.com/mitchellh/reflectwalk@v1.0.2/reflectwalk.go:200 +0x5aa fp=0xc005f78c90 sp=0xc005f78ba8 pc=0x701b4a
github.com/mitchellh/reflectwalk.walkStruct({0x2925420?, 0xc001e9ec60?, 0xc005a26640?}, {0x296a0a0, 0xc005a26640})
	/home/circleci/.go_workspace/pkg/mod/github.com/mitchellh/reflectwalk@v1.0.2/reflectwalk.go:404 +0x3d5 fp=0xc005f78e10 sp=0xc005f78c90 pc=0x702c35
github.com/mitchellh/reflectwalk.walk({0x290e760?, 0xc007c1e040?, 0xc005a26640?}, {0x296a0a0, 0xc005a26640})
	/home/circleci/.go_workspace/pkg/mod/github.com/mitchellh/reflectwalk@v1.0.2/reflectwalk.go:206 +0x6af fp=0xc005f78ef8 sp=0xc005f78e10 pc=0x701c4f
github.com/mitchellh/reflectwalk.walkStruct({0x29f1740?, 0xc007c1e000?, 0xc005a26640?}, {0x296a0a0, 0xc005a26640})
	/home/circleci/.go_workspace/pkg/mod/github.com/mitchellh/reflectwalk@v1.0.2/reflectwalk.go:404 +0x3d5 fp=0xc005f79078 sp=0xc005f78ef8 pc=0x702c35
github.com/mitchellh/reflectwalk.walk({0x230c420?, 0xc002964530?, 0xc005a26640?}, {0x296a0a0, 0xc005a26640})
	/home/circleci/.go_workspace/pkg/mod/github.com/mitchellh/reflectwalk@v1.0.2/reflectwalk.go:206 +0x6af fp=0xc005f79160 sp=0xc005f79078 pc=0x701c4f
github.com/mitchellh/reflectwalk.walkStruct({0x29dc200?, 0xc002964400?, 0xc005a26640?}, {0x296a0a0, 0xc005a26640})
	/home/circleci/.go_workspace/pkg/mod/github.com/mitchellh/reflectwalk@v1.0.2/reflectwalk.go:404 +0x3d5 fp=0xc005f792e0 sp=0xc005f79160 pc=0x702c35
github.com/mitchellh/reflectwalk.walk({0x25862a0?, 0xc002964400?, 0xc005a26640?}, {0x296a0a0, 0xc005a26640})
	/home/circleci/.go_workspace/pkg/mod/github.com/mitchellh/reflectwalk@v1.0.2/reflectwalk.go:206 +0x6af fp=0xc005f793c8 sp=0xc005f792e0 pc=0x701c4f
github.com/mitchellh/reflectwalk.Walk({0x25862a0?, 0xc002964400?}, {0x296a0a0, 0xc005a26640})
	/home/circleci/.go_workspace/pkg/mod/github.com/mitchellh/reflectwalk@v1.0.2/reflectwalk.go:99 +0x146 fp=0xc005f79438 sp=0xc005f793c8 pc=0x701526
github.com/mitchellh/copystructure.Config.Copy({0x0?, 0x0?, 0x0?}, {0x25862a0?, 0xc002964400})
	/home/circleci/.go_workspace/pkg/mod/github.com/mitchellh/copystructure@v1.2.0/copystructure.go:116 +0x188 fp=0xc005f794b0 sp=0xc005f79438 pc=0x703188
github.com/mitchellh/copystructure.Copy(...)
	/home/circleci/.go_workspace/pkg/mod/github.com/mitchellh/copystructure@v1.2.0/copystructure.go:36
github.com/hashicorp/nomad/command/agent.(*HTTPServer).AgentSelfRequest(0xc003bb88c0, {0x0?, 0xc005f79778?}, 0x4950d7?)
	/home/circleci/go/src/github.com/hashicorp/nomad/command/agent/agent_endpoint.go:84 +0x33e fp=0xc005f79758 sp=0xc005f794b0 pc=0x1fd499e
github.com/hashicorp/nomad/command/agent.(*HTTPServer).AgentSelfRequest-fm({0x3025740?, 0xc000fa9360?}, 0xc00096f704?)
	<autogenerated>:1 +0x3c fp=0xc005f79788 sp=0xc005f79758 pc=0x2021cfc
github.com/hashicorp/nomad/command/agent.(*HTTPServer).wrap.func1({0x3025740, 0xc000fa9360}, 0xc0044c3a00)
	/home/circleci/go/src/github.com/hashicorp/nomad/command/agent/http.go:581 +0x154 fp=0xc005f798a0 sp=0xc005f79788 pc=0x1fff954
net/http.HandlerFunc.ServeHTTP(0xc007aed880?, {0x3025740?, 0xc000fa9360?}, 0xc005f79908?)
	/usr/local/go/src/net/http/server.go:2084 +0x2f fp=0xc005f798c8 sp=0xc005f798a0 pc=0x803d2f
net/http.(*ServeMux).ServeHTTP(0x0?, {0x3025740, 0xc000fa9360}, 0xc0044c3a00)
	/usr/local/go/src/net/http/server.go:2462 +0x149 fp=0xc005f79918 sp=0xc005f798c8 pc=0x805b89
github.com/gorilla/handlers.CompressHandlerLevel.func1({0x3023d60?, 0xc000d0d260}, 0xc0044c3a00)
	/home/circleci/.go_workspace/pkg/mod/github.com/gorilla/handlers@v1.5.1/compress.go:141 +0x663 fp=0xc005f79a70 sp=0xc005f79918 pc=0x1f4b7a3
net/http.HandlerFunc.ServeHTTP(0x0?, {0x3023d60?, 0xc000d0d260?}, 0x4554960?)
	/usr/local/go/src/net/http/server.go:2084 +0x2f fp=0xc005f79a98 sp=0xc005f79a70 pc=0x803d2f
net/http.serverHandler.ServeHTTP({0xc006836d50?}, {0x3023d60, 0xc000d0d260}, 0xc0044c3a00)
	/usr/local/go/src/net/http/server.go:2916 +0x43b fp=0xc005f79b58 sp=0xc005f79a98 pc=0x8077db
net/http.(*conn).serve(0xc005a26000, {0x3025bd8, 0xc007a4e8a0})
	/usr/local/go/src/net/http/server.go:1966 +0x5d7 fp=0xc005f79fb8 sp=0xc005f79b58 pc=0x8027d7
net/http.(*Server).Serve.func3()
	/usr/local/go/src/net/http/server.go:3071 +0x2e fp=0xc005f79fe0 sp=0xc005f79fb8 pc=0x80812e
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc005f79fe8 sp=0xc005f79fe0 pc=0x46fe21
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3071 +0x4db
```
