### ISSUE TITLE
-config option fails and throws error when directory is passed.

### ISSUE THREAD

**Issue by clstokes** [hashicorp/nomad#123]
When starting nomad with the `-config` option and passing a path to a directory, Nomad fails and throws an error. Passing a path to a file works fine.

#### Error
```
$ nomad agent -config="/etc/nomad.d/"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x8 pc=0x49120d]

goroutine 1 [running]:
github.com/hashicorp/nomad/command/agent.(*Config).Merge(0xc820077b00, 0x0, 0x0)
	/home/ubuntu/go/src/github.com/hashicorp/nomad/command/agent/config.go:251 +0x6d
github.com/hashicorp/nomad/command/agent.(*Command).readConfig(0xc820087a40, 0xb09e00)
	/home/ubuntu/go/src/github.com/hashicorp/nomad/command/agent/command.go:109 +0xf09
...
```

#### Successful
```
$ nomad agent -config="/etc/nomad.d/nomad.conf"
==> Starting Nomad agent...
==> Error starting agent: must have at least client or server mode enabled
ubuntu@ip-172-31-10-48:~$
```

Full error log and successful log at https://gist.github.com/clstokes/4cb766a9209dda8fff65.

**Comment by ryanuber** [comment]
This should be fixed in 61f4e63 !
