### ISSUE TITLE
test: data race in `TestPeriodicDispatch_Add_TriggersUpdate`

### ISSUE THREAD

**Issue by tgross** [hashicorp/nomad#12331]
While running tests for PR https://github.com/hashicorp/nomad/pull/12325 I ran into what appears to be a data race in the `TestPeriodicDispatch_Add_TriggersUpdate` (and possibly that entire file of tests). 

At first glance it looks like an issue in the test setup. We create a periodic dispatcher and enable it, which calls `run()` in a goroutine. In the main goroutine we `p.Add` a job, which requires that `run()` reached the `enabled = true` bit. I'm not sure why that wouldn't result in an empty heap which we should be handling safely. For some reason the main test goroutine always "won" that race previously and this time we didn't. Maybe it was discovered found by the new parallelism approach for testing? I've opened this issue so that I remember to come back and investigate after my current pile of tasks is complete.

[Failing test run](https://app.circleci.com/pipelines/github/hashicorp/nomad/21215/workflows/69aa8799-3271-432a-b43d-576374386f23/jobs/220276):

```
Failed
=== RUN   TestPeriodicDispatch_Add_TriggersUpdate
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x190e8c0]

goroutine 75542 [running]:
github.com/hashicorp/nomad/nomad/structs.(*PeriodicConfig).GetLocation(...)
	/home/circleci/go/src/github.com/hashicorp/nomad/nomad/structs/structs.go:5281
github.com/hashicorp/nomad/nomad.(*PeriodicDispatch).run(0xc00252a120, {0x2413fc0, 0xc0040dbb00}, 0xc00312f200)
	/home/circleci/go/src/github.com/hashicorp/nomad/nomad/periodic.go:342 +0x120
created by github.com/hashicorp/nomad/nomad.(*PeriodicDispatch).SetEnabled
	/home/circleci/go/src/github.com/hashicorp/nomad/nomad/periodic.go:188 +0x18f
```

**Comment by tgross** [comment]
I had a few spare moments to look at this and the only way we could get this exact stack trace is if the `Periodic` block was nil, not the Job itself (note the `addr` in particular here). I can't figure out a way this can possibly happen because the job wouldn't have been marked as `IsPeriodic` and we only _have_ one job here which is a mock periodic job. It's never appeared again and doesn't seem to have a production impact, so unfortunately I'm going to just close this one out as an unsolved mystery.
