### ISSUE TITLE
Jobspec using validation with missing constraint causes panic

### ISSUE THREAD

**Issue by shoenig** [hashicorp/nomad#12513]
While looking over https://github.com/hashicorp/nomad/pull/12508 I had a typo in my own example and triggered a panic of the CLI. A missing `condition` in the `validation` block of a `variable` block gets through jobspec validation itself, and causes a NPE. 

```hcl
variable "image_id" {
  type          = string
  description   = "Check on image names."

  validation {
    # condition  =   substr(var.image_id, 0, 4) == "foo-" 
    error_message = "Must use a foo image."
  }
}

job "example" {
  datacenters = ["dc1"]

  group "cache" {
    network {
      port "db" {
        to = 6379
      }
    }

    task "redis" {
      driver = "docker"
      config {
        image = "${var.image_id}"
        ports = ["db"]
      }
    }
  }
}
```

```
➜ nomad job run -var 'image_id=foo-' example.nomad
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1be87d9]

goroutine 1 [running]:
github.com/hashicorp/nomad/jobspec2.(*Variable).validateValue(0xc000909ea0, {{0x25b2ed8, 0x3}, {{{0x2b067c8, 0xc0004bcd69}}, {0x1fa0820, 0xc000b4d1b0}}, {0x7f03143459f0, 0xc000c304e0}})
	github.com/hashicorp/nomad/jobspec2/types.variables.go:99 +0x359
github.com/hashicorp/nomad/jobspec2.(*Variable).Value(0x120)
	github.com/hashicorp/nomad/jobspec2/types.variables.go:159 +0x145
github.com/hashicorp/nomad/jobspec2.Variables.Values(0xc0003a1730)
	github.com/hashicorp/nomad/jobspec2/types.variables.go:176 +0xd9
github.com/hashicorp/nomad/jobspec2.(*jobConfig).decodeBody(0xc0003a1730, {0x2b054c0, 0xc0002d3550})
	github.com/hashicorp/nomad/jobspec2/types.config.go:68 +0x2da
github.com/hashicorp/nomad/jobspec2.decode(0xc0003a1730)
	github.com/hashicorp/nomad/jobspec2/parse.go:105 +0xc9
github.com/hashicorp/nomad/jobspec2.ParseWithConfig(0xc0002d2f20)
	github.com/hashicorp/nomad/jobspec2/parse.go:44 +0xe5
github.com/hashicorp/nomad/command.(*JobGetter).ApiJobWithArgs(0xc000b930f0, {0x7ffcdd7e7319, 0xd}, {0xc000b4cce0, 0x1, 0x1}, {0x0, 0x0, 0x0}, 0x1)
	github.com/hashicorp/nomad/command/helpers.go:455 +0x76d
github.com/hashicorp/nomad/command.(*JobRunCommand).Run(0xc000b93040, {0xc00004e210, 0x3, 0x3})
	github.com/hashicorp/nomad/command/job_run.go:218 +0x68e
github.com/mitchellh/cli.(*CLI).Run(0xc000496640)
	github.com/mitchellh/cli@v1.1.2/cli.go:262 +0x5f8
main.RunCustom({0xc00004e1f0, 0x1f76220, 0xc0000001a0})
	github.com/hashicorp/nomad/main.go:115 +0x33d
main.Run(...)
	github.com/hashicorp/nomad/main.go:85
main.main()
	github.com/hashicorp/nomad/main.go:81 +0x50
```

**Comment by tgross** [comment]
Fixed in https://github.com/hashicorp/nomad/pull/16018 which will ship in Nomad 1.5.0 (with backports)
