### ISSUE TITLE
panic parsing JSON config file

### ISSUE THREAD

**Issue by The-Loeki** [hashicorp/nomad#1290]
### Nomad version
0.3.2
0.4.0-rc1

### Operating system and Environment details
CentOS 7 64-bit
Ubuntu 16.04 64-bit

### Issue
Upon parsing a seemingly correct JSON config file, Nomad agent panics with an index-out-of-range.

### Reproduction steps
```
root@n01:~# cat /etc/nomad/borking-config.json
{
  "client": {
    "options": {
      "driver.whitelist": "docker"
    }
  }
}
root@n01:~# /usr/local/bin/nomad agent -log-level=DEBUG -config /etc/nomad/borking-config.json 
```

### Nomad Client logs (if appropriate)
```
root@n01:~# /usr/local/bin/nomad agent -version
Nomad v0.4.0-dev ('bc09a0444722617a3a0ee0daa28d24b93d9d3e5b+CHANGES'
root@n01:~# /usr/local/bin/nomad agent -log-level=DEBUG -config /etc/nomad/borking-config.json 
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x11b6100, 0xc820010070)
	/opt/go/src/runtime/panic.go:481 +0x3e6
github.com/hashicorp/nomad/command/agent.parseClient(0xc82000de80, 0xc8201e20c0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/nomad/command/agent/config_parse.go:298 +0xbc7
github.com/hashicorp/nomad/command/agent.parseConfig(0xc82000de00, 0xc820149a40, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/nomad/command/agent/config_parse.go:145 +0x8e7
github.com/hashicorp/nomad/command/agent.ParseConfig(0x7f66f0d97258, 0xc820026150, 0xc820026150, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/nomad/command/agent/config_parse.go:63 +0x33d
github.com/hashicorp/nomad/command/agent.ParseConfigFile(0x7fff4d5fe859, 0x1e, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/nomad/command/agent/config_parse.go:30 +0x151
github.com/hashicorp/nomad/command/agent.LoadConfig(0x7fff4d5fe859, 0x1e, 0x3, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/nomad/command/agent/config.go:813 +0x135
github.com/hashicorp/nomad/command/agent.(*Command).readConfig(0xc82014c640, 0x1231520)
	/opt/gopath/src/github.com/hashicorp/nomad/command/agent/command.go:141 +0x119f
github.com/hashicorp/nomad/command/agent.(*Command).Run(0xc82014c640, 0xc82000a070, 0x3, 0x3, 0x0)
	/opt/gopath/src/github.com/hashicorp/nomad/command/agent/command.go:380 +0x1a3
github.com/hashicorp/nomad/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc8200c2480, 0xc8200c2480, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/nomad/vendor/github.com/mitchellh/cli/cli.go:153 +0x5ee
main.RunCustom(0xc82000a060, 0x4, 0x4, 0xc82010f050, 0xc8200160b8)
	/opt/gopath/src/github.com/hashicorp/nomad/main.go:55 +0x4d5
main.Run(0xc82000a060, 0x4, 0x4, 0x1cf4350)
	/opt/gopath/src/github.com/hashicorp/nomad/main.go:20 +0x4c
main.main()
	/opt/gopath/src/github.com/hashicorp/nomad/main.go:16 +0x60
```

### RCA WIP
I'm no go expert, but looking at
https://github.com/hashicorp/nomad/blob/v0.4.0-rc1/command/agent/config_parse.go#L144
I'd say the `client` section gets detected & passed on to https://github.com/hashicorp/nomad/blob/v0.4.0-rc1/command/agent/config_parse.go#L298 which is the source of the panic, so I'm confused.
There are also several other HCL-formatted config files (including one with a `client` section) which get parsed correctly.

**Comment by bsphere** [comment]
the exact thing happens with the following json -

**Comment by amfern** [comment]
same happens for me `{"client": {"options": {}}}`
