### ISSUE TITLE
panic in nomad 1.3.0 if `server.protocol_version` is set

### ISSUE THREAD

**Issue by SLoeuillet** [hashicorp/nomad#12960]
### Nomad version
Nomad v1.3.0 (52e95d64113e01be05d585d8b4c07f6f19efebbc)

### Operating system and Environment details
Ubuntu 20.04, self-hosted
Was running 1.2.6, updated to 1.3.0

### Issue

Crash at startup after upgrade from 1.2.6, was already using raft 3
```
May 12 07:49:52 staging00-staging-stg nomad[661300]: WARNING: keyring exists but -encrypt given, using keyring
May 12 07:49:52 staging00-staging-stg nomad[661300]: panic: runtime error: invalid memory address or nil pointer dereference
May 12 07:49:52 staging00-staging-stg nomad[661300]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1f3439a]
May 12 07:49:52 staging00-staging-stg nomad[661300]: goroutine 1 [running]:
May 12 07:49:52 staging00-staging-stg nomad[661300]: github.com/hashicorp/nomad/command/agent.(*Command).IsValidConfig(0xc000125800, 0xc000546600, 0xc000c14600)
May 12 07:49:52 staging00-staging-stg nomad[661300]:         github.com/hashicorp/nomad/command/agent/command.go:439 +0xdfa
May 12 07:49:52 staging00-staging-stg nomad[661300]: github.com/hashicorp/nomad/command/agent.(*Command).readConfig(0xc000125800)
May 12 07:49:52 staging00-staging-stg nomad[661300]:         github.com/hashicorp/nomad/command/agent/command.go:296 +0x1ce5
May 12 07:49:52 staging00-staging-stg nomad[661300]: github.com/hashicorp/nomad/command/agent.(*Command).Run(0xc000125800, {0xc00004e060, 0x2, 0x2})
May 12 07:49:52 staging00-staging-stg nomad[661300]:         github.com/hashicorp/nomad/command/agent/command.go:664 +0x147
May 12 07:49:52 staging00-staging-stg nomad[661300]: github.com/mitchellh/cli.(*CLI).Run(0xc000b337c0)
May 12 07:49:52 staging00-staging-stg nomad[661300]:         github.com/mitchellh/cli@v1.1.2/cli.go:262 +0x5f8
May 12 07:49:52 staging00-staging-stg nomad[661300]: main.RunCustom({0xc00004e050, 0x229de40, 0xc0000001a0})
May 12 07:49:52 staging00-staging-stg nomad[661300]:         github.com/hashicorp/nomad/main.go:115 +0x33d
May 12 07:49:52 staging00-staging-stg nomad[661300]: main.Run(...)
May 12 07:49:52 staging00-staging-stg nomad[661300]:         github.com/hashicorp/nomad/main.go:85
May 12 07:49:52 staging00-staging-stg nomad[661300]: main.main()
May 12 07:49:52 staging00-staging-stg nomad[661300]:         github.com/hashicorp/nomad/main.go:81 +0x50
```

### Reproduction steps

Start the daemon

#### Expected Result

Upgrade works

#### Actual Result

Service crash looping

### Nomad Server logs (if appropriate)
```
May 12 07:55:23 staging00-staging-stg systemd[1]: nomad.service: Scheduled restart job, restart counter is at 110.
May 12 07:55:23 staging00-staging-stg systemd[1]: Stopped nomad.service.
May 12 07:55:23 staging00-staging-stg systemd[1]: Started nomad.service.
May 12 07:55:23 staging00-staging-stg nomad[664705]: WARNING: keyring exists but -encrypt given, using keyring
May 12 07:55:23 staging00-staging-stg nomad[664705]: panic: runtime error: invalid memory address or nil pointer dereference
May 12 07:55:23 staging00-staging-stg nomad[664705]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1f3439a]
May 12 07:55:23 staging00-staging-stg nomad[664705]: goroutine 1 [running]:
May 12 07:55:23 staging00-staging-stg nomad[664705]: github.com/hashicorp/nomad/command/agent.(*Command).IsValidConfig(0xc000c9a580, 0xc000c72400, 0xc00023c600)
May 12 07:55:23 staging00-staging-stg nomad[664705]:         github.com/hashicorp/nomad/command/agent/command.go:439 +0xdfa
May 12 07:55:23 staging00-staging-stg nomad[664705]: github.com/hashicorp/nomad/command/agent.(*Command).readConfig(0xc000c9a580)
May 12 07:55:23 staging00-staging-stg nomad[664705]:         github.com/hashicorp/nomad/command/agent/command.go:296 +0x1ce5
May 12 07:55:23 staging00-staging-stg nomad[664705]: github.com/hashicorp/nomad/command/agent.(*Command).Run(0xc000c9a580, {0xc0001aa020, 0x2, 0x2})
May 12 07:55:23 staging00-staging-stg nomad[664705]:         github.com/hashicorp/nomad/command/agent/command.go:664 +0x147
May 12 07:55:23 staging00-staging-stg nomad[664705]: github.com/mitchellh/cli.(*CLI).Run(0xc0007d4f00)
May 12 07:55:23 staging00-staging-stg nomad[664705]:         github.com/mitchellh/cli@v1.1.2/cli.go:262 +0x5f8
May 12 07:55:23 staging00-staging-stg nomad[664705]: main.RunCustom({0xc0001aa010, 0x229de40, 0xc0000001a0})
May 12 07:55:23 staging00-staging-stg nomad[664705]:         github.com/hashicorp/nomad/main.go:115 +0x33d
May 12 07:55:23 staging00-staging-stg nomad[664705]: main.Run(...)
May 12 07:55:23 staging00-staging-stg nomad[664705]:         github.com/hashicorp/nomad/main.go:85
May 12 07:55:23 staging00-staging-stg nomad[664705]: main.main()
May 12 07:55:23 staging00-staging-stg nomad[664705]:         github.com/hashicorp/nomad/main.go:81 +0x50
May 12 07:55:23 staging00-staging-stg systemd[1]: nomad.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 12 07:55:23 staging00-staging-stg systemd[1]: nomad.service: Failed with result 'exit-code'.
```

**Comment by SLoeuillet** [comment]
Rolling back to 1.2.7 binary => working

**Comment by jrasell** [comment]
Hi @SLoeuillet and thanks for raising this. To help me quickly look into this, are you able to provide a redacted version of the server configuration you're using?

**Comment by SLoeuillet** [comment]
server {
  protocol_version    = 1
}


	// ProtocolVersion has never been used. Warn if it is set as someone
	// has probably made a mistake.
	if config.Server.ProtocolVersion != 0 {
		c.agent.logger.Warn("Please remove deprecated protocol_version field from config.")
	}

**Comment by SLoeuillet** [comment]
Line 439 is : c.agent.logger.Warn("Please remove deprecated protocol_version field from config.")

**Comment by jrasell** [comment]
Hi @SLoeuillet thanks for that as it helps confirm my initial thoughts. I'll do some additional testing and should be able to raise a PR shortly.

**Comment by SLoeuillet** [comment]
Confirmed working node in 1.3.0 once server.protocol_version = 1 line has been removed
