### ISSUE TITLE
panic from dropDirPermissions

### ISSUE THREAD

**Issue by shoenig** [hashicorp/nomad#14217]
While working on an unrelated e2e test, hit this panic

```
nomad: pthread_mutex_lock.c:90: ___pthread_mutex_lock: Assertion `mutex->__data.__owner == 0' failed.
SIGABRT: abort
PC=0x7f15ab71f54c m=15 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 601 [syscall]:
runtime.cgocall(0x1e0c770, 0xc000c519b0)
	runtime/cgocall.go:158 +0x5c fp=0xc000c51988 sp=0xc000c51950 pc=0x40761c
os/user._Cfunc_mygetpwnam_r(0xc000c2c140, 0xc000d12570, 0x7f1548000b60, 0x400, 0xc000464620)
	_cgo_gotypes.go:159 +0x4c fp=0xc000c519b0 sp=0xc000c51988 pc=0xaa62ec
os/user.lookupUser.func1.1({0xc000c2c140, 0xc000760f20?, 0x0?}, 0xc000500800?, 0xc000c51a58?, 0x411547?)
	os/user/cgo_lookup_unix.go:69 +0xbb fp=0xc000c51a10 sp=0xc000c519b0 pc=0xaa6fdb
os/user.lookupUser.func1()
	os/user/cgo_lookup_unix.go:69 +0x31 fp=0xc000c51a50 sp=0xc000c51a10 pc=0xaa6ef1
os/user.retryWithBuffer(0xc000760f20, 0xc000c51b40)
	os/user/cgo_lookup_unix.go:244 +0x39 fp=0xc000c51a98 sp=0xc000c51a50 pc=0xaa8619
os/user.lookupUser({0x26d7c32, 0x6})
	os/user/cgo_lookup_unix.go:60 +0x168 fp=0xc000c51b90 sp=0xc000c51a98 pc=0xaa6cc8
os/user.Lookup({0x26d7c32, 0x6})
	os/user/lookup.go:36 +0x91 fp=0xc000c51bd0 sp=0xc000c51b90 pc=0xaa5c11
github.com/hashicorp/nomad/client/allocdir.dropDirPermissions({0xc0006e0370, 0x49}, 0xc51d30?)
	github.com/hashicorp/nomad/client/allocdir/fs_unix.go:42 +0x125 fp=0xc000c51ca8 sp=0xc000c51bd0 pc=0xdff805
github.com/hashicorp/nomad/client/allocdir.(*AllocDir).Build(0xc0004f6230)
	github.com/hashicorp/nomad/client/allocdir/alloc_dir.go:339 +0x245 fp=0xc000c51d60 sp=0xc000c51ca8 pc=0xdfcb85
github.com/hashicorp/nomad/client/allocrunner.(*allocDirHook).Prerun(0x0?)
```

**Comment by shoenig** [comment]
closing this as related to https://github.com/hashicorp/nomad/issues/14235 and probably https://github.com/hashicorp/nomad/issues/12342
