### ISSUE TITLE
node drain returning complete before jobs have stopped

### ISSUE THREAD

**Issue by srisch** [hashicorp/nomad#14293]
### Nomad version
```
Nomad v1.2.4 (9f21b724acf115a58d9ecdc97d281aef01d36387)
Nomad v1.3.3 (latest)
```

### Operating system and Environment details
`Ubuntu 20.04`
### Issue
When draining a node that is running service jobs with a long kill timeout ( say 1h ) to finish existing traffic - the node drain command instantly returns "Drain Complete" while allocations are still in the stop/running state and waiting to safely finish. 

```
nomad node drain -enable -deadline 1h 89213336
Are you sure you want to enable drain mode for node "89213336-5dda-e359-bc0a-f34e463fda79"? [y/N] y
2022-08-24T15:30:55Z: Ctrl-C to stop monitoring: will not cancel the node drain
2022-08-24T15:30:55Z: Node "89213336-5dda-e359-bc0a-f34e463fda79" drain strategy set
2022-08-24T15:30:56Z: Drain complete for node 89213336-5dda-e359-bc0a-f34e463fda79
2022-08-24T15:30:56Z: Alloc "92d17994-9a31-be8f-edbe-a635882d05c8" marked for migration
2022-08-24T15:30:56Z: Alloc "a1c99835-cdaa-45a3-ac04-ba2a007d45f8" marked for migration
2022-08-24T15:30:56Z: Alloc "92d17994-9a31-be8f-edbe-a635882d05c8" draining
2022-08-24T15:30:56Z: Alloc "a1c99835-cdaa-45a3-ac04-ba2a007d45f8" draining
```

This behavior currently causes the nomad-autoscaler with AWS to pre-emptively shut down the node before the allocation is finished.  Documentation here https://www.nomadproject.io/docs/commands/node/drain seems to indicate that
```
By default the node drain command blocks until a node is done draining and all allocations have terminated.
```   

### Reproduction steps
Set a job with a long kill_timeout so that it stays running when the node is drained - example below for HAproxy to continue handling traffic
```
kill_signal = "SIGUSR1"
kill_timeout = "1h"
```
#### Expected Result
Node drain shouldn't be complete until all allocations have stopped
#### Actual Result
Node is marked complete before all allocations have stopped

#### Idea
I do wonder if the below code is what is returning that the drain is complete.
https://github.com/hashicorp/nomad/blob/34e4b080f6279db4b96efaaeb9aca1c1d848bfb0/nomad/drainer/draining_node.go#L50-L82

**Comment by srisch** [comment]
May be related to https://github.com/hashicorp/nomad/issues/12915 ?

**Comment by tgross** [comment]
Hi @srisch! I think there may be an issue similar to #12915 in the way we're reporting that a drain is complete, so I'll take a second look at that.

But the next thing to check here is that the allocations you're talking about aren't for `system` jobs, which don't hold up the drain by default.

The full function in [`draining_node.go#L50-L82`](https://github.com/hashicorp/nomad/blob/v1.3.3/nomad/drainer/draining_node.go#L50-L82) is as follows:

```go
// IsDone returns if the node is done draining batch and service allocs. System
// allocs must be stopped before marking drain complete unless they're being
// ignored.
func (n *drainingNode) IsDone() (bool, error) {
	n.l.RLock()
	defer n.l.RUnlock()

	// Should never happen
	if n.node == nil || n.node.DrainStrategy == nil {
		return false, fmt.Errorf("node doesn't have a drain strategy set")
	}

	// Retrieve the allocs on the node
	allocs, err := n.state.AllocsByNode(nil, n.node.ID)
	if err != nil {
		return false, err
	}

	for _, alloc := range allocs {
		// System and plugin jobs are only stopped after a node is
		// done draining everything else, so ignore them here.
		if alloc.Job.Type == structs.JobTypeSystem || alloc.Job.IsPlugin() {
			continue
		}

		// If there is a non-terminal we aren't done
		if !alloc.TerminalStatus() {
			return false, nil
		}
	}

	return true, nil
}
```

From a high level, that says:
* Skip if this node has been GC'd already or isn't actually draining anymore
* Get all the allocs on the node
* If an allocation belongs a plugin or system job, don't check it
* Otherwise, we're not done draining if the allocation isn't "terminal".

Weirdly, it looks like we're checking [`TerminalStatus`](https://github.com/hashicorp/nomad/blob/v1.3.3/nomad/structs/structs.go#L9812-L9818) and not [`ClientTerminalStatus`](https://github.com/hashicorp/nomad/blob/v1.3.3/nomad/structs/structs.go#L9830-L9838) here. That doesn't seem right to me, so I'll look into that as well.

**Comment by srisch** [comment]
Hi @tgross  thank you for the quick reply and the code snippet - will definitely give it a look through and I appreciate you looking into this!

Indeed we are only using service jobs atm
```
job "haproxy-load-balancer" {
  region = var.region
  datacenters = ["default"]
  type = "service"

**Comment by srisch** [comment]
I will add I made a local test build and changed TerminalStatus to ClientTerminalStatus and it does appear to achieve desired behavior except that the drain never is marked complete even after they finish up.  Still working on understanding the code but it's some progress

```
nomad node drain -enable f5c3ac5c
Are you sure you want to enable drain mode for node "f5c3ac5c-209f-760d-e6cb-5972f12a8d12"? [y/N] y
2022-08-25T20:04:58Z: Ctrl-C to stop monitoring: will not cancel the node drain
2022-08-25T20:04:58Z: Node "f5c3ac5c-209f-760d-e6cb-5972f12a8d12" drain strategy set
2022-08-25T20:04:59Z: Alloc "0c26fe6a-f13b-9948-b8f5-25d7606e402f" marked for migration
2022-08-25T20:04:59Z: Alloc "cb8dcb56-0326-ad9f-a33a-0cb4690b4f5b" marked for migration
2022-08-25T20:04:59Z: Alloc "0c26fe6a-f13b-9948-b8f5-25d7606e402f" draining
2022-08-25T20:04:59Z: Alloc "cb8dcb56-0326-ad9f-a33a-0cb4690b4f5b" draining
2022-08-25T20:07:25Z: Alloc "0c26fe6a-f13b-9948-b8f5-25d7606e402f" status running -> complete

**Comment by tgross** [comment]
Ha, I was _just_ about to post the following that shows exactly the same! 😀  tl;dr when we do so we're somehow falling out of the `IsDone()` function in the drainer and that's why it gets stuck there. I've got a goroutine dump I'm rummaging thru to figure out why, but I've got to wrap up for the day. I should be able to come back to this tomorrow.

My original post I was about to post:

---

Ok, so I've been able to reproduce this issue. The node drain is definitely reporting that it's completed even though it's still continuing. I've got a job running on my cluster here that traps signals so we're forced to wait for 30s before getting `SIGKILL`. When I drain a node it's running on:

```
$ nomad node drain -enable e133
Are you sure you want to enable drain mode for node "e133b49c-6a52-9df4-60bb-398ed13fcc78"? [y/N] y
2022-08-25T14:36:38-04:00: Ctrl-C to stop monitoring: will not cancel the node drain
2022-08-25T14:36:38-04:00: Node "e133b49c-6a52-9df4-60bb-398ed13fcc78" drain strategy set
2022-08-25T14:36:39-04:00: Alloc "8572b0fd-6424-25e3-caae-60debbcc0813" marked for migration
2022-08-25T14:36:39-04:00: Alloc "8572b0fd-6424-25e3-caae-60debbcc0813" draining
2022-08-25T14:36:39-04:00: Drain complete for node e133b49c-6a52-9df4-60bb-398ed13fcc78
2022-08-25T14:37:09-04:00: Alloc "8572b0fd-6424-25e3-caae-60debbcc0813" status running -> complete
2022-08-25T14:37:09-04:00: All allocations on node "e133b49c-6a52-9df4-60bb-398ed13fcc78" have stopped
```

Note that we see the 30s gap between the "drain complete" message and the drain actually completing. That matches what we see in the allocation status:

```
$ nomad alloc status 8572b0fd

Recent Events:
Time                       Type        Description
2022-08-25T14:37:09-04:00  Killed      Task successfully killed
2022-08-25T14:37:09-04:00  Terminated  Exit Code: 137, Exit Message: "Docker container exited with non-zero exit code: 137"
2022-08-25T14:36:38-04:00  Killing     Sent interrupt. Waiting 30s before force killing
2022-08-25T14:35:41-04:00  Started     Task started by client
2022-08-25T14:35:41-04:00  Task Setup  Building Task Directory
2022-08-25T14:35:41-04:00  Received    Task received by client
```

In [`command/node_drain.go#L362`](https://github.com/hashicorp/nomad/blob/v1.3.3/command/node_drain.go#L362) we call `monitorDrain`, which eventually gets to this function in [`nodes.go#L273-L280`](https://github.com/hashicorp/nomad/blob/v1.3.3/api/nodes.go#L273-L280):

```go
if node.DrainStrategy == nil {
    msg := Messagef(MonitorMsgLevelInfo, "Drain complete for node %s", nodeID)
    select {
    case nodeCh <- msg:
    case <-ctx.Done():
    }
    return
}
```

This suggests the node's `DrainStrategy` is nil, which is weird because that's set synchronously with the underlying API call so I wouldn't expect some weird race condition there. But when I _poll_ the API and then run the drain, I see something like this:

```
$ while :
while> do
while> nomad operator api "/v1/node/e133b49c-6a52-9df4-60bb-398ed13fcc78" | jq '.DrainStrategy'
while> sleep 1
while> done
null
null
{
  "Deadline": 3600000000000,
  "ForceDeadline": "2022-08-25T19:36:38.118206813Z",
  "IgnoreSystemJobs": false,
  "StartedAt": "2022-08-25T18:36:38.118206813Z"
}
null
null
null
null
null
... etc, forever
```

If we look at the Node events from the node in question (which would have been a good first place to look!), we can see the node drain complete is _not_ simply a property of the monitoring, and there's no weird race condition in the API call:

```
Node Events
Time                  Subsystem  Message
2022-08-25T18:36:39Z  Drain      Node drain complete
2022-08-25T18:36:38Z  Drain      Node drain strategy set
2022-08-25T18:33:39Z  Cluster    Node registered
```

The `DrainStrategy` is getting reset!

The following patch seems like the "obvious" fix:

```diff
diff --git a/nomad/drainer/draining_node.go b/nomad/drainer/draining_node.go
index 3e3e5c2b1..447f92e7a 100644
--- a/nomad/drainer/draining_node.go
+++ b/nomad/drainer/draining_node.go
@@ -73,7 +73,7 @@ func (n *drainingNode) IsDone() (bool, error) {
                }

                // If there is a non-terminal we aren't done
-               if !alloc.TerminalStatus() {
+               if !alloc.ClientTerminalStatus() {
                        return false, nil
                }
        }
```

But this prevents the drain from _ever_ finishing, so that's not quite right either:

```
$ nomad node drain -enable 78eb
Are you sure you want to enable drain mode for node "78eb86b3-1f9f-6db2-d553-437439a35ee9"? [y/N] y
2022-08-25T15:57:11-04:00: Ctrl-C to stop monitoring: will not cancel the node drain
2022-08-25T15:57:11-04:00: Node "78eb86b3-1f9f-6db2-d553-437439a35ee9" drain strategy set
2022-08-25T15:57:12-04:00: Alloc "48152eb8-2d3a-3e6d-49af-c6049b23fa13" marked for migration
2022-08-25T15:57:12-04:00: Alloc "48152eb8-2d3a-3e6d-49af-c6049b23fa13" draining
2022-08-25T15:57:42-04:00: Alloc "48152eb8-2d3a-3e6d-49af-c6049b23fa13" status running -> complete
2022-08-25T15:57:42-04:00: All allocations on node "78eb86b3-1f9f-6db2-d553-437439a35ee9" have stopped
^C
```

If I add logging at the point I make that check, I see it gets hit twice, once with server status set to run and once with server status set to stop, but then the check never gets hit again. So 30s later when client status changes, we don't see it in the drainer and don't exit. We never come back to `IsDone()` again.

**Comment by tgross** [comment]
Ok, last item before I'm done for the day. The goroutine is stuck here:

```
goroutine 422 [select, 1 minutes]:
github.com/hashicorp/nomad/nomad/drainer.(*NodeDrainer).run(0xc000ad8c30, {0x1?, 0x1?})
	github.com/hashicorp/nomad/nomad/drainer/drainer.go:228 +0x16f
created by github.com/hashicorp/nomad/nomad/drainer.(*NodeDrainer).SetEnabled
	github.com/hashicorp/nomad/nomad/drainer/drainer.go:199 +0x135
```

So we've returned from the `handleMigratedAllocs` and just waiting on another event, which we're never getting. Tomorrow's mission will be to discover what we're missing!

**Comment by srisch** [comment]
Hivemind! I appreciate the detail!  If it helps your testing I've added some additional logging and I've found that when I use the ClientTerminalStatus i'm not hitting my log lines in 

https://github.com/hashicorp/nomad/blob/aa74aa0f14b5e0733d58d59109da39470a6db046/nomad/drainer/watch_nodes.go#L42-L116

However when I use TerminalStatus the log lines I've added within the `if done {` block seem to fire in this function and it feels like that's what's firing off the drain complete message.

When I'm using ClientTerminalStatus i'm only seemingly hitting my log lines from handleMigratedAllocs where we're getting stuck at, and it looks like you just posted that's where it's getting stuck :smile:

**Comment by tgross** [comment]
Ok, the following additional patch apparently fixes this bug by ensuring we get the event we need:

```diff
diff --git a/nomad/drainer/watch_jobs.go b/nomad/drainer/watch_jobs.go
index 36d301cc3..79ccf42f1 100644
--- a/nomad/drainer/watch_jobs.go
+++ b/nomad/drainer/watch_jobs.go
@@ -363,6 +363,10 @@ func handleTaskGroup(snap *state.StateSnapshot, batch bool, tg *structs.TaskGrou
                        drainingNodes[alloc.NodeID] = onDrainingNode
                }

+               if onDrainingNode && !alloc.ClientTerminalStatus() {
+                       result.done = false
+               }
+
                // Check if the alloc should be considered migrated. A migrated
                // allocation is one that is terminal, is on a draining
                // allocation, and has only happened since our last handled index to
```

The resulting drain for the allocation with a 30s `kill_timeout`:

```
$ nomad node drain -enable 761
Are you sure you want to enable drain mode for node "761cb7fe-4032-5182-b953-f56d00d12b85"? [y/N] y
2022-08-26T10:48:19-04:00: Ctrl-C to stop monitoring: will not cancel the node drain
2022-08-26T10:48:19-04:00: Node "761cb7fe-4032-5182-b953-f56d00d12b85" drain strategy set
2022-08-26T10:48:20-04:00: Alloc "a72c6237-9abd-aaec-c5b3-94c9142f5f8d" marked for migration
2022-08-26T10:48:20-04:00: Alloc "a72c6237-9abd-aaec-c5b3-94c9142f5f8d" draining
2022-08-26T10:48:50-04:00: Alloc "a72c6237-9abd-aaec-c5b3-94c9142f5f8d" status running -> complete
2022-08-26T10:48:50-04:00: All allocations on node "761cb7fe-4032-5182-b953-f56d00d12b85" have stopped
2022-08-26T10:48:50-04:00: Drain complete for node 761cb7fe-4032-5182-b953-f56d00d12b85
```

Note that this breaks a couple of our existing tests, so I need to review those to see if the test is simply wrong or whether I'm missing a case this change breaks. This is obviously a very complex area of the code and unfortunately the test coverage isn't ideal either. The design here where the result _starts_ in a "done" state smells somewhat dubious to me in general. I'll need to run through all the existing tests and make sure we have appropriate coverage before I feel comfortable calling this one fixed, but I think we're on the right path here.

**Comment by tgross** [comment]
I'm working a draft PR in https://github.com/hashicorp/nomad/pull/14348

**Comment by srisch** [comment]
Awesome thank you so much! Glad you figured it out! I was looking at the logger  when I was investigating this and I noticed the agent/client and other things use the new Intercept Logger, and this seemed to update it to the same pattern - Unsure if you'd like to include it in there or not but thought i'd toss it out there. :smile: 

```
diff --git a/nomad/drainer/drainer.go b/nomad/drainer/drainer.go
index f610a0bce..2b7aa70dc 100644
--- a/nomad/drainer/drainer.go
+++ b/nomad/drainer/drainer.go
@@ -5,6 +5,7 @@ import (
        "sync"
        "time"
 
+       "github.com/hashicorp/go-hclog"
        log "github.com/hashicorp/go-hclog"
 
        "github.com/hashicorp/nomad/helper/pointer"
@@ -110,7 +111,7 @@ type allocMigrateBatcher struct {
 
 // NodeDrainerConfig is used to configure a new node drainer.
 type NodeDrainerConfig struct {
-       Logger               log.Logger
+       Logger               hclog.Logger
        Raft                 RaftApplier
        JobFactory           DrainingJobWatcherFactory
        NodeFactory          DrainingNodeWatcherFactory
@@ -129,7 +130,7 @@ type NodeDrainerConfig struct {
 // nodes.
 type NodeDrainer struct {
        enabled bool
-       logger  log.Logger
+       logger  hclog.Logger

**Comment by tgross** [comment]
I did some code spelunking and I think I figured out why node drain uses the `alloc.TerminalStatus()` which includes both server and client status. The node drain code in question https://github.com/hashicorp/nomad/commit/8217ebf11e2b7585bef61b142550fa9bd3dfcb0e was written a month before there ever was a separate client status method https://github.com/hashicorp/nomad/commit/7fa7655ebebb84a1b7fa47de6b4c376d9f08159e !

**Comment by tgross** [comment]
Doing some more research on this while waiting for CI to run I remembered we have https://github.com/hashicorp/nomad/issues/9902 open which is exactly this issue. The behavior was never particularly well-defined, which is probably why this is a little confusing; without a kill timeout a drain being marked complete "too early" isn't a noticeable problem for anyone.

**Comment by srisch** [comment]
Very interesting - Indeed the only thing that indicated to me something wasn't right was the use of the kill timeout with the nomad-autoscaler.  The autoscaler detected the job as complete and it shut down my AWS node while my job was still stop/running.  I haven't taken a peek at the autoscaler code yet to see if that's desired or not, but i'm guessing it was just reading back from the API that the drain was complete.

**Comment by tgross** [comment]
Yeah almost certainly. The autoscaler _should_ be able to rely on the drain complete message being correct. It's just wrong in the design. I think the remaining piece of the puzzle in #14348 is to track "has migrated" and "has been asked to migrate" separately for purposes of calculating doneness. Full disclosure, I'm probably not going to get a chance to wrap that up this week because of some other interrupts, but I'll do my best to get back to it as soon as possible.

**Comment by srisch** [comment]
No worries thanks again for all your help on this and I appreciate the heads up!

**Comment by srisch** [comment]
@tgross Just wanted to check and see if this working on any current builds or branches?    Thanks!

**Comment by pop** [comment]
I am also seeing similar (but possibly different?) issues.

* Triggering a node drain in the UI it returns immediately saying the drain was complete even when there are clearly still allocs running. 

* The Nomad CLI just hangs here:
```
$ nomad node drain -enable 636d5eaa-ce3c-d654-f7dc-77a77d7ba608
2022-12-02T10:45:26-08:00: Ctrl-C to stop monitoring: will not cancel the node drain
2022-12-02T10:45:26-08:00: Node "636d5eaa-ce3c-d654-f7dc-77a77d7ba608" drain strategy set
2022-12-02T10:45:26-08:00: Drain complete for node 636d5eaa-ce3c-d654-f7dc-77a77d7ba608
```

I am running Nomad 1.4.3 with the majority of clients running 1.4.0.

**Comment by tgross** [comment]
This issue is fixed by https://github.com/hashicorp/nomad/pull/14348, which will ship in the next regular patch release of Nomad.
