### ISSUE TITLE
Panic when `attribute` is unset inside constraint stanza.

### ISSUE THREAD

**Issue by chuckyz** [hashicorp/nomad#14488]
### Nomad version
v1.2.3

### Operating system and Environment details
macohs big sir

### Issue
Big ol' panic when trying to do `nomad job plan` on a job with a constraint stanza with an empty `attribute` value.

### Reproduction steps
add
```
constraint {
  attribute =
  value = "foo"
  operator = "="
}
```
to any job

#### Expected Result
Something like `Error: no attribute set in constraint stanza (line number)`

#### Actual Result
```
panic: value is unknown

goroutine 1 [running]:
github.com/zclconf/go-cty/cty.Value.AsString({{{0x1045bc828, 0x1400011cbb9}}, {0x10405f7c0, 0x105763940}})
	github.com/zclconf/go-cty@v1.8.0/cty/value_ops.go:1257 +0x150
github.com/hashicorp/nomad/jobspec2.decodeConstraint.func1({0x1039a4f3d, 0x9})
	github.com/hashicorp/nomad/jobspec2/hcl_conversions.go:199 +0xc0
github.com/hashicorp/nomad/jobspec2.decodeConstraint({0x1045bb750, 0x140002f2150}, 0x14000389840, {0x103ee83a0, 0x1400083f440})
	github.com/hashicorp/nomad/jobspec2/hcl_conversions.go:202 +0x100
github.com/hashicorp/hcl/v2/gohcl.(*Decoder).decodeBodyToStruct(0x140004b8c50, {0x1045bb750, 0x140002f2150}, 0x14000389840, {0x10429c120, 0x1400083f440, 0x199})
	github.com/hashicorp/hcl/v2@v2.9.2-0.20210407182552-eb14f8319bdc/gohcl/decode.go:102 +0xa80
github.com/hashicorp/hcl/v2/gohcl.(*Decoder).decodeBodyToValue(0x140004b8c50, {0x1045bb750, 0x140002f2150}, 0x14000389840, {0x10429c120, 0x1400083f440, 0x199})
	github.com/hashicorp/hcl/v2@v2.9.2-0.20210407182552-eb14f8319bdc/gohcl/decode.go:92 +0xa4
github.com/hashicorp/hcl/v2/gohcl.(*Decoder).decodeBlockToValue(0x140004b8c50, 0x1400029dee0, 0x14000389840, {0x10429c120, 0x1400083f440, 0x199})
	github.com/hashicorp/hcl/v2@v2.9.2-0.20210407182552-eb14f8319bdc/gohcl/decode.go:365 +0x348
github.com/hashicorp/hcl/v2/gohcl.(*Decoder).decodeBodyToStruct(0x140004b8c50, {0x1045bb750, 0x140007f7920}, 0x14000389840, {0x1044e3e60, 0x14000622d00, 0x199})
	github.com/hashicorp/hcl/v2@v2.9.2-0.20210407182552-eb14f8319bdc/gohcl/decode.go:255 +0x284c
github.com/hashicorp/hcl/v2/gohcl.(*Decoder).decodeBodyToValue(0x140004b8c50, {0x1045bb750, 0x140007f7920}, 0x14000389840, {0x1044e3e60, 0x14000622d00, 0x199})
	github.com/hashicorp/hcl/v2@v2.9.2-0.20210407182552-eb14f8319bdc/gohcl/decode.go:92 +0xa4
github.com/hashicorp/hcl/v2/gohcl.(*Decoder).DecodeBody(0x140004b8c50, {0x1045bb750, 0x140007f7920}, 0x14000389840, {0x1043f3320, 0x14000622d00})
	github.com/hashicorp/hcl/v2@v2.9.2-0.20210407182552-eb14f8319bdc/gohcl/decode.go:85 +0x134
github.com/hashicorp/nomad/jobspec2.(*jobConfig).decodeJob(0x140007c4070, 0x14000834f60, 0x14000389840)
	github.com/hashicorp/nomad/jobspec2/types.config.go:283 +0x608
github.com/hashicorp/nomad/jobspec2.(*jobConfig).decodeBody(0x140007c4070, {0x1045bb9b8, 0x14000807c30})
	github.com/hashicorp/nomad/jobspec2/types.config.go:83 +0x5a0
github.com/hashicorp/nomad/jobspec2.decode(0x140007c4070)
	github.com/hashicorp/nomad/jobspec2/parse.go:99 +0xb8
github.com/hashicorp/nomad/jobspec2.ParseWithConfig(0x14000806210)
	github.com/hashicorp/nomad/jobspec2/parse.go:44 +0x118
github.com/hashicorp/nomad/command.(*JobGetter).ApiJobWithArgs(0x14000413ec0, {0x16da87487, 0x19}, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x1)
	github.com/hashicorp/nomad/command/helpers.go:455 +0x664
github.com/hashicorp/nomad/command.(*JobPlanCommand).Run(0x14000413e10, {0x1400003c0b0, 0x1, 0x1})
	github.com/hashicorp/nomad/command/job_plan.go:152 +0x3c4
github.com/mitchellh/cli.(*CLI).Run(0x1400046be00)
	github.com/mitchellh/cli@v1.1.0/cli.go:260 +0x5c4
main.RunCustom({0x1400003c090, 0x3, 0x3})
	github.com/hashicorp/nomad/main.go:116 +0x3a4
main.Run(...)
	github.com/hashicorp/nomad/main.go:86
main.main()
	github.com/hashicorp/nomad/main.go:82 +0x60
```

### Job file (if appropriate)

```
job "example" {
  datacenters = ["dc1"]

  constraint {
    attribute =
    value = "foo"
    operator = "="
  }

  group "cache" {
    network {
      port "db" {
        to = 6379
      }
    }

    task "redis" {
      driver = "docker"

      config {
        image = "redis:3.2"

        ports = ["db"]
      }

      resources {
        cpu    = 500
        memory = 256
      }
    }
  }
}
```

**Comment by jrasell** [comment]
Hi @chuckyz and thanks for the report. I was able to reproduce this using `v1.2.3`, however, can confirm this bug has been fixed within `v1.2.6` a later. I am not sure why the changelog entry is not correctly populated and will look into this, however,  https://github.com/hashicorp/nomad/pull/13036 contained the fix.
