### ISSUE TITLE
Nomad server node does not start after power shutwdown 

### ISSUE THREAD

**Issue by suikast42** [hashicorp/nomad#14624]
After hard power shutdown the nomad server do not come up anymore. 
The client node is running. 

### Nomad version
Output from `nomad version`
Nomad v1.4.0-beta.1 (d17021a366178a11b79353f13735389629102d6a)

### Operating system and Environment details
Ubuntu 22.04
### Issue

Nomad server node does not start after power shutwdown 

### Nomad Server logs (if appropriate)
WARNING: keyring exists but -encrypt given, using keyring
==> WARNING: Bootstrap mode enabled! Potentially unsafe operation.
==> Loaded configuration from /etc/nomad.d/server.hcl
==> Starting Nomad agent...
==> Nomad agent configuration:

       Advertise Addrs: HTTP: 192.168.68.148:4646; RPC: 192.168.68.148:4647; Serf: 192.168.68.148:4648
            Bind Addrs: HTTP: [0.0.0.0:4646]; RPC: 0.0.0.0:4647; Serf: 0.0.0.0:4648
                Client: false
             Log Level: DEBUG
                Region: global (DC: nomadder1)
                Server: true
               Version: 1.4.0-beta.1

==> Nomad agent started! Log data will stream in below:

> 
    2022-09-20T06:30:44.291Z [WARN]  agent.plugin_loader: skipping external plugins since plugin_dir doesn't exist: plugin_dir=/opt/services/core/nomad/data/plugins
    2022-09-20T06:30:44.291Z [DEBUG] agent.plugin_loader.docker: using client connection initialized from environment: plugin_dir=/opt/services/core/nomad/data/plugins
    2022-09-20T06:30:44.291Z [DEBUG] agent.plugin_loader.docker: using client connection initialized from environment: plugin_dir=/opt/services/core/nomad/data/plugins
    2022-09-20T06:30:44.291Z [INFO]  agent: detected plugin: name=docker type=driver plugin_version=0.1.0
    2022-09-20T06:30:44.291Z [INFO]  agent: detected plugin: name=raw_exec type=driver plugin_version=0.1.0
    2022-09-20T06:30:44.291Z [INFO]  agent: detected plugin: name=exec type=driver plugin_version=0.1.0
    2022-09-20T06:30:44.291Z [INFO]  agent: detected plugin: name=qemu type=driver plugin_version=0.1.0
    2022-09-20T06:30:44.291Z [INFO]  agent: detected plugin: name=java type=driver plugin_version=0.1.0
    2022-09-20T06:30:44.296Z [INFO]  nomad: setting up raft bolt store: no_freelist_sync=false
    2022-09-20T06:30:44.303Z [INFO]  nomad.raft: initial configuration: index=1 servers="[{Suffrage:Voter ID:0542a6f6-5cb5-59d4-1d33-76ce2b14870c Address:192.168.68.148:4647}]"
    2022-09-20T06:30:44.304Z [INFO]  nomad.raft: entering follower state: follower="Node at 192.168.68.148:4647 [Follower]" leader-address= leader-id=
    2022-09-20T06:30:44.304Z [INFO]  nomad: serf: EventMemberJoin: master-01.global 192.168.68.148
    2022-09-20T06:30:44.304Z [INFO]  nomad: starting scheduling worker(s): num_workers=4 schedulers=["service", "batch", "system", "sysbatch", "_core"]
    2022-09-20T06:30:44.304Z [DEBUG] nomad: started scheduling worker: id=90a05390-fbeb-893b-428d-2c8e624dc19c index=1 of=4
    2022-09-20T06:30:44.304Z [DEBUG] nomad: started scheduling worker: id=5a787683-125d-a71f-6517-f0f768ed6794 index=2 of=4
    2022-09-20T06:30:44.304Z [DEBUG] nomad: started scheduling worker: id=d016281f-fe72-1894-697f-9b9a5fb82e5a index=3 of=4
    2022-09-20T06:30:44.304Z [DEBUG] nomad: started scheduling worker: id=3122c0d5-8d91-320d-fcd0-03ba5a751bcd index=4 of=4
    2022-09-20T06:30:44.304Z [INFO]  nomad: started scheduling worker(s): num_workers=4 schedulers=["service", "batch", "system", "sysbatch", "_core"]
    2022-09-20T06:30:44.304Z [WARN]  agent: not registering Nomad HTTPS Health Check because verify_https_client enabled
    2022-09-20T06:30:44.307Z [DEBUG] worker: running: worker_id=90a05390-fbeb-893b-428d-2c8e624dc19c
    2022-09-20T06:30:44.307Z [WARN]  nomad: serf: Failed to re-join any previously known node
    2022-09-20T06:30:44.307Z [DEBUG] worker: running: worker_id=5a787683-125d-a71f-6517-f0f768ed6794
    2022-09-20T06:30:44.307Z [DEBUG] worker: running: worker_id=d016281f-fe72-1894-697f-9b9a5fb82e5a
    2022-09-20T06:30:44.307Z [DEBUG] worker: running: worker_id=3122c0d5-8d91-320d-fcd0-03ba5a751bcd
    2022-09-20T06:30:44.307Z [DEBUG] nomad.keyring.replicator: starting encryption key replication
    2022-09-20T06:30:44.307Z [DEBUG] http: UI is enabled
    2022-09-20T06:30:44.307Z [INFO]  nomad: adding server: server="master-01.global (Addr: 192.168.68.148:4647) (DC: nomadder1)"
    2022-09-20T06:30:44.326Z [DEBUG] consul.sync: sync complete: registered_services=3 deregistered_services=0 registered_checks=0 deregistered_checks=0
    2022-09-20T06:30:45.790Z [WARN]  nomad.raft: heartbeat timeout reached, starting election: last-leader-addr= last-leader-id=
    2022-09-20T06:30:45.790Z [INFO]  nomad.raft: entering candidate state: node="Node at 192.168.68.148:4647 [Candidate]" term=112
    2022-09-20T06:30:45.792Z [DEBUG] nomad.raft: votes: needed=1
    2022-09-20T06:30:45.792Z [DEBUG] nomad.raft: vote granted: from=0542a6f6-5cb5-59d4-1d33-76ce2b14870c term=112 tally=1
    2022-09-20T06:30:45.792Z [INFO]  nomad.raft: election won: tally=1
    2022-09-20T06:30:45.792Z [INFO]  nomad.raft: entering leader state: leader="Node at 192.168.68.148:4647 [Leader]"
    2022-09-20T06:30:45.792Z [INFO]  nomad: cluster leadership acquired
    2022-09-20T06:30:45.793Z [DEBUG] nomad: shutting down leader looppanic: pgid (339) above high water mark (339)

goroutine 114 [running]:
go.etcd.io/bbolt.(*node).spill(0xc0005a4460)
        go.etcd.io/bbolt@v1.3.6/node.go:371 +0x559
go.etcd.io/bbolt.(*node).spill(0xc0005a43f0)
        go.etcd.io/bbolt@v1.3.6/node.go:346 +0xa9
go.etcd.io/bbolt.(*Bucket).spill(0xc000c52e40)
        go.etcd.io/bbolt@v1.3.6/bucket.go:570 +0x33f
go.etcd.io/bbolt.(*Bucket).spill(0xc000c2f278)
        go.etcd.io/bbolt@v1.3.6/bucket.go:537 +0x107
go.etcd.io/bbolt.(*Tx).Commit(0xc000c2f260)
        go.etcd.io/bbolt@v1.3.6/tx.go:160 +0xe7
github.com/hashicorp/raft-boltdb/v2.(*BoltStore).StoreLogs(0xc000b5a2a0, {0xc000127240, 0x1, 0x1ff?})
        github.com/hashicorp/raft-boltdb/v2@v2.2.0/bolt_store.go:207 +0x43a
github.com/hashicorp/raft.(*LogCache).StoreLogs(0xc000b78c80, {0xc000127240?, 0x1, 0x0?})
        github.com/hashicorp/raft@v1.3.9/log_cache.go:54 +0x3c
github.com/hashicorp/raft.(*Raft).dispatchLogs(0xc000208b00, {0xc000c89d90, 0x1, 0x1?})
        github.com/hashicorp/raft@v1.3.9/raft.go:1191 +0x3dc
github.com/hashicorp/raft.(*Raft).runLeader(0xc000208b00)
        github.com/hashicorp/raft@v1.3.9/raft.go:516 +0x427
github.com/hashicorp/raft.(*Raft).run(0xc000208b00)
        github.com/hashicorp/raft@v1.3.9/raft.go:148 +0x4f
github.com/hashicorp/raft.(*raftState).goFunc.func1()
        github.com/hashicorp/raft@v1.3.9/state.go:146 +0x62
created by github.com/hashicorp/raft.(*raftState).goFunc
        github.com/hashicorp/raft@v1.3.9/state.go:144 +0x8d

**Comment by lgfa29** [comment]
Hi @suikast42 👋 

Thanks for reporting the issue. This seems like a data corruption issue in BBolt due to the power shutdown. A similar problem is described here: https://github.com/etcd-io/etcd/issues/10466.

Normally the recovery procedure would be to delete the corrupted server `data_dir` and have it join the cluster again, where it would replicated the Raft logs from the other servers. But it seems like you are running a single server topology? If that's the case this process would not work for you. That's why for production environments we recommend at least 3 servers.

We haven't seen any reports of this before, so I don't have a lot of help to offer. Looking at this [comment](https://github.com/lightningnetwork/lnd/issues/6503#issuecomment-1129483480) you may be able to use the `bbolt` CLI and run `bbolt check` to validate the the database got corrupted and `bbolt compact` to try to remove corrupted values.

In the case of Nomad, the database file is located at `<YOUR data_dir>/server/raft/raft.db`. Make sure you make a copy of this file before attempting any actions.

And please let us know how this procedure go and if it helps you fix the problem. If it doesn't, it may be good to open an issue directly in the https://github.com/etcd-io/bbolt repo.

**Comment by suikast42** [comment]
Hi @lgfa29 

thanks for the clarification. You ara right. The problem occurs on a single sever worker setup on my local machine. 
I will consider that the three server setup is required for situations like this.

> And please let us know how this procedure go and if it helps you fix the problem.

For reproduce this issue I must do hard powershutdown on my window host machine. I am a little bit affraid of that. But maybe at the weekend.  Maybe it needs a revocer of windows itself :-D

**Comment by lgfa29** [comment]
> For reproduce this issue I must do hard powershutdown on my window host machine. I am a little bit affraid of that.

Ah yes, I certainly wouldn't want you to crash any more nodes 😄 

What I meant was that, if you still have the corrupt file available, to test the `bbolt` CLI commands to see if it's able to restore the file.

**Comment by suikast42** [comment]
> Ah yes, I certainly wouldn't want you to crash any more nodes 😄

I have some problems with my business notbook. If I plug off my docking station the whole system freeze. It's easy to reproduce 😄

**Comment by lgfa29** [comment]
Cool, so if this happens again, try those `bbolt` commands and see if they fix the problem 🙂 

I'm going to go ahead and close this for now, since there's not much Nomad can do about it. If your experience with the `bbolt` CLI goes well we can document the process to help others.
