### ISSUE TITLE
panic in volume watcher

### ISSUE THREAD

**Issue by tgross** [hashicorp/nomad#15095]
Reported through our support org:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x110 pc=0x1d647f3]

goroutine 22850374 [running]:
github.com/hashicorp/nomad/nomad/volumewatcher.(*volumeWatcher).volumeReapImpl(0x0?, 0x0)
    github.com/hashicorp/nomad/nomad/volumewatcher/volume_watcher.go:208 +0x33
github.com/hashicorp/nomad/nomad/volumewatcher.(*volumeWatcher).volumeReap(0xc002c84f00, 0xc0020ea1a0?)
    github.com/hashicorp/nomad/nomad/volumewatcher/volume_watcher.go:193 +0x58
github.com/hashicorp/nomad/nomad/volumewatcher.(*volumeWatcher).watch(0xc002c84f00)
    github.com/hashicorp/nomad/nomad/volumewatcher/volume_watcher.go:121 +0x5f
created by github.com/hashicorp/nomad/nomad/volumewatcher.(*volumeWatcher).Start
    github.com/hashicorp/nomad/nomad/volumewatcher/volume_watcher.go:89 +0x125
```

This is bubbling up from [`volume_watcher.go#L208`](https://github.com/hashicorp/nomad/blob/v1.4.2/nomad/volumewatcher/volume_watcher.go#L208), which suggests the volume is nil here. A quick look at the code shows we're missing a nil-check at [`volume_watcher.go#L120-L121`](https://github.com/hashicorp/nomad/blob/v1.4.2/nomad/volumewatcher/volume_watcher.go#L120-L121)

**Comment by tgross** [comment]
#15101 has been merged and will ship in the next release of Nomad, with backports to the 1.3.x and 1.2.x series.
