### ISSUE TITLE
Job Endpoint concurrent map writes

### ISSUE THREAD

**Issue by shoenig** [hashicorp/nomad#15474]
Had a CI fail due to (almost certainly) unrelated changes; concurrent map writes on the Job endpoint

@pkazmierczak 
@jrasell 

```
FAIL nomad
=== RUN   TestACLEndpoint_GetAuthMethods
=== PAUSE TestACLEndpoint_GetAuthMethods
FAIL nomad.TestACLEndpoint_GetAuthMethods (-1.00s)
=== RUN   TestClientEndpoint_UpdateAlloc_Evals_ByTrigger
=== PAUSE TestClientEndpoint_UpdateAlloc_Evals_ByTrigger
FAIL nomad.TestClientEndpoint_UpdateAlloc_Evals_ByTrigger (-1.00s)
=== RUN   TestPlanEndpoint_ApplyConcurrent
=== PAUSE TestPlanEndpoint_ApplyConcurrent
FAIL nomad.TestPlanEndpoint_ApplyConcurrent (-1.00s)
=== RUN   TestRPC_streamingRpcConn_goodMethod_TLS
fatal error: concurrent map writes

goroutine 91524 [running]:
github.com/hashicorp/nomad/nomad/structs.(*StreamingRpcRegistry).Register(...)
	/home/runner/work/nomad/nomad/nomad/structs/streaming_rpc.go:42
github.com/hashicorp/nomad/nomad.(*ClientAllocations).register(...)
	/home/runner/work/nomad/nomad/nomad/client_alloc_endpoint.go:32
github.com/hashicorp/nomad/nomad.(*Server).setupRpcServer(0xc0046aedc0, 0xc005f65880?, 0xc0050bb220)
	/home/runner/work/nomad/nomad/nomad/server.go:1206 +0x16b
github.com/hashicorp/nomad/nomad.(*rpcHandler).handleMultiplexV2(0xc005bfd280, {0x29e92a0?, 0xc0066e5440}, {0x29f51f0?, 0xc005f65880}, 0xc0050bb220)
	/home/runner/work/nomad/nomad/nomad/rpc.go:494 +0x225
github.com/hashicorp/nomad/nomad.(*rpcHandler).handleConn(0xc005bfd280, {0x29e92a0, 0xc0066e5440}, {0x29f51f0, 0xc005f65880?}, 0xc0050bb220)
	/home/runner/work/nomad/nomad/nomad/rpc.go:352 +0xe45
github.com/hashicorp/nomad/nomad.(*rpcHandler).handleConn(0xc005bfd280, {0x29e92a0, 0xc0066e5440}, {0x29f74a8, 0xc005d9b148?}, 0xc0050bb220)
	/home/runner/work/nomad/nomad/nomad/rpc.go:332 +0x9bf
created by github.com/hashicorp/nomad/nomad.(*rpcHandler).listen
	/home/runner/work/nomad/nomad/nomad/rpc.go:183 +0x452
```

**Comment by jrasell** [comment]
This seems related to https://github.com/hashicorp/nomad/pull/15451

**Comment by tgross** [comment]
I suspect @jrasell is right here. Originally the streaming RPCs were registered once at startup, but now they'll get registered for each RPC call. That's unnecessary, for starters, but also risks hitting this concurrent map update.
