### ISSUE TITLE
nomad process dies with `panic: counter cannot decrease in value`

### ISSUE THREAD

**Issue by rbastiaans-tc** [hashicorp/nomad#15861]
### Nomad version
```
Nomad v1.3.1 (2b054e38e91af964d1235faa98c286ca3f527e56)
```
### Operating system and Environment details

```
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

### Issue

The Nomad agent process died with a message: `panic: counter cannot decrease in value`

See full panic output below.

### Reproduction steps

Unknown

#### Expected Result

Nomad stay running

#### Actual Result

Nomad process exits

### Nomad Client logs (if appropriate)

```
Sun 2023-01-22 16:57:52 UTC nomadclient013 nomad[3403]: ==> Newer Nomad version available: 1.4.3 (currently running: 1.3.1)
Sun 2023-01-22 16:58:41 UTC nomadclient013 nomad[3403]: panic: counter cannot decrease in value
Sun 2023-01-22 16:58:41 UTC nomadclient013 nomad[3403]: goroutine 7598137 [running]:
Sun 2023-01-22 16:58:41 UTC nomadclient013 nomad[3403]: github.com/prometheus/client_golang/prometheus.(*counter).Add(...)
Sun 2023-01-22 16:58:41 UTC nomadclient013 nomad[3403]:         github.com/prometheus/client_golang@v1.12.0/prometheus/counter.go:109
Sun 2023-01-22 16:58:41 UTC nomadclient013 nomad[3403]: github.com/prometheus/client_golang/prometheus.(*goCollector).Collect(0xc000280080, 0xc00235bf60)
Sun 2023-01-22 16:58:41 UTC nomadclient013 nomad[3403]:         github.com/prometheus/client_golang@v1.12.0/prometheus/go_collector_go117.go:147 +0x5ec
Sun 2023-01-22 16:58:41 UTC nomadclient013 nomad[3403]: github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
Sun 2023-01-22 16:58:41 UTC nomadclient013 nomad[3403]:         github.com/prometheus/client_golang@v1.12.0/prometheus/registry.go:446 +0x102
Sun 2023-01-22 16:58:41 UTC nomadclient013 nomad[3403]: created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
Sun 2023-01-22 16:58:41 UTC nomadclient013 nomad[3403]:         github.com/prometheus/client_golang@v1.12.0/prometheus/registry.go:457 +0x4e8
Sun 2023-01-22 16:58:41 UTC nomadclient013 systemd[1]: nomad.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Sun 2023-01-22 16:58:41 UTC nomadclient013 systemd[1]: nomad.service: Failed with result 'exit-code'.
Sun 2023-01-22 16:58:43 UTC nomadclient013 systemd[1]: nomad.service: Service RestartSec=2s expired, scheduling restart.
Sun 2023-01-22 16:58:43 UTC nomadclient013 systemd[1]: nomad.service: Scheduled restart job, restart counter is at 1.
```

**Comment by lgfa29** [comment]
Hi @rbastiaans-tc 👋 

Thanks for the report. Unfortunately we will need more information in order to understand what's going wrong. 

Looking at the code this panic is raised by the [Prometheus client library](https://github.com/prometheus/client_golang/blob/v1.12.0/prometheus/counter.go#L108-L110) when the counter attempts to add a negative value.

This library is used by [`go-metrics` in the `IncrCounter` and `IncrCounterWithLabels` methods](https://github.com/hashicorp/go-metrics/blob/v0.3.10/prometheus/prometheus.go#L368-L393), but all [uses of these methods in Nomad](https://cs.github.com/?scopeName=Nomad&scope=repo%3Ahashicorp%2Fnomad&q=IncrCounter) pass either `1` or the `len(...)` of something, which is always positive.

So in order to understand what's going on with your cluster I built custom binaries that output more information when the panic occurs. You can find them at the bottom of this page: https://github.com/hashicorp/nomad/actions/runs/4000378647

One very important thing is that **these binaries are for test only and should not be run in production**, so if you could, please copy the `data_dir` of the agent presenting this problem somewhere else and run the custom binary pointing to the new directory.

The changes included in these binaries can be viewed here:
- https://github.com/hashicorp/go-metrics/compare/v0.3.10...wip-add-negative
- https://github.com/hashicorp/nomad/compare/v1.3.1...tmp-metrics-panic

Another thing that could be relevant, what CPU architecture are you using?

**Comment by lgfa29** [comment]
Ah no worries, I thought this something that was always happening when your agent started so it could be tested quickly.

> Besides the root cause of the panic, I would imagine the Nomad process should never crash because of a issue with just telemetry or monitoring metrics only. Especially in production environments.
>
> Wouldn't catching that panic be a relatively easy fix?

I definitely agree with this, but it's not so simple to fix this from the Nomad side. The telemetry library we use is called in several places and, as far as I can tell, we always send values that are supposed to be positive.

I will have to discuss with the rest of the team how to best handle this. It would probably require changes to the `go-metrics` module.

**Comment by rbastiaans-tc** [comment]
> Ah no worries, I thought this something that was always happening when your agent started so it could be tested quickly.
> 

Ah perhaps that wasn't clear from my report. It happened after running Nomad for a long time, on only 1 machine in the cluster so far.

Thanks so much for looking into this @lgfa29

**Comment by lgfa29** [comment]
Got it, thanks! Yeah, we've been using this library for a while and haven't seen any reports about this before. I also haven't heard from other teams that also use it. So it seems like it was a unfortunate, but very rare, situation.

**Comment by tgross** [comment]
It occurs to me that any stack trace isn't going to be that useful b/c it's getting messages over a channel, so this is just the prom goroutine. I wonder if we're starting from the position here. If we know we aren't trying to decrement a counter, maybe something else is? The prometheus client gets metrics from the go runtime. I don't see anything obvious in [`go_collector.go`](https://github.com/prometheus/client_golang/blob/main/prometheus/go_collector.go) or in the golang issues for [MemStats](https://github.com/golang/go/issues?q=is%3Aissue+MemStats+is%3Aopen), but it'd be worth some investigation here I think.

**Comment by lgfa29** [comment]
Ah that's right, we emit metrics for the runtime environment, and probably other things I'm not remembering right now 😅 

I think the best option we have is to move forward with https://github.com/hashicorp/go-metrics/pull/146, that would prevent crashes and also give us more information about which metric is behaving unexpectedly.

**Comment by rbastiaans-tc** [comment]
@tgross @lgfa29 Can we please get that metrics PR merged and that into a Nomad release?

This is still happening for me on occasion and in production environments it's not really great, in combination with that CSI volume bug. It means that whenever Nomad dies of this panic, also all our jobs running there using CSI volumes get killed and rescheduled.

So if we could get a fix at least for this panic it will already help us, regardless of the CSI volume bug which seems more difficult to tackle. This metrics PR seems like an easier win.

**Comment by tgross** [comment]
@lhossack has reported seeing the logging we added to detect this case in https://github.com/hashicorp/nomad/issues/18804, so that's a good start on next steps for this issue.

**Comment by tgross** [comment]
Fix in https://github.com/hashicorp/nomad/pull/18835. See my comment here https://github.com/hashicorp/nomad/issues/18804#issuecomment-1775331491 for a detailed breakdown of the problem.

**Comment by chenk008** [comment]
I think it is related to https://github.com/prometheus/client_golang/pull/969

**Comment by lgfa29** [comment]
Hi @chenk008 👋 

Have you encountered this issue after https://github.com/hashicorp/nomad/pull/18835 was released in Nomad 1.6.3?

**Comment by lgfa29** [comment]
No worries @chenk008, I mostly trying to understand the exact issue you've experience.

Would you be able to open a new issue and post the exact error from log output and Nomad version you're using? 

Thanks!
