### ISSUE TITLE
nomad client unknown panic

### ISSUE THREAD

**Issue by BSick7** [hashicorp/nomad#1722]
If filing a bug please include the following:

### Nomad version
Output from `nomad version`
v0.4.1 (client and server)

### Operating system and Environment details
CoreOS

### Issue
I noticed a nomad client was down and looked in the logs and found a panic.

### Reproduction steps

I'm not sure how it happened exactly.

### Nomad Client logs

```
Sep 20 14:26:08 worker-blue-18 nomad[1861]: panic: runtime error: invalid memory address or nil pointer dereference
Sep 20 14:26:08 worker-blue-18 nomad[1861]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x553635]
Sep 20 14:26:08 worker-blue-18 nomad[1861]: goroutine 803889 [running]:
Sep 20 14:26:08 worker-blue-18 nomad[1861]: panic(0xeca8e0, 0xc420012040)
Sep 20 14:26:08 worker-blue-18 nomad[1861]:         /opt/go/src/runtime/panic.go:500 +0x1a1
Sep 20 14:26:08 worker-blue-18 nomad[1861]: github.com/hashicorp/nomad/client.(*TaskRunner).collectResourceUsageStats(0xc426aac160, 0xc420fafec0)
Sep 20 14:26:08 worker-blue-18 nomad[1861]:         /opt/gopath/src/github.com/hashicorp/nomad/client/task_runner.go:494 +0x105
Sep 20 14:26:08 worker-blue-18 nomad[1861]: created by github.com/hashicorp/nomad/client.(*TaskRunner).run
Sep 20 14:26:08 worker-blue-18 nomad[1861]:         /opt/gopath/src/github.com/hashicorp/nomad/client/task_runner.go:354 +0x1764
Sep 20 14:26:08 worker-blue-18 systemd[1]: nomad.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Sep 20 14:26:08 worker-blue-18 systemd[1]: nomad.service: Unit entered failed state.
Sep 20 14:26:08 worker-blue-18 systemd[1]: nomad.service: Failed with result 'exit-code'.
```

**Comment by dadgar** [comment]
Thanks for reporting! Will take a look soon!

**Comment by BSick7** [comment]
You guys rock!
