### ISSUE TITLE
Runtime error if -config path specified is empty

### ISSUE THREAD

**Issue by cleung2010** [hashicorp/nomad#182]
As the title says, nomad exits with a runtime error if the `-config` path specified is empty:
```
vagrant@nomad:~$ ls /etc/nomad.d/
vagrant@nomad:~$ sudo nomad agent -config /etc/nomad.d
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x8 pc=0x470f5f]

goroutine 1 [running]:
github.com/hashicorp/nomad/command/agent.(*Config).Merge(0xc208001b00, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/nomad/command/agent/config.go:251 +0x6f
github.com/hashicorp/nomad/command/agent.(*Command).readConfig(0xc208044be0, 0xc20800a020)
	/opt/gopath/src/github.com/hashicorp/nomad/command/agent/command.go:109 +0xf8c
github.com/hashicorp/nomad/command/agent.(*Command).Run(0xc208044be0, 0xc20800a020, 0x2, 0x2, 0x0)
	/opt/gopath/src/github.com/hashicorp/nomad/command/agent/command.go:278 +0x18e
github.com/mitchellh/cli.(*CLI).Run(0xc208046630, 0xc2080d65e0, 0x0, 0x0)
	/opt/gopath/src/github.com/mitchellh/cli/cli.go:112 +0x5be
main.RunCustom(0xc20800a010, 0x3, 0x3, 0xc20803d830, 0x4)
	/opt/gopath/src/github.com/hashicorp/nomad/main.go:47 +0x49e
main.Run(0xc20800a010, 0x3, 0x3, 0xcda5f8)
	/opt/gopath/src/github.com/hashicorp/nomad/main.go:15 +0x53
main.main()
	/opt/gopath/src/github.com/hashicorp/nomad/main.go:11 +0x6d

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1
```

Edit: This also happens if the directory is non-empty, but does not have any HCL or JSON specific files:
```
vagrant@nomad:~$ ls /foo
bar
vagrant@nomad:~$ sudo nomad agent -config /foo
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x8 pc=0x470f5f]

goroutine 1 [running]:
github.com/hashicorp/nomad/command/agent.(*Config).Merge(0xc2080019e0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/nomad/command/agent/config.go:251 +0x6f
github.com/hashicorp/nomad/command/agent.(*Command).readConfig(0xc208045040, 0xc20800a020)
	/opt/gopath/src/github.com/hashicorp/nomad/command/agent/command.go:109 +0xf8c
github.com/hashicorp/nomad/command/agent.(*Command).Run(0xc208045040, 0xc20800a020, 0x2, 0x2, 0x0)
	/opt/gopath/src/github.com/hashicorp/nomad/command/agent/command.go:278 +0x18e
github.com/mitchellh/cli.(*CLI).Run(0xc2080c0160, 0xc20801f380, 0x0, 0x0)
	/opt/gopath/src/github.com/mitchellh/cli/cli.go:112 +0x5be
main.RunCustom(0xc20800a010, 0x3, 0x3, 0xc2080566f0, 0x4)
	/opt/gopath/src/github.com/hashicorp/nomad/main.go:47 +0x49e
main.Run(0xc20800a010, 0x3, 0x3, 0xcda5f8)
	/opt/gopath/src/github.com/hashicorp/nomad/main.go:15 +0x53
main.main()
	/opt/gopath/src/github.com/hashicorp/nomad/main.go:11 +0x6d

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1
```

**Comment by dadgar** [comment]
Fixed in https://github.com/hashicorp/nomad/commit/61f4e638b83e8d1ce749e6a7670f6984b5c2220c
