### ISSUE TITLE
Seg fault running compiled linux/amd64 binary on WSL

### ISSUE THREAD

**Issue by MattJustMatt** [hashicorp/nomad#18347]
### Nomad version
Nomad v1.6.2-dev

### Operating system and Environment details
WSL 2 running Ubuntu on a Intel/Windows host

### Issue
I compiled Nomad on WSL using the make file and instructions from the contributing section. The linux/amd64 binary works fine on a Debian host OS, and basic commands (./nomad -v, etc...) work ok. But when I try to launch a dev server it segmentation faults (looks like during fingerprinting of the system). I have made no code changes in these areas. 

```
matt@Matt12900k:~/nomad/pkg/linux_amd64$ ./nomad agent -dev
==> No configuration files loaded
==> Starting Nomad agent...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1220a95]

goroutine 1 [running]:
github.com/hashicorp/nomad/client/lib/idset.(*Set[...]).Size(...)
        github.com/hashicorp/nomad/client/lib/idset/idset.go:156
github.com/hashicorp/nomad/client/lib/numalib.(*Sysfs).discoverCosts(0x30e65d0, 0x2ad97ec?)
        github.com/hashicorp/nomad/client/lib/numalib/detect_linux.go:69 +0x15
github.com/hashicorp/nomad/client/lib/numalib.(*Sysfs).ScanSystem(0x310bef0?, 0xc000880f50)
        github.com/hashicorp/nomad/client/lib/numalib/detect_linux.go:51 +0x70
github.com/hashicorp/nomad/client/lib/numalib.Scan(...)
        github.com/hashicorp/nomad/client/lib/numalib/detect.go:22
github.com/hashicorp/nomad/drivers/docker.NewDockerDriver({0x310bef0?, 0xc000880f00}, {0xc000b47078?, 0x416392?}, {0x312cfb0?, 0xc000894db0?})
        github.com/hashicorp/nomad/drivers/docker/driver.go:174 +0x214
github.com/hashicorp/nomad/drivers/docker.glob..func1({0x310bef0?, 0xc000880f00?}, {0x312cfb0?, 0xc000894db0?})
        github.com/hashicorp/nomad/drivers/docker/config.go:127 +0x31
github.com/hashicorp/nomad/helper/pluginutils/loader.(*PluginLoader).initInternal(0xc000894e10, 0xc000894bd0, 0x4847e80?)
        github.com/hashicorp/nomad/helper/pluginutils/loader/init.go:99 +0x194
github.com/hashicorp/nomad/helper/pluginutils/loader.(*PluginLoader).init(0xc000894e10, 0xc000b475a0)
        github.com/hashicorp/nomad/helper/pluginutils/loader/init.go:62 +0x13b
github.com/hashicorp/nomad/helper/pluginutils/loader.NewPluginLoader(0xc000b475a0)
        github.com/hashicorp/nomad/helper/pluginutils/loader/loader.go:138 +0x31b
github.com/hashicorp/nomad/command/agent.(*Agent).setupPlugins(0xc00090a120)
        github.com/hashicorp/nomad/command/agent/plugins.go:30 +0x11d
github.com/hashicorp/nomad/command/agent.(*Agent).setupClient(0xc00090a120)
        github.com/hashicorp/nomad/command/agent/agent.go:1061 +0x3d
github.com/hashicorp/nomad/command/agent.NewAgent(0xc000279c00, {0x3133588?, 0xc000784c00}, {0x30ebea0?, 0xc0002809d8}, 0xc000782730)
        github.com/hashicorp/nomad/command/agent/agent.go:151 +0x1e5
github.com/hashicorp/nomad/command/agent.(*Command).setupAgent(0xc000155200, 0xc000279c00, {0x3133588, 0xc000784c00}, {0x30ebea0, 0xc0002809d8}, 0x0?)
        github.com/hashicorp/nomad/command/agent/command.go:570 +0x9e
github.com/hashicorp/nomad/command/agent.(*Command).Run(0xc000155200, {0xc0001187a0, 0x1, 0x1})
        github.com/hashicorp/nomad/command/agent/command.go:776 +0x611
github.com/mitchellh/cli.(*CLI).Run(0xc000130c80)
        github.com/mitchellh/cli@v1.1.5/cli.go:262 +0x5b8
main.Run({0xc000118790, 0x2, 0x2})
        github.com/hashicorp/nomad/main.go:110 +0x227
main.main()
        github.com/hashicorp/nomad/main.go:80 +0x45
```

### Reproduction steps
- Clone Nomad on a WSL 2 instance
- Install deps (go, yarn, gcc)
- make bootstrap
- make prerelease
- make make pkg/linux_amd64/nomad
- run nomad binary with agent -dev

#### Expected Result
Dev server starts

#### Actual Result
Dev server segfaults

**Comment by MattJustMatt** [comment]
I should note-- the release binaries seem to work fine. It's only when compiling locally that I'm getting this error.

**Comment by shoenig** [comment]
@MattJustMatt this code is in the middle of being written for the Nomad 1.7 release. The code path you're segfaulting in is a stub for an actual implementation.
