### ISSUE TITLE
numa: ensure 1.6.x to 1.7 upgrade path works

### ISSUE THREAD

**Issue by shoenig** [hashicorp/nomad#18837]
@Juanadelacuesta tried an upgrade from 1.6.x to main and got this; need to go back and make sure the 1.6.x to 1.7 upgrade path works correctly before the 1.7 beta.

```
2023-10-23T18:02:56.797+0200 [ERROR] worker.batch_sched: processing eval panicked scheduler - please report this as a bug!: eval_id=68012d8c-faab-1057-a491-c40b9be4263f job_id=exam namespace=default worker_id=f203a16e-9560-2db5-7fb2-6e9d2bebb59e eval_id=68012d8c-faab-1057-a491-c40b9be4263f error="runtime error: invalid memory address or nil pointer dereference"
  stack_trace=
  | goroutine 28 [running]:
  | runtime/debug.Stack()
  | \t/opt/homebrew/Cellar/go/1.21.1/libexec/src/runtime/debug/stack.go:24 +0x64
  | github.com/hashicorp/nomad/scheduler.(*GenericScheduler).Process.func1()
  | \t/Users/juanita.delacuestamorales/go/src/github.com/hashicorp/nomad/scheduler/generic_sched.go:153 +0x58
  | panic({0x103499000?, 0x104d6d150?})
  | \t/opt/homebrew/Cellar/go/1.21.1/libexec/src/runtime/panic.go:920 +0x254
  | github.com/hashicorp/nomad/client/lib/numalib.(*Topology).UsableCores(0x0)
  | \t/Users/juanita.delacuestamorales/go/src/github.com/hashicorp/nomad/client/lib/numalib/topology.go:252 +0x38
  | github.com/hashicorp/nomad/nomad/structs.(*NodeResources).Comparable(0x140002079a0)
  | \t/Users/juanita.delacuestamorales/go/src/github.com/hashicorp/nomad/nomad/structs/structs.go:3199 +0x44
  | github.com/hashicorp/nomad/scheduler.(*Preemptor).SetNode(0x14000eacaf0, 0x14001180c00)
  | \t/Users/juanita.delacuestamorales/go/src/github.com/hashicorp/nomad/scheduler/preemption.go:139 +0x30
  | github.com/hashicorp/nomad/scheduler.(*BinPackIterator).Next(0x140004780e0)
  | \t/Users/juanita.delacuestamorales/go/src/github.com/hashicorp/nomad/scheduler/rank.go:274 +0x7bc
  | github.com/hashicorp/nomad/scheduler.(*JobAntiAffinityIterator).Next(0x14000eac5a0)
  | \t/Users/juanita.delacuestamorales/go/src/github.com/hashicorp/nomad/scheduler/rank.go:616 +0x4c
  | github.com/hashicorp/nomad/scheduler.(*NodeReschedulingPenaltyIterator).Next(0x14000a09a70)
  | \t/Users/juanita.delacuestamorales/go/src/github.com/hashicorp/nomad/scheduler/rank.go:677 +0x40
  | github.com/hashicorp/nomad/scheduler.(*NodeAffinityIterator).Next(0x14000eac5f0)
  | \t/Users/juanita.delacuestamorales/go/src/github.com/hashicorp/nomad/scheduler/rank.go:749 +0x44
  | github.com/hashicorp/nomad/scheduler.(*SpreadIterator).Next(0x14000478150)
  | \t/Users/juanita.delacuestamorales/go/src/github.com/hashicorp/nomad/scheduler/spread.go:131 +0x4c
  | github.com/hashicorp/nomad/scheduler.(*PreemptionScoringIterator).Next(0x14000c80c00)
  | \t/Users/juanita.delacuestamorales/go/src/github.com/hashicorp/nomad/scheduler/rank.go:844 +0x40
  | github.com/hashicorp/nomad/scheduler.(*ScoreNormalizationIterator).Next(0x14000c80c20)
  | \t/Users/juanita.delacuestamorales/go/src/github.com/hashicorp/nomad/scheduler/rank.go:808 +0x40
  | github.com/hashicorp/nomad/scheduler.(*LimitIterator).nextOption(0x14000e00720)
  | \t/Users/juanita.delacuestamorales/go/src/github.com/hashicorp/nomad/scheduler/select.go:63 +0x3c
  | github.com/hashicorp/nomad/scheduler.(*LimitIterator).Next(0x14000e00720)
  | \t/Users/juanita.delacuestamorales/go/src/github.com/hashicorp/nomad/scheduler/select.go:42 +0x60
  | github.com/hashicorp/nomad/scheduler.(*MaxScoreIterator).Next(0x14000a09b00)
  | \t/Users/juanita.delacuestamorales/go/src/github.com/hashicorp/nomad/scheduler/select.go:105 +0x6c
  | github.com/hashicorp/nomad/scheduler.(*GenericStack).Select(0x140011901a0, 0x140009e4ea0, 0x14000b8c940)
  | \t/Users/juanita.delacuestamorales/go/src/github.com/hashicorp/nomad/scheduler/stack.go:192 +0x5c8
  | github.com/hashicorp/nomad/scheduler.(*GenericScheduler).selectNextOption(0x14000aaea50, 0x140009e4ea0, 0x14000b8c940)
  | \t/Users/juanita.delacuestamorales/go/src/github.com/hashicorp/nomad/scheduler/generic_sched.go:869 +0x48
  | github.com/hashicorp/nomad/scheduler.(*GenericScheduler).computePlacements(0x14000aaea50, {0x104eb53e0, 0x0, 0x0}, {0x14000a19940, 0x1, 0x1})
  | \t/Users/juanita.delacuestamorales/go/src/github.com/hashicorp/nomad/scheduler/generic_sched.go:595 +0x9cc
  | github.com/hashicorp/nomad/scheduler.(*GenericScheduler).computeJobAllocs(0x14000aaea50)
  | \t/Users/juanita.delacuestamorales/go/src/github.com/hashicorp/nomad/scheduler/generic_sched.go:469 +0x1190
  | github.com/hashicorp/nomad/scheduler.(*GenericScheduler).process(0x14000aaea50)
  | \t/Users/juanita.delacuestamorales/go/src/github.com/hashicorp/nomad/scheduler/generic_sched.go:289 +0x778
  | github.com/hashicorp/nomad/scheduler.retryMax(0x2, 0x14000caf928, 0x14000caf898)
  | \t/Users/juanita.delacuestamorales/go/src/github.com/hashicorp/nomad/scheduler/util.go:96 +0x58
  | github.com/hashicorp/nomad/scheduler.(*GenericScheduler).Process(0x14000aaea50, 0x14000e44480)
  | \t/Users/juanita.delacuestamorales/go/src/github.com/hashicorp/nomad/scheduler/generic_sched.go:188 +0x1584
  | github.com/hashicorp/nomad/nomad.(*Worker).invokeScheduler(0x1400071e380, 0x14000a21ad0, 0x14000e44480, {0x14001086600, 0x24})
  | \t/Users/juanita.delacuestamorales/go/src/github.com/hashicorp/nomad/nomad/worker.go:629 +0x538
  | github.com/hashicorp/nomad/nomad.(*Worker).run(0x1400071e380, 0x12a05f200)
  | \t/Users/juanita.delacuestamorales/go/src/github.com/hashicorp/nomad/nomad/worker.go:458 +0xa74
  | created by github.com/hashicorp/nomad/nomad.(*Worker).Start in goroutine 1
  | \t/Users/juanita.delacuestamorales/go/src/github.com/hashicorp/nomad/nomad/worker.go:158 +0x88
```

**Comment by shoenig** [comment]
I've walked through a complete upgrade from 1.6.3 -> 1.7.0-beta.1 in a production ready cluster, using in-place agent swaps. 3 servers and 3 clients, upgrading servers first. On the clients I had raw_exec, exec, and docker tasks running. Everything went smoothly AFAICT.
