### ISSUE TITLE
E2E: UI tests failing before they start

### ISSUE THREAD

**Issue by gulducat** [hashicorp/nomad#19114]
The e2e test workflow [here](https://github.com/hashicorp/nomad-e2e/blob/e6a28d9/.github/workflows/e2e-runner.yml#L289-L300) (private repo) runs this:

```
nomad namespace apply proxy
nomad job run ./e2e/ui/input/proxy.nomad
IP=$(nomad node status -json -verbose "$(nomad operator api '/v1/allocations?namespace=proxy' | jq -r '.[] | select(.JobID == "nomad-proxy") | .NodeID')" | jq -r '.Attributes."unique.platform.aws.public-ipv4"')
export NOMAD_ADDR="https://$IP:6464"
echo "running UI tests against $NOMAD_ADDR"
docker run -it --rm -v "$(pwd)"/e2e/ui:/src -w /src -e NOMAD_ADDR="$NOMAD_ADDR" -e NOMAD_TOKEN="$NOMAD_TOKEN" --ipc=host --net=host mcr.microsoft.com/playwright:focal bash script.sh
```

which fails like this:

```
Successfully applied namespace "proxy"!
==> 2023-11-16T20:39:21Z: Monitoring evaluation "382e659d"
    2023-11-16T20:39:21Z: Evaluation triggered by job "nomad-proxy"
    2023-11-16T20:39:22Z: Evaluation within deployment: "ecd7d0d0"
    2023-11-16T20:39:22Z: Allocation "8f33eca7" created: node "e170f7e1", group "proxy"
    2023-11-16T20:39:22Z: Evaluation status changed: "pending" -> "complete"
==> 2023-11-16T20:39:22Z: Evaluation "382e659d" finished with status "complete"
==> 2023-11-16T20:39:22Z: Monitoring deployment "ecd7d0d0"
    
2023-11-16T20:39:22Z
ID          = ecd7d0d0
Job ID      = nomad-proxy
Job Version = 0
Status      = running
Description = Deployment is running

Deployed
Task Group  Desired  Placed  Healthy  Unhealthy  Progress Deadline
proxy       1        1       0        0          2023-11-16T20:49:21Z
    
2023-11-16T20:39:38Z
ID          = ecd7d0d0
Job ID      = nomad-proxy
Job Version = 0
Status      = running
Description = Deployment is running

Deployed
Task Group  Desired  Placed  Healthy  Unhealthy  Progress Deadline
proxy       1        1       1        0          2023-11-16T20:49:38Z
    
2023-11-16T20:39:39Z
ID          = ecd7d0d0
Job ID      = nomad-proxy
Job Version = 0
Status      = successful
Description = Deployment completed successfully

Deployed
Task Group  Desired  Placed  Healthy  Unhealthy  Progress Deadline
proxy       1        1       1        0          2023-11-16T20:49:38Z
parse error: Invalid numeric literal at line 1, column 8
Prefix matched multiple nodes

ID                                    DC   Name              Class   Drain  Eligibility  Status
b035da60-b8ce-fbc1-4822-0dd4ee994fd6  dc1  EC2AMAZ-NHFTA7S   <none>  false  eligible     ready
e170f7e1-80d1-3e21-3ea6-7238fc996ecd  dc1  ip-172-31-87-242  <none>  false  eligible     ready
9336b433-b21c-184c-e2ca-6270dc88752f  dc2  ip-172-31-83-252  <none>  false  eligible     ready
87447de8-c5a5-2f3b-6448-025dfb192d74  dc1  ip-172-31-90-161  <none>  false  eligible     ready
41f03e06-2f49-5187-e8b7-f16fe73d75a2  dc2  ip-172-31-88-157  <none>  false  eligible     ready
running UI tests against https://:6464
the input device is not a TTY
Error: Process completed with exit code 1.
```

First gotta overcome the parse error trying to get an IP the proxy is running on, to use as a NOMAD_ADDR, then see if tests run okay.

**Comment by gulducat** [comment]
After appropriately getting the proxy IP, the test is able to run, but errors with:

```
Error: page.click: Timeout 30000ms exceeded.
Call log:
  - waiting for locator('button:has-text("Set Token")')


   at global-setup.js:25

  23 |   await page.goto(NOMAD_ADDR+'/ui/settings/tokens');
  24 |   await page.fill('input[id="token-input"]', NOMAD_TOKEN);
> 25 |   await page.click('button:has-text("Set Token")', {strict: true});
     |              ^
  26 |
  27 |   await page.context().storageState({ path: 'storageState.json' });
  28 |   await browser.close();

    at module.exports (/src/global-setup.js:25:14)
```

then after updating that button to "Sign in" instead of "Set Token", the login state apparently was not persisted:

```
    Error: Timed out 5000ms waiting for expect(locator).toBeVisible()

    Locator: locator('text=Policies')
    Expected: visible
    Received: hidden
    Call log:
      - expect.toBeVisible with timeout 5000ms
      - waiting for locator('text=Policies')


      21 |
      22 |   const policies = page.locator('text=Policies')
    > 23 |   await expect(policies).toBeVisible();
         |                          ^
      24 | });
      25 |

        at /src/tests/example.spec.js:23:26
```

"Policies" not visible because it's showing the sign-in page again.

**Comment by gulducat** [comment]
"device is not a TTY" is due to `docker run -it`, so need to detect that as appropriate and not use `-it` in CI.
