### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by willcharlton** [hashicorp/nomad#19455]
### Nomad version
Output from `nomad version`: `1.7.1`

### Operating system and Environment details

Nomad server running in docker container (multani/nomad) with sockd proxy for nomad agent traffic on port 4647. Server is running on a linode with debian 11. The server and client establish comms with mTLS over the socks5 port (clients show up in nomad UI).

### Issue

I am using the `nomad` cli to run jobs and they are failing. I am seeing the stack trace (see below) in both nomad server logs and the ui > Clients > <client> > Monitor tab.

It's possible that the stack trace and the job failure are unrelated, but the error log asked me to file this as a bug.

### Reproduction steps

I have two clients (arm64 and x86_64) connected to a single server. Launch job file targeting a single client via `${meta.machine_id} = foo` with x86_64 client agent.hcl set to the same.

#### Expected Result

Job runs a simple shell command and the output is found in the allocation.

#### Actual Result

Job fails to run.

### Job file (if appropriate)

```
job "env" {
  datacenters = ["global"]
  type = "sysbatch"

  meta {
    run_uuid = "${uuidv4()}"
  }
  group "env" {

    task "env" {
      driver = "raw_exec"

      config {
        command = "/bin/sh"
        args    = ["-c", "env"]
      }
    }
  }
}
```

### Nomad Server logs (if appropriate)

```
    2023-12-13T06:38:26.504Z [DEBUG] worker: dequeued evaluation: worker_id=2e5cf912-4ddb-414d-f0b0-1ee5bb3c3576 eval_id=e2a3bd94-46e8-f91f-0b28-bfb771a90ce3 type=sysbatch namespace=default job_id=env node_id="" triggered_by=failed-follow-up
    2023-12-13T06:38:26.504Z [DEBUG] worker.sysbatch_sched: reconciled current state with desired state: eval_id=e2a3bd94-46e8-f91f-0b28-bfb771a90ce3 job_id=env namespace=default worker_id=2e5cf912-4ddb-414d-f0b0-1ee5bb3c3576 results="allocs: (place 2) (update 0) (migrate 0) (stop 0) (ignore 0) (lost 0) (disconnecting 0) (reconnecting 0)"
    2023-12-13T06:38:26.504Z [ERROR] worker.sysbatch_sched: processing eval panicked scheduler - please report this as a bug!: eval_id=e2a3bd94-46e8-f91f-0b28-bfb771a90ce3 job_id=env namespace=default worker_id=2e5cf912-4ddb-414d-f0b0-1ee5bb3c3576 eval_id=e2a3bd94-46e8-f91f-0b28-bfb771a90ce3 error="runtime error: invalid memory address or nil pointer dereference"
  stack_trace=
  | goroutine 57 [running]:
  | runtime/debug.Stack()
  | \truntime/debug/stack.go:24 +0x5e
  | github.com/hashicorp/nomad/scheduler.(*SystemScheduler).Process.func1()
  | \tgithub.com/hashicorp/nomad/scheduler/scheduler_system.go:83 +0x58
  | panic({0x2a68b80?, 0x4f24a40?})
  | \truntime/panic.go:914 +0x21f
  | github.com/hashicorp/nomad/client/lib/numalib.(*Topology).UsableCores(...)
  | \tgithub.com/hashicorp/nomad/client/lib/numalib/topology.go:252
  | github.com/hashicorp/nomad/nomad/structs.(*NodeResources).Comparable(0xc0005bad20)
  | \tgithub.com/hashicorp/nomad/nomad/structs/structs.go:3177 +0xcc
  | github.com/hashicorp/nomad/scheduler.(*Preemptor).SetNode(0xc0006e7048, 0xc00074f680)
  | \tgithub.com/hashicorp/nomad/scheduler/preemption.go:139 +0x36
  | github.com/hashicorp/nomad/scheduler.(*BinPackIterator).Next(0xc000694070)
  | \tgithub.com/hashicorp/nomad/scheduler/rank.go:274 +0x74d
  | github.com/hashicorp/nomad/scheduler.(*ScoreNormalizationIterator).Next(0xc000bac660)
  | \tgithub.com/hashicorp/nomad/scheduler/rank.go:808 +0x28
  | github.com/hashicorp/nomad/scheduler.(*SystemStack).Select(0xc001090300, 0xc000478240, 0xc0006e7790)
  | \tgithub.com/hashicorp/nomad/scheduler/stack.go:362 +0x82e
  | github.com/hashicorp/nomad/scheduler.(*SystemScheduler).computePlacements(0xc000a540c0, {0xc00152c380, 0x2, 0x3?})
  | \tgithub.com/hashicorp/nomad/scheduler/scheduler_system.go:374 +0x325
  | github.com/hashicorp/nomad/scheduler.(*SystemScheduler).computeJobAllocs(0xc000a540c0)
  | \tgithub.com/hashicorp/nomad/scheduler/scheduler_system.go:322 +0xb85
  | github.com/hashicorp/nomad/scheduler.(*SystemScheduler).process(0xc000a540c0)
  | \tgithub.com/hashicorp/nomad/scheduler/scheduler_system.go:163 +0x4da
  | github.com/hashicorp/nomad/scheduler.retryMax(0x2, 0xc0006e7d80, 0xc0006e7d70)
  | \tgithub.com/hashicorp/nomad/scheduler/util.go:96 +0x49
  | github.com/hashicorp/nomad/scheduler.(*SystemScheduler).Process(0xc000a540c0, 0xc0006f0300)
  | \tgithub.com/hashicorp/nomad/scheduler/scheduler_system.go:108 +0x525
  | github.com/hashicorp/nomad/nomad.(*Worker).invokeScheduler(0xc000d14fc0, 0xc000c64990, 0xc0006f0300, {0xc0011f2210, 0x24})
  | \tgithub.com/hashicorp/nomad/nomad/worker.go:629 +0x353
  | github.com/hashicorp/nomad/nomad.(*Worker).run(0xc000d14fc0, 0x12a05f200)
  | \tgithub.com/hashicorp/nomad/nomad/worker.go:458 +0x5a5
  | created by github.com/hashicorp/nomad/nomad.(*Worker).Start in goroutine 1
  | \tgithub.com/hashicorp/nomad/nomad/worker.go:158 +0x59
  
    2023-12-13T06:38:26.504Z [ERROR] worker: error invoking scheduler: worker_id=2e5cf912-4ddb-414d-f0b0-1ee5bb3c3576 error="failed to process evaluation: failed to process eval: runtime error: invalid memory address or nil pointer dereference"
    2023-12-13T06:38:26.504Z [DEBUG] worker: nack evaluation: worker_id=2e5cf912-4ddb-414d-f0b0-1ee5bb3c3576 eval_id=e2a3bd94-46e8-f91f-0b28-bfb771a90ce3 type=sysbatch namespace=default job_id=env node_id="" triggered_by=failed-follow-up
    2023-12-13T06:38:26.505Z [WARN]  nomad: eval reached delivery limit, marking as failed: eval="<Eval \"e2a3bd94-46e8-f91f-0b28-bfb771a90ce3\" JobID: \"env\" Namespace: \"default\">"
```

### Nomad Client logs (if appropriate)

Client version = `1.6.3`

```
Dec 13 00:30:29 user-ubuntu nomad[82609]:     2023-12-13T00:30:29.495-0600 [DEBUG] client: received stale allocation information; retrying: index=1 min_index=1
```

**Comment by tgross** [comment]
Hi @willcharlton! You're hitting the same panic that was reported in https://github.com/hashicorp/nomad/issues/19407, which we're actively working on. I'm going to close this as a duplicate.

(I'll also point out that `multani/nomad` in not our official Docker container, so any problems specific to that you'll need to take to the author. Running clients in containers is explicitly unsupported, but it doesn't look like the problem at hand here.)
