### ISSUE TITLE
Panic: runtime error: invalid memory address or nil pointer dereference after upgrade to 1.7.x

### ISSUE THREAD

**Issue by fendrychl** [hashicorp/nomad#19961]
### Nomad version
Nomad v1.7.4
BuildDate 2024-02-08T14:34:12Z
Revision 29019121564e2ef7f5e2a227af6b959510bcc142

### Operating system and Environment details
Debian in lxd container

### Issue
After upgrade to 1.7.4, nomad client did not start and exited with panic error. I have successfully downgraded to 1.6.4. This version works fine.

Thank you.

### Nomad Client logs (if appropriate)
==> Starting Nomad agent...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xfd65ea]

goroutine 1 [running]:
github.com/hashicorp/nomad/client/lib/idset.(*Set[...]).Size(...)
        github.com/hashicorp/nomad/client/lib/idset/idset.go:190
github.com/hashicorp/nomad/client/lib/numalib.gradeOf(...)
        github.com/hashicorp/nomad/client/lib/numalib/topology.go:31
github.com/hashicorp/nomad/client/lib/numalib.(*Sysfs).discoverCores.func2.1(0x0)
        github.com/hashicorp/nomad/client/lib/numalib/detect_linux.go:140 +0x1ea
github.com/hashicorp/nomad/client/lib/idset.(*Set[...]).ForEach(0xc000c15e28?, 0xc000f06b58?)
        github.com/hashicorp/nomad/client/lib/idset/idset.go:181 +0x18c
github.com/hashicorp/nomad/client/lib/numalib.(*Sysfs).discoverCores.func2(0x0)
        github.com/hashicorp/nomad/client/lib/numalib/detect_linux.go:127 +0xf5
github.com/hashicorp/nomad/client/lib/idset.(*Set[...]).ForEach(0x31032d8?, 0xc000f06cd0?)
        github.com/hashicorp/nomad/client/lib/idset/idset.go:181 +0x18b
github.com/hashicorp/nomad/client/lib/numalib.(*Sysfs).discoverCores(0x37edca0, 0xc00100b6d0, 0x3217be8)
        github.com/hashicorp/nomad/client/lib/numalib/detect_linux.go:120 +0xf5
github.com/hashicorp/nomad/client/lib/numalib.(*Sysfs).ScanSystem(0xc000f06e48?, 0xc00100b6d0)
        github.com/hashicorp/nomad/client/lib/numalib/detect_linux.go:60 +0x9b
github.com/hashicorp/nomad/client/lib/numalib.Scan(...)
        github.com/hashicorp/nomad/client/lib/numalib/detect.go:23
github.com/hashicorp/nomad/client/fingerprint.(*CPUFingerprint).initialize(0xc00093a200, 0xc000b87fe0)
        github.com/hashicorp/nomad/client/fingerprint/cpu.go:90 +0x4ab
github.com/hashicorp/nomad/client/fingerprint.(*CPUFingerprint).Fingerprint(0xc00093a200, 0x3838190?, 0xc000adb320)
        github.com/hashicorp/nomad/client/fingerprint/cpu.go:40 +0x25
github.com/hashicorp/nomad/client.(*FingerprintManager).fingerprint(0xc000b94300, {0x3?, 0x3838190?}, {0x3805a10, 0xc00093a200})
        github.com/hashicorp/nomad/client/fingerprint_manager.go:200 +0xd2
github.com/hashicorp/nomad/client.(*FingerprintManager).setupFingerprinters(0xc000b94300, {0xc000271e00?, 0x13, 0x10?})
        github.com/hashicorp/nomad/client/fingerprint_manager.go:143 +0xfb
github.com/hashicorp/nomad/client.(*FingerprintManager).Run(0xc000b94300)
        github.com/hashicorp/nomad/client/fingerprint_manager.go:107 +0x49b
github.com/hashicorp/nomad/client.NewClient(0xc0007b6580, {0x3803018?, 0xc000604b40}, 0xc00075c1b0, {0x3817c40?, 0xc0005b0220}, 0x1b7eba5?)
        github.com/hashicorp/nomad/client/client.go:468 +0x1196
github.com/hashicorp/nomad/command/agent.(*Agent).setupClient(0xc0004d6300)
        github.com/hashicorp/nomad/command/agent/agent.go:1131 +0x2cc
github.com/hashicorp/nomad/command/agent.NewAgent(0xc000755200, {0x383f568?, 0xc000d8d440}, {0x37f2100?, 0xc000f0a060}, 0xc000c04c30)
        github.com/hashicorp/nomad/command/agent/agent.go:160 +0x1f3
github.com/hashicorp/nomad/command/agent.(*Command).setupAgent(0xc000a5ce00, 0xc000755200, {0x383f568, 0xc000d8d440}, {0x37f2100, 0xc000f0a060}, 0x0?)
        github.com/hashicorp/nomad/command/agent/command.go:619 +0xa5
github.com/hashicorp/nomad/command/agent.(*Command).Run(0xc000a5ce00, {0xc0001ec1e0, 0x2, 0x2})
        github.com/hashicorp/nomad/command/agent/command.go:836 +0x61b
github.com/mitchellh/cli.(*CLI).Run(0xc0005feb40)
        github.com/mitchellh/cli@v1.1.5/cli.go:262 +0x5b8
main.Run({0xc0001ec1d0, 0x3, 0x3})
        github.com/hashicorp/nomad/main.go:112 +0x228
main.main()
        github.com/hashicorp/nomad/main.go:82 +0x45

**Comment by tgross** [comment]
Looks like we're panicking because [`detect_linux.go#L132`](https://github.com/hashicorp/nomad/blob/main/client/lib/numalib/detect_linux.go#L132) is returning a nil pointer. That'd be because your host is missing `/sys/devices/system/cpu/cpu{id}/topology/thread_siblings_list` (and potentially other `/sys` files in that range). Or rather, the LXD container in which you're running Nomad is missing that file. Note that [running Nomad clients in a container is not supported](https://developer.hashicorp.com/nomad/docs/install/production/requirements#running-nomad-in-docker). But obviously we'd rather not panic in this situation and return a meaningful error message.
