### ISSUE TITLE
SIGSEGV on upgrade from Nomad 0.3.2 to 0.5.4

### ISSUE THREAD

**Issue by Gerrrr** [hashicorp/nomad#2304]
### Nomad version
Nomad v0.5.4

### Operating system and Environment details
Ubuntu 14.04.2 LTS

### Issue
Upgrading from Nomad 0.3.2 to 0.5.4 caused invalid memory address or nil pointer dereference on the servers:

```
Loaded configuration from /etc/nomad.d/server/config.hcl
==> Starting Nomad agent...
==> Joining cluster...
    Join completed. Synced with 3 initial agents
==> Nomad agent configuration:

                 Atlas: <disabled>
                Client: false
             Log Level: INFO
                Region: global (DC: dc1)
                Server: true
               Version: 0.5.4

==> Nomad agent started! Log data will stream in below:

    2017/02/09 14:14:08 [INFO] raft: Restored from snapshot 2588-3551901-1486626981169
    2017/02/09 14:14:08 [INFO] raft: Node at 10.250.18.20:4647 [Follower] entering Follower state (Leader: "")
    2017/02/09 14:14:08 [INFO] serf: EventMemberJoin: 10-250-18-20.global 10.250.18.20
    2017/02/09 14:14:08.064253 [INFO] nomad: starting 4 scheduling worker(s) for [service batch system _core]
    2017/02/09 14:14:08 [INFO] serf: Attempting re-join to previously known node: 10-250-18-21.global: 10.250.18.21:4648
    2017/02/09 14:14:08.065869 [INFO] nomad: adding server 10-250-18-20.global (Addr: 10.250.18.20:4647) (DC: dc1)
    2017/02/09 14:14:08 [INFO] serf: EventMemberJoin: 10-250-18-22.global 10.250.18.22
    2017/02/09 14:14:08.068539 [INFO] nomad: adding server 10-250-18-22.global (Addr: 10.250.18.22:4647) (DC: dc1)
    2017/02/09 14:14:08 [INFO] serf: EventMemberJoin: 10-250-18-21.global 10.250.18.21
    2017/02/09 14:14:08 [WARN] memberlist: Refuting an alive message
    2017/02/09 14:14:08.069171 [INFO] nomad: adding server 10-250-18-21.global (Addr: 10.250.18.21:4647) (DC: dc1)
    2017/02/09 14:14:08 [INFO] serf: Re-joined to previously known node: 10-250-18-21.global: 10.250.18.21:4648
    2017/02/09 14:14:08.089127 [INFO] server.consul: successfully contacted 2 Nomad Servers
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x118 pc=0xc49101]

goroutine 12 [running]:
panic(0x1000940, 0xc420012050)
        /opt/go/src/runtime/panic.go:500 +0x1a1
github.com/hashicorp/nomad/nomad/state.(*StateStore).ReconcileJobSummaries(0xc4201ac680, 0x3641ee, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/nomad/nomad/state/state_store.go:1455 +0x401
github.com/hashicorp/nomad/nomad.(*nomadFSM).applyReconcileSummaries(0xc42049ca40, 0xc420deb481, 0x8, 0x8, 0x3641ee, 0xc77548, 0xc4204aee88)
        /opt/gopath/src/github.com/hashicorp/nomad/nomad/fsm.go:473 +0x3d
github.com/hashicorp/nomad/nomad.(*nomadFSM).Apply(0xc42049ca40, 0xc420885ec0, 0x19427e0, 0xed02e6201)
        /opt/gopath/src/github.com/hashicorp/nomad/nomad/fsm.go:141 +0x69b
github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft.(*Raft).runFSM(0xc42042e1e0)
        /opt/gopath/src/github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft/raft.go:577 +0xc56
github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft.(*Raft).(github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft.runFSM)-fm()
        /opt/gopath/src/github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft/raft.go:258 +0x2a
github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc42042e1e0, 0xc4207ff800)
        /opt/gopath/src/github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft/state.go:154 +0x4d
created by github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft.(*raftState).goFunc
        /opt/gopath/src/github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft/state.go:155 +0x57
    Loaded configuration from /etc/nomad.d/server/config.hcl
==> Starting Nomad agent...
```

We backed up the nomad server state directories which caused the `SIGSEGV` and decided to start with empty state. We expected clients to check against the servers and stop currently running allocations, but the clients fail to do it:

```
* RPC failed to server 10.250.18.21:4647: rpc error: failed to get conn: dial tcp 10.250.18.21:4647: getsockopt: connection refused
   2017/02/09 14:24:59.508437 [INFO] client: node registration complete
   2017/02/09 14:25:12.018562 [INFO] client: node registration complete
   2017/02/09 14:25:47.303564 [ERR] client: failed to kill task 'infra-app-meta' for alloc "6233d059-e252-5998-0419-fd1b6579cc90". Retrying in 5s: executor Shutdown failed: unexpected EOF
   2017/02/09 14:25:47.303599 [ERR] client: failed to kill task 'rstudio' for alloc "20cd5f26-6a3b-81e9-4e97-060c6528be95". Retrying in 5s: executor Shutdown failed: unexpected EOF
   2017/02/09 14:25:47.303654 [WARN] client: error fetching stats of task rstudio: rpc: can't find method Plugin.Stats
   2017/02/09 14:25:47.303702 [ERR] driver.raw_exec: failed to deregister services: connection is shut down
   2017/02/09 14:25:47.303814 [ERR] driver.raw_exec: error killing executor: connection is shut down
   2017/02/09 14:25:47.303833 [WARN] client: error fetching stats of task infra-proxy-apps: rpc: can't find method Plugin.Stats
   2017/02/09 14:25:47.303991 [ERR] driver.raw_exec: failed to deregister services: connection is shut down
   2017/02/09 14:25:47.304029 [ERR] driver.raw_exec: error killing executor: connection is shut down
   2017/02/09 14:25:47.304130 [ERR] driver.raw_exec: failed to deregister services: connection is shut down
   2017/02/09 14:25:47.304197 [ERR] driver.raw_exec: error killing executor: connection is shut down
   2017/02/09 14:25:47.304021 [WARN] client: error fetching stats of task infra-app-meta: rpc: can't find method Plugin.Stats
   2017/02/09 14:25:47.303826 [ERR] client: failed to kill task 'infra-proxy-apps' for alloc "c977971a-d238-9026-5fda-1f3d6b408dae". Retrying in 5s: executor Shutdown failed: unexpected EOF
   2017/02/09 14:25:47.308015 [WARN] client: error fetching stats of task consul-alerts: rpc: can't find method Plugin.Stats
   2017/02/09 14:25:47.308524 [WARN] client: error fetching stats of task consul-alerts: unexpected EOF
   2017/02/09 14:25:47.308638 [ERR] client: failed to kill task 'consul-alerts' for alloc "cc74540f-f172-3a7a-13bb-3c73cdd0ac09". Retrying in 5s: executor Shutdown failed: unexpected EOF
   2017/02/09 14:25:47.309189 [ERR] driver.raw_exec: failed to deregister services: connection is shut down
   2017/02/09 14:25:47.309958 [ERR] driver.raw_exec: error killing executor: connection is shut down
```

**Comment by dadgar** [comment]
Fixed in 60d1e80461304cd0a11efdc672c04b8a90d6c132.

Updating two major releases at once is not really recommended. I would in the future do sequential upgrades as we may have deprecated upgrade paths on the second major release

**Comment by akaspin** [comment]
This issue is horrible. Any chance for bugfix release?

**Comment by dadgar** [comment]
@akaspin https://releases.hashicorp.com/nomad/0.5.5-rc1/
