### ISSUE TITLE
Nomad client processes consume a lot of CPU on Windows Server

### ISSUE THREAD

**Issue by Settler** [hashicorp/nomad#23323]
### Nomad version
Nomad v1.8.0
BuildDate 2024-05-28T17:38:17Z
Revision 28b82e4b2259fae5a62e2ed47395334bea5a24c4

### Operating system and Environment details
Windows Server 2019

### Issue
Previously we reported issue #20042 which was fixed in 1.8.0. We ran another tests and found that problem with abnormal cpu consumption on Windows is still exists in 1.8.0. 
Today I present to you another graph where we can compare behaviour in nomad 1.6.10 and 1.8.0
![image](https://github.com/hashicorp/nomad/assets/104102/0e7ac0ec-b48c-4f34-b080-a2656b2a084d)

Upper graph – Server with nomad v1.6.10 (which is under load of 81 working allocations)
Bottom graph – Server with nomad v1.8.0 (clean server with new nomad version without working allocations)
Red horizontal lines with spikes – 95th percentile of overall CPU on machine.
Blue ares – CPU consumption sum of all nomad processes

And again we've tested different workloads (on each server at the same time):
- 20 allocs on each server
- 50 allocs on each server
- 100 allocs on each server
- 200 allocs on each server

As you can see, nomad 1.6.10 won again. Despite the fact that server with nomad 1.6.10 was under load of 81 allocations, when we added additional 200 allocations, it consumed less CPU than server with nomad 1.8.0. Both servers have same specs. And we clearly see that main CPU consumers of server with 1.8.0 were processes of nomad itself.

On Linux environment everything is okay.

### Reproduction steps
Run example job file on Windows. Tweak alloc count variable to achieve ~75% overall CPU consumption.

#### Expected Result
CPU consumption of nomad processes same as 1.6.x version.

#### Actual Result
Inappropriate nomad CPU consumption.

### Job file (if appropriate)
```
locals {
  allocs = 100
}

job "PSTest" {
  type = "service"
  
  group "PSTest-Group" {
    count = "${local.allocs}"
    
    task "PSTest" {
      driver = "raw_exec"
      kill_timeout = "10s"

      config {
        command = "powershell"
        args = ["./test.ps1"]
      }
      
      resources {
        cpu = 50
        memory = 100
      }        
      
      template {
        data = <<EOH

for (($i = 0); $i -lt 3600; $i++)
{
    Write-Host $i
    Start-Sleep -Second 180
}
                EOH
        destination = "./test.ps1"
        change_mode = "noop"
      }
    }
  }
}

```

**Comment by tgross** [comment]
Hi @Settler! Just out of curiosity, do you see the same results in Nomad 1.8.x when the job doesn't have a `template` block? We made some fairly large changes to template rendering on Windows which we're likely to back out very soon. But if those are the source of heavy CPU utilization that would help me make the case to do the work even sooner.

**Comment by Settler** [comment]
Hi @tgross!
We've ran sample job without template block (placed ps file on the server) and didn't see any difference.
![image](https://github.com/hashicorp/nomad/assets/104102/9d6aa170-439f-4087-bc1e-1da819ab76d9)
This graph shows 100 and 200 allocations on the server.

**Comment by tgross** [comment]
Ok, sorry to hear that wasn't the case. I'll mark this issue for further investigation.

**Comment by lbv2rus** [comment]
The same issue in Nomad 1.9.3.
100 dummy alloc on Windows-node with Nomad 1.9.3 consume almost 100% CPU.

Upper graph – Server with nomad v1.9.3
Bottom graph – Server with nomad v1.6.10

Both nodes are physical servers with no other load.

![image](https://github.com/user-attachments/assets/6969e0bb-cc09-44e7-ba35-4f34dec8ebaa)

**Comment by lbv2rus** [comment]
After a series of tests, I found that when the main process (Windows service) is stopped, Nomad's load almost completely disappears, while all allocations continues to work.

When the main process is started again, Nomad attaches all running allocations and the CPU load increases again.
It can be assumed that the load is related to receiving statistics from processes tree.

It is worth noting that the load does not increase linearly, from which i can assume that the main Nomad process at some point stops having time to poll the entire process tree before the start of the next polling cycle. 
Is there any way to increase the polling interval of the process tree for allocations?

Test with 100 alloc with Nomad 1.9.4 on bare-metal client-node with Windows Server.
![изображение](https://github.com/user-attachments/assets/b4d92070-6fc3-4085-a2f4-c29c51c2958d)

**Comment by grembo** [comment]
@lbv2rus I had an issue with very similar symptoms on FreeBSD, caused by a change in v1.7.7 (change in config enabled the wait feature in consul-template, which causes a massive increase in signals and a 5-7x load increase in my setup. I created #25255, which fixes the problem for me. Even though I cannot tell if your problem is actually the same thing, it might want to take a look/test.

**Comment by tgross** [comment]
Hi folks! I'm picking this back up to do some more investigation. A user was able to get us a CPU profile for their Nomad client agents on Windows. I found a lot of goroutines burning CPU time in Windows syscalls, particularly in IO from reading logs from allocations and plugin RPCs. But the test they were running was maybe unrealistic in terms of the number of allocations vs the number of cores available. While I debug that and follow-up with them, I want to make sure that this isn't unrepresentative of the problems folks are reporting here.

If you are on Windows and experiencing high CPU load on the Nomad clients, it would be helpful if you could run a 30s CPU profile for us using the [Agent Runtime Profile API](https://developer.hashicorp.com/nomad/api-docs/agent#agent-runtime-profiles) (`/v1/agent/pprof/profile?seconds=30` or `/debug/pprof/profile?seconds=30`). You can then send the resulting file along with the version of Nomad you're using to nomad-oss-debug@hashicorp.com, which is a write-only email address that only Nomad Engineering can read.

If you're not on Windows and running into CPU load issues, do me a favor and open an issue specific to your platform.

**Comment by tgross** [comment]
I did want to share some preliminary analysis on the profiles I did get (goroutine, cpu, and trace). It looks like the Nomad process is burning all its CPU time in Windows syscalls. I don't yet have any ideas on how we're going to fix or workaround this, but that's why I want to gather more data from you kind folks if possible.

When a Go application (Nomad in this case) makes a non-blocking syscall, the runtime puts the goroutine in a network poller backed by whatever mechanism the OS provides (epoll on Linux, kqueue on BSD, or IO completion ports on Windows) and comes back to it when that mechanism unblocks. But for blocking syscalls like file operations, the runtime has to make a decision between waiting on that call or spawning an OS thread to park the goroutine in until the work is done.

The profiles I've examined where on a machine which was running from between 50-100 allocs during various snapshots taken. The details below are at the high end of that range.

In the goroutine profile, I can see that we have hundreds of goroutines servicing syscalls. The bulk of them are in go-plugin blocking while reading logs from the workloads ([`client.go#L1172`](https://github.com/hashicorp/go-plugin/blob/v1.6.2/client.go#L1172)) or in various bits of gRPC transport used by go-plugin ([`grpc_client.go#L76`](https://github.com/hashicorp/nomad/blob/v1.10.1/drivers/shared/executor/grpc_client.go#L76))

([`goroutine-inspect`](https://github.com/tgross/goroutine-inspect) output)

```
goroutine 319304 [syscall]: 159 times: [319304, 322248, 316589, 319395, 321131, 318625, 317547, 318285, 318563, 319350, 318465, 318344, 319658, 316469, 318111, 318637, 320600, 323138, 316678, 318327, 316764, 321441, 316724, 320522, 320525, 319462, 322673, 321657, 323199, 319090, 320326, 319108, 323329, 318953, 318959, 320684, 316923, 318347, 317318, 320708, 319317, 321163, 321479, 321445, 317315, 322831, 317462, 319692, 321455, 322192, 317600, 322863, 321171, 319081, 319029, 319681, 319812, 321035, 322934, 322942, 317532, 321199, 316839, 318571, 317925, 319792, 320620, 320137, 323071, 318772, 320168, 319836, 322798, 319743, 316532, 320119, 318033, 319678, 320101, 322700, 317497, 316619, 320479, 322881, 318214, 319400, 321152, 317969, 318622, 316851, 321561, 323204, 317360, 318813, 317501, 319553, 319950, 321936, 316985, 320733, 317899, 319752, 318723, 322274, 318193, 316418, 318704, 317813, 317378, 321052, 321555, 319633, 317997, 322741, 322577, 317875, 316488, 317314, 321076, 319015, 317747, 317842, 319335, 318698, 320400, 321504, 322111, 317017, 322125, 321007, 321010, 321518, 320482, 316514, 316536, 317922, 316405, 320254, 322049, 321619, 323149, 322496, 320730, 322918, 317249, 322137, 322089, 322015, 321796, 318041, 319386, 316544, 317434, 321819, 322514, 320094, 322195, 317044, 322753]
syscall.Syscall6(0x2e83eaf4?, 0xc0036c9b50?, 0x12bb405?, 0x3f20f3?, 0xc0036c9c00?, 0x12bb337?, 0xc002305300?, 0x2?)
        runtime/syscall_windows.go:463 +0x38
syscall.readFile(0x2eb4, {0xc003900000?, 0x10000, 0xc?}, 0xa0?, 0x800000?)
        syscall/zsyscall_windows.go:1020 +0x8b
syscall.ReadFile(...)
        syscall/syscall_windows.go:453
syscall.Read(0xc00164cfc8?, {0xc003900000?, 0x12bffe5?, 0xc007c132c0?})
        syscall/syscall_windows.go:432 +0x2d
internal/poll.(*FD).Read(0xc00164cfc8, {0xc003900000, 0x10000, 0x10000})
        internal/poll/fd_windows.go:424 +0x1b5
os.(*File).read(...)
        os/file_posix.go:29
os.(*File).Read(0xc001f44c08, {0xc003900000?, 0x0?, 0x0?})
        os/file.go:124 +0x4f
bufio.(*Reader).fill(0xc0036c9f00)
        bufio/bufio.go:113 +0x103
bufio.(*Reader).ReadSlice(0xc0036c9f00, 0xa)
        bufio/bufio.go:380 +0x29
bufio.(*Reader).ReadLine(0xc0036c9f00)
        bufio/bufio.go:409 +0x25
github.com/hashicorp/go-plugin.(*Client).logStderr(0xc000ce4900, {0xc0005a0168?, 0xc00575bfd0?}, {0x437e900, 0xc001f44c08})
        github.com/hashicorp/go-plugin@v1.6.2/client.go:1172 +0x27d
created by github.com/hashicorp/go-plugin.(*Client).Start in goroutine 319162
        github.com/hashicorp/go-plugin@v1.6.2/client.go:761 +0x1ad1
```

When we look at the CPU profiles, we see we're burning almost all our CPU time on these blocking syscall goroutines.

![Image](https://github.com/user-attachments/assets/6a8369a1-3de6-43a7-b241-3066eb3a5566)

If we load one of the trace profiles (`go tool trace trace_0003.pprof`) we can see that we've spawned _thousands_ of threads, all of which are waiting on syscalls.

![Image](https://github.com/user-attachments/assets/4b66118a-b246-4c29-ae7d-f6ebd7a40446)

But when we look at the blocking syscall profile, we can see that 98% of the _time spent blocking_ is on a single `GetEnvironmentVariable` syscall (ref [`verify.go#L19-L21`](https://github.com/etcd-io/bbolt/blob/v1.4.0/internal/common/verify.go#L19-L21)) in the bbolt database we use to store client state. This particular call seems like it gets potentially called a lot because it's checked again whenever trying to free pages ([`shared.go#L68`](https://github.com/etcd-io/bbolt/blob/v1.4.0/internal/freelist/shared.go#L68)), which doesn't seem right... but this is only a first pass.

![Image](https://github.com/user-attachments/assets/f139a47e-112d-48a4-aa60-a6300d5b6f30)

**Comment by tgross** [comment]
I spent some time today investigating further and wanted to report what I've found so far. I've put together a test environment setup that reproduces the environment that generated the profiles I discussed above. This is a Windows 2022 host on an AWS `t3.xlarge` EC2 instance, with the following job spec.

<details><summary>jobspec</summary>

```hcl
job "example" {

  group "group" {

    # adjusted each step
    count = 80

    network {
      mode = "none"
    }

    ephemeral_disk {
      size = 10
    }

    task "task" {

      driver = "raw_exec"

      config {
        command = "Powershell.exe"
        args    = ["sleep", "10000"]
      }

      logs {
        max_files     = 1
        max_file_size = 1
        disabled      = false
      }

      resources {
        cpu    = 50
        memory = 50
      }

    }
  }
}
```

</details>

I ran this job spec in 10 alloc increments. What I noticed is that during the deployment, the CPU on the host spikes to ~100%. Once the deployment completes, the CPU settles back down (but is still higher than I'd like to see). I then took 30s goroutine, CPU profile, and trace profiles after the deployment completes to get a steady state. Although the trace profile does show lots of threads waiting on syscalls, the CPU profile looks normal in this state rather than matching the profiles I discussed above.

When I ran the profiles _during_ the deployment, I did see the same patterns discussed above: the CPU profile is spending all its time waiting on syscalls. Also during this time, I found that anti-virus on the host was eating about 50% of the CPU. Which is an interesting data point, for sure.

So then I ran a second set of profiles during a deployment, with realtime antivirus protection turned off. The CPU profiles were the same and there was still a large spike in CPU load, but the deployment took roughly half the time to complete (~30s vs ~60s). I ran this a few times to make sure this wasn't just a fluke and it was consistently half the time.

Even in steady state, this still feels like we're running the CPU up way too much. But I'll pick that up tomorrow.

**Comment by tgross** [comment]
I've just opened https://github.com/hashicorp/nomad/pull/25870 with the fix for this. The problem was in the executor's stats-gathering code. We have a short-lived cache in the executor to ensure we don't try to get metrics excessively. In the various refactorings of this code as part of the NUMA aware scheduling feature, we accidentally broke that cache and weren't setting the TTL properly. This meant the cache was always being treated as expired. With that fix in place, the CPU usage for my tests fell back to the pre-1.6.4 level. And we can see that the CPU samples for the executor processes are much closer to the original as well:

![Image](https://github.com/user-attachments/assets/45ecf396-68e6-4904-a0b4-dde8f3d92e16)

While I was looking at this, I discovered that [`telemetry.public_allocation_metrics`](https://developer.hashicorp.com/nomad/docs/configuration/telemetry#publish_allocation_metrics) wasn't being respected in the taskrunner. So while we weren't _publishing_ the stats, we were still _collecting_ the stats, which turns out to be expensive. I've fixed that in the same PR.

This will ship in the regular patch release of Nomad, with backports for Nomad Enterprise. In the meantime, you can reduce the impact of this issue by tuning the [`telemetry.collection_interval`](https://developer.hashicorp.com/nomad/docs/configuration/telemetry#collection_interval) configuration for your client nodes.
