### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference 

### ISSUE THREAD

**Issue by avinashkumar1289** [hashicorp/nomad#24271]
### Nomad version
Output from `nomad version`
nomad version
Nomad v1.7.12+ent
BuildDate 2024-09-17T20:49:17Z
Revision d300cbff7a044c070b667869f3a35a5d6fbfb934

### Operating system and Environment details
Nomad client version 0.11.3
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.7 LTS
Release:	16.04

### Issue
We have job that is running on nomad client version 0.11.3 and server 1.3.16+ent . We are upgrading nomad servers from 1.3.16+ent to 1.7.12+ent but that specific job still needs to be run on 0.11.3. 
After upgrading the server and the clients to 1.7.12+ent we started seeing these error while running the job in the older node 0.11.3
```
worker.service_sched: processing eval panicked scheduler - please report this as a bug!
  eval_id=2fe9741d-2ff3-b7ed-befb-ea448ac85dbf
  job_id=dilithium 
  namespace=default 
  worker_id=f3d38b79-fef4-1d91-d5ec-d740d7d5f79d
  eval_id=2fe9741d-2ff3-b7ed-befb-ea448ac85dbf
  error="runtime error: invalid memory address or nil pointer dereference"

Stack trace:
  | goroutine 161 [running]:
  | runtime/debug.Stack()
  |     runtime/debug/stack.go:24 +0x5e
  | github.com/hashicorp/nomad/scheduler.(*GenericScheduler).Process.func1()
  |     github.com/hashicorp/nomad/scheduler/generic_sched.go:153 +0x58
  | panic({0x2e201a0?, 0x574eba0?})
  |     runtime/panic.go:770 +0x132
  | github.com/hashicorp/nomad/client/lib/numalib.(*Topology).UsableCores(...)
  |     github.com/hashicorp/nomad/client/lib/numalib/topology.go:284
  | github.com/hashicorp/nomad/nomad/structs.(*NodeResources).Comparable(0xc036dee820)
  |     github.com/hashicorp/nomad/nomad/structs/structs.go:3190 +0xcc
  | github.com/hashicorp/nomad/scheduler.(*Preemptor).SetNode(0xc04a452be0, 0xc00285bc80)
  |     github.com/hashicorp/nomad/scheduler/preemption.go:139 +0x36
  | github.com/hashicorp/nomad/scheduler.(*BinPackIterator).Next(0xc122534a10)
  |     github.com/hashicorp/nomad/scheduler/rank.go:274 +0x745
  | github.com/hashicorp/nomad/scheduler.(*JobAntiAffinityIterator).Next(0xc122754af0)
  |     github.com/hashicorp/nomad/scheduler/rank.go:626 +0x6b
  | github.com/hashicorp/nomad/scheduler.(*NodeReschedulingPenaltyIterator).Next(0xc122735b30)
  |     github.com/hashicorp/nomad/scheduler/rank.go:687 +0x28
  | github.com/hashicorp/nomad/scheduler.(*NodeAffinityIterator).Next(0xc122754b40)
  |     github.com/hashicorp/nomad/scheduler/rank.go:759 +0x30
  | github.com/hashicorp/nomad/scheduler.(*SpreadIterator).Next(0xc122534a80)
  |     github.com/hashicorp/nomad/scheduler/spread.go:131 +0x33
  | github.com/hashicorp/nomad/scheduler.(*PreemptionScoringIterator).Next(0xc11aa30f00)
  |     github.com/hashicorp/nomad/scheduler/rank.go:854 +0x28
  | github.com/hashicorp/nomad/scheduler.(*ScoreNormalizationIterator).Next(0xc11aa30f20)
  |     github.com/hashicorp/nomad/scheduler/rank.go:818 +0x28
  | github.com/hashicorp/nomad/scheduler.(*LimitIterator).nextOption(0xc1222ffb60)
  |     github.com/hashicorp/nomad/scheduler/select.go:63 +0x24
  | github.com/hashicorp/nomad/scheduler.(*LimitIterator).Next(0xc1222ffb60)
  |     github.com/hashicorp/nomad/scheduler/select.go:42 +0x26
  | github.com/hashicorp/nomad/scheduler.(*MaxScoreIterator).Next(0xc122735bc0)
  |     github.com/hashicorp/nomad/scheduler/select.go:105 +0x3e
  | github.com/hashicorp/nomad/scheduler.(*GenericStack).Select(0xc122021ad0, 0xc0017e67e0, 0xc04a453570)
  |     github.com/hashicorp/nomad/scheduler/stack.go:192 +0xe97
  | github.com/hashicorp/nomad/scheduler.(*GenericScheduler).selectNextOption(0xc0d8416160, 0xc0017e67e0, 0xc04a453570)
  |     github.com/hashicorp/nomad/scheduler/generic_sched.go:918 +0x2d
  | github.com/hashicorp/nomad/scheduler.(*GenericScheduler).computePlacements(0xc0d8416160, {0x5aba9a0, 0x0, 0x0}, {0xc122744990, 0x1, 0x1}, 0xc12275c2d0)
  |     github.com/hashicorp/nomad/scheduler/generic_sched.go:602 +0xa67
  | github.com/hashicorp/nomad/scheduler.(*GenericScheduler).computeJobAllocs(0xc0d8416160)
  |     github.com/hashicorp/nomad/scheduler/generic_sched.go:469 +0x145a
  | github.com/hashicorp/nomad/scheduler.(*GenericScheduler).process(0xc0d8416160)
  |     github.com/hashicorp/nomad/scheduler/generic_sched.go:289 +0x465
  | github.com/hashicorp/nomad/scheduler.retryMax(0x5, 0xc04a453d78, 0xc04a453ce8)
  |     github.com/hashicorp/nomad/scheduler/util.go:96 +0x49
  | github.com/hashicorp/nomad/scheduler.(*GenericScheduler).Process(0xc0d8416160, 0xc0d4d96000)
  |     github.com/hashicorp/nomad/scheduler/generic_sched.go:188 +0x53f
  | github.com/hashicorp/nomad/nomad.(*Worker).invokeScheduler(0xc000ee56c0, 0xc122735680, 0xc0d4d96000, {0xc122758690, 0x24})
  |     github.com/hashicorp/nomad/nomad/worker.go:634 +0x33b
  | github.com/hashicorp/nomad/nomad.(*Worker).run(0xc000ee56c0, 0x12a05f200)
  |     github.com/hashicorp/nomad/nomad/worker.go:463 +0x585
  | created by github.com/hashicorp/nomad/nomad.(*Worker).Start in goroutine 1
  |     github.com/hashicorp/nomad/nomad/worker.go:162 +0x59

2024-10-21T04:31:08-07:00 nomad[6860]: 
worker: error invoking scheduler: 
  worker_id=6734ffa0-2a9e-5794-91d4-3851b6c1aa7b 
  error="failed to process evaluation: failed to process eval: runtime error: invalid memory address or nil pointer dereference"
```

#### Expected Result
The job allocation should have been successful 

#### Actual Result
Job plan fails with the error
```
nomad_plan ERROR stderr: b'Error during plan: Unexpected response code: 500 (rpc error: failed to process eval: runtime error: invalid memory address or nil pointer dereference)\n'

```

**Comment by tgross** [comment]
Hi @avinashkumar1289! I see your team has an open Enterprise support issue for this issue (internal link: https://hashicorp.zendesk.com/agent/tickets/164794). Nomad 0.11.3 is long out of support, as is 1.3.16, and the stack trace you've posted doesn't line up with the scheduler source code I see for the 1.7.12+ent tag.

It's not clear to me that panicking isn't the correct behavior here. The server can't make sense of a node that's this old, so continuing as if it did may be the wrong thing to do. But in any case nothing here is going to be useful for our community members to participate in, so I'm going to close this GitHub issue and the Support folks will continue with you in the Zendesk ticket.
