### ISSUE TITLE
Failing periodic job remains in running state

### ISSUE THREAD

**Issue by wannabesrevenge** [hashicorp/nomad#2540]
### Nomad version
Nomad v0.5.4

### Operating system and Environment details
Ubuntu 16.04

### Issue
A periodic job that always fails does not leave the running state.

When a job fails, it looks like a retries a number of times. At a certain point, the script stops retrying. After it stops retrying, the job remains in the running state. If you are using `prohibit_overlap = true`, then your periodic job will not run again.

This is probably because I'm new to Nomad, but a couple things here:
- A job should not retry unless I explicitly tell it to for a batch job
- A job that fails (after all tries), should get marked as "failed", or at the very least "dead"

### Reproduction steps
Put the python script in /home/ubuntu directory. Run the job file. Wait for some time.

### Nomad Server logs (if appropriate)
Job STDOUT
```
2017-04-10 15:02:00.315560
2017-04-10 15:02:18.698926
2017-04-10 15:02:35.375005
2017-04-10 15:02:52.955405
2017-04-10 15:03:08.275452
2017-04-10 15:03:25.385175
2017-04-10 15:03:44.718670
2017-04-10 15:04:01.620121
2017-04-10 15:04:18.742090
2017-04-10 15:04:33.910549
2017-04-10 15:04:50.910466
2017-04-10 15:05:09.719748
2017-04-10 15:05:25.279390
2017-04-10 15:05:40.888189
2017-04-10 15:05:58.513177
2017-04-10 15:06:17.162296
```

Job STDERR
```
Traceback (most recent call last):
  File "/home/ubuntu/fail.py", line 6, in <module>
    raise Exception('Fake failed at {}'.format(now))
Exception: Fake failed at 2017-04-10 15:02:00.315560
Traceback (most recent call last):
  File "/home/ubuntu/fail.py", line 6, in <module>
    raise Exception('Fake failed at {}'.format(now))
Exception: Fake failed at 2017-04-10 15:02:18.698926
Traceback (most recent call last):
  File "/home/ubuntu/fail.py", line 6, in <module>
    raise Exception('Fake failed at {}'.format(now))
Exception: Fake failed at 2017-04-10 15:02:35.375005
Traceback (most recent call last):
  File "/home/ubuntu/fail.py", line 6, in <module>
    raise Exception('Fake failed at {}'.format(now))
Exception: Fake failed at 2017-04-10 15:02:52.955405
Traceback (most recent call last):
  File "/home/ubuntu/fail.py", line 6, in <module>
    raise Exception('Fake failed at {}'.format(now))
Exception: Fake failed at 2017-04-10 15:03:08.275452
Traceback (most recent call last):
  File "/home/ubuntu/fail.py", line 6, in <module>
    raise Exception('Fake failed at {}'.format(now))
Exception: Fake failed at 2017-04-10 15:03:25.385175
Traceback (most recent call last):
  File "/home/ubuntu/fail.py", line 6, in <module>
    raise Exception('Fake failed at {}'.format(now))
Exception: Fake failed at 2017-04-10 15:03:44.718670
Traceback (most recent call last):
  File "/home/ubuntu/fail.py", line 6, in <module>
    raise Exception('Fake failed at {}'.format(now))
Exception: Fake failed at 2017-04-10 15:04:01.620121
Traceback (most recent call last):
  File "/home/ubuntu/fail.py", line 6, in <module>
    raise Exception('Fake failed at {}'.format(now))
Exception: Fake failed at 2017-04-10 15:04:18.742090
Traceback (most recent call last):
  File "/home/ubuntu/fail.py", line 6, in <module>
    raise Exception('Fake failed at {}'.format(now))
Exception: Fake failed at 2017-04-10 15:04:33.910549
Traceback (most recent call last):
  File "/home/ubuntu/fail.py", line 6, in <module>
    raise Exception('Fake failed at {}'.format(now))
Exception: Fake failed at 2017-04-10 15:04:50.910466
Traceback (most recent call last):
  File "/home/ubuntu/fail.py", line 6, in <module>
    raise Exception('Fake failed at {}'.format(now))
Exception: Fake failed at 2017-04-10 15:05:09.719748
Traceback (most recent call last):
  File "/home/ubuntu/fail.py", line 6, in <module>
    raise Exception('Fake failed at {}'.format(now))
Exception: Fake failed at 2017-04-10 15:05:25.279390
Traceback (most recent call last):
  File "/home/ubuntu/fail.py", line 6, in <module>
    raise Exception('Fake failed at {}'.format(now))
Exception: Fake failed at 2017-04-10 15:05:40.888189
Traceback (most recent call last):
  File "/home/ubuntu/fail.py", line 6, in <module>
    raise Exception('Fake failed at {}'.format(now))
Exception: Fake failed at 2017-04-10 15:05:58.513177
Traceback (most recent call last):
  File "/home/ubuntu/fail.py", line 6, in <module>
    raise Exception('Fake failed at {}'.format(now))
Exception: Fake failed at 2017-04-10 15:06:17.162296
```

### Job Status
```
/home/ubuntu# nomad status fail-job
ID                   = fail-job
Name                 = fail-job
Type                 = batch
Priority             = 50
Datacenters          = dc1
Status               = running
Periodic             = true
Parameterized        = false
Next Periodic Launch = 04/10/17 16:00:00 UTC (42s from now)

Children Job Summary
Pending  Running  Dead
0        1        0

Previously Launched Jobs
ID                            Status
fail-job/periodic-1491836520  running
```

### Job file fail.nomad
```
job "fail-job" {
  datacenters = ["dc1"]
  type = "batch"

  periodic {
    # Every minute
    cron = "* * * * *"
    prohibit_overlap = true
  }

  group "failer" {
    task "fails" {
      driver = "raw_exec"

      config {
        command = "python3"
        args = ["/home/ubuntu/fail.py"]
      }
    }
  }
}
```

### Python script fail.py
```
import datetime

now = datetime.datetime.now()
print(now)

raise Exception('Fake failed at {}'.format(now))
```

**Comment by dadgar** [comment]
Hey if you just run `nomad inspect <job-name>` you will see that the job has a default restart policy applied. If you would like to override it specify the restart policy at the group level: https://www.nomadproject.io/docs/job-specification/restart.html

When a job exceeds its restart policy and fails the job will transition to dead.

**Comment by wannabesrevenge** [comment]
Thanks for the info on the restart policy, but I still have a problem with the state transition. My jobs are not transitioning to dead even after the 15 retries. This is a status output from the same job above:

```
nomad status fail-job
ID                   = fail-job
Name                 = fail-job
Type                 = batch
Priority             = 50
Datacenters          = dc1
Status               = running
Periodic             = true
Parameterized        = false
Next Periodic Launch = 04/10/17 17:31:00 UTC (35s from now)

Children Job Summary
Pending  Running  Dead
0        1        0

Previously Launched Jobs
ID                            Status
fail-job/periodic-1491836520  running
```

It's been 2 and a half hours since the final retry failed, and the job is still marked as running.

**Comment by dadgar** [comment]
Hey I just ran a test:
```
$ nomad status fail-job/p
ID            = fail-job/periodic-1491847860
Name          = fail-job/periodic-1491847860
Type          = batch
Priority      = 50
Datacenters   = dc1
Status        = running
Periodic      = false
Parameterized = false

Summary
Task Group  Queued  Starting  Running  Failed  Complete  Lost
failer      0       1         0        0       0         0

Allocations
ID        Eval ID   Node ID   Task Group  Desired  Status   Created At
08710b68  d07bf35b  564d83f1  failer      run      pending  04/10/17 18:11:00 UTC

$ nomad alloc-status 08
ID                  = 08710b68
Eval ID             = d07bf35b
Name                = fail-job/periodic-1491847860.failer[0]
Node ID             = 564d83f1
Job ID              = fail-job/periodic-1491847860
Client Status       = failed
Client Description  = <none>
Desired Status      = run
Desired Description = <none>
Created At          = 04/10/17 18:11:00 UTC

Task "fails" is "dead"
Task Resources
CPU      Memory  Disk     IOPS  Addresses
100 MHz  10 MiB  300 MiB  0

Recent Events:
Time                   Type            Description
04/10/17 18:11:25 UTC  Not Restarting  Exceeded allowed attempts 2 in interval 1m0s and mode is "fail"
04/10/17 18:11:25 UTC  Terminated      Exit Code: 1
04/10/17 18:11:25 UTC  Started         Task started by client
04/10/17 18:11:13 UTC  Restarting      Task restarting in 12.369198747s
04/10/17 18:11:13 UTC  Terminated      Exit Code: 1
04/10/17 18:11:13 UTC  Started         Task started by client
04/10/17 18:11:01 UTC  Restarting      Task restarting in 11.023474345s
04/10/17 18:11:01 UTC  Terminated      Exit Code: 1
04/10/17 18:11:00 UTC  Started         Task started by client
04/10/17 18:11:00 UTC  Task Setup      Building Task Directory

$ nomad status fail-job/p
ID            = fail-job/periodic-1491847860
Name          = fail-job/periodic-1491847860
Type          = batch
Priority      = 50
Datacenters   = dc1
Status        = dead
Periodic      = false
Parameterized = false

Summary
Task Group  Queued  Starting  Running  Failed  Complete  Lost
failer      0       0         0        1       0         0

Allocations
ID        Eval ID   Node ID   Task Group  Desired  Status  Created At
08710b68  d07bf35b  564d83f1  failer      run      failed  04/10/17 18:11:00 UTC

$ nomad status fail-job
ID                   = fail-job
Name                 = fail-job
Type                 = batch
Priority             = 50
Datacenters          = dc1
Status               = running
Periodic             = true
Parameterized        = false
Next Periodic Launch = 04/10/17 18:12:00 UTC (17s from now)

Children Job Summary
Pending  Running  Dead
0        0        1

Previously Launched Jobs
ID                            Status
fail-job/periodic-1491847860  dead
```

The job was modified to have a shorter policy:
```
job "fail-job" {
  datacenters = ["dc1"]
  type        = "batch"

  periodic {
    # Every minute
    cron             = "* * * * *"
    prohibit_overlap = true
  }

  group "failer" {
    restart {
      mode = "fail"
      interval = "1m"
      attempts = 2
      delay = "10s"
    }
    task "fails" {
      driver = "raw_exec"

      config {
        command = "python3"
        args    = ["local/fail.py"]
      }

      template {
        data = <<EOF
import datetime

now = datetime.datetime.now()
print(now)

raise Exception('Fake failed at {}'.format(now))
        EOF

        destination = "local/fail.py"
      }
    }
  }
}
```

This was on 0.5.6 and it is working.

**Comment by wannabesrevenge** [comment]
Awesome! Thanks you!
