### ISSUE TITLE
0.6.0-rc1: Nomad client failure after Docker timeout

### ISSUE THREAD

**Issue by rlenk** [hashicorp/nomad#2835]
### Nomad version
Nomad v0.6.0-rc1 (5187fcfcae50e3dee61e5340eb99805a564b55c3+CHANGES)

### Operating system and Environment details

CentOS 7.3.1611
Docker 17.03.2-ce
Consul v0.8.5

### Issue
Nomad client fails after a number of timed out calls to Docker.

### Nomad Client logs (if appropriate)
```
2017/07/13 22:25:37.902462 [ERR] driver.docker: error removing container: Delete http://unix.sock/containers/915f3abe9950f62ff16c0cd8c376950fff1f8e50038bbd31c867e4783b511d79?force=1&v=1: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2017/07/13 22:25:37.902624 [INFO] client: task "adpodref-casreader" for alloc "176e696f-22fa-c11b-bef8-2630c61bac1c" completed successfully
2017/07/13 22:25:37.902641 [INFO] client: Not restarting task: adpodref-casreader for alloc: 176e696f-22fa-c11b-bef8-2630c61bac1c
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xbbc0fa]
goroutine 301730 [running]:
github.com/hashicorp/nomad/client/driver.(*DockerDriver).Start(0xc424e52240, 0xc4284c2350, 0xc4247b7960, 0xc428161fe0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/nomad/client/driver/docker.go:600 +0x130a
github.com/hashicorp/nomad/client.(*TaskRunner).startTask(0xc42627f200, 0xc4250600c0, 0x0)
	/opt/gopath/src/github.com/hashicorp/nomad/client/task_runner.go:1344 +0x56c
github.com/hashicorp/nomad/client.(*TaskRunner).run(0xc42627f200)
	/opt/gopath/src/github.com/hashicorp/nomad/client/task_runner.go:1031 +0x334
github.com/hashicorp/nomad/client.(*TaskRunner).Run(0xc42627f200)
	/opt/gopath/src/github.com/hashicorp/nomad/client/task_runner.go:561 +0x507
created by github.com/hashicorp/nomad/client.(*AllocRunner).Run
	/opt/gopath/src/github.com/hashicorp/nomad/client/alloc_runner.go:746 +0xbab
```

**Comment by dadgar** [comment]
@rlenk Thanks for the report! Any reproduction steps, did you stop the docker engine?

**Comment by rlenk** [comment]
No specific steps to reproduce on this one either, except that it happened sometime after the Docker engine became unresponsive; `docker ps` and other commands timed out as well. It might be possible to reproduce by sending the Docker engine a `SIGSTOP`, I will try this afternoon.

**Comment by shantanugadgil** [comment]
@rlenk  just a minor nitpick, CentOS 7 has Docker CE 17.06 as latest stable.

Cheers,
Shantanu

**Comment by schmichael** [comment]
No need for repro steps; this is the same sort of bug as #2802. Will get a PR up and audit docker.go for similar lines.

Thanks @rlenk!
