### ISSUE TITLE
Unable to start nomad on raspberry pi (linux/arm)

### ISSUE THREAD

**Issue by stahnma** [hashicorp/nomad#2971]
If filing a bug please include the following:

### Nomad version
Nomad v0.6.0

### Operating system and Environment details
CentOS Linux release 7.3.1611 (Core) 
on ARM (Raspberry Pi 3)

### Issue
```
/usr/local/bin/nomad agent -config /etc/nomad
    Loaded configuration from /etc/nomad/server.hcl
==> Starting Nomad agent...
==> Nomad agent configuration:

                Client: false
             Log Level: INFO
                Region: global (DC: dc1)
                Server: true
               Version: 0.6.0

==> Nomad agent started! Log data will stream in below:

    2017/08/04 18:01:29 [INFO] raft: Initial configuration (index=1): [{Suffrage:Voter ID:192.168.1.119:4647 Address:192.168.1.119:4647}]
    2017/08/04 18:01:29 [INFO] raft: Node at 192.168.1.119:4647 [Follower] entering Follower state (Leader: "")
    2017/08/04 18:01:29 [INFO] serf: EventMemberJoin: cordy.global 192.168.1.119
    2017/08/04 18:01:29.163323 [INFO] nomad: starting 4 scheduling worker(s) for [service batch system _core]
    2017/08/04 18:01:29 [WARN] serf: Failed to re-join any previously known node
    2017/08/04 18:01:29.165256 [INFO] nomad: adding server cordy.global (Addr: 192.168.1.119:4647) (DC: dc1)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x11e60]

goroutine 19 [running]:
sync/atomic.storeUint64(0x116861d4, 0x1, 0x0)
	/opt/go/src/sync/atomic/64bit_arm.go:20 +0x3c
github.com/hashicorp/nomad/command/agent/consul.(*ServiceClient).markSeen(0x11686180)
	/opt/gopath/src/github.com/hashicorp/nomad/command/agent/consul/client.go:153 +0x34
github.com/hashicorp/nomad/command/agent/consul.(*ServiceClient).sync(0x11686180, 0x11762f00, 0x11a8776c)
	/opt/gopath/src/github.com/hashicorp/nomad/command/agent/consul/client.go:360 +0x594
github.com/hashicorp/nomad/command/agent/consul.(*ServiceClient).Run(0x11686180)
	/opt/gopath/src/github.com/hashicorp/nomad/command/agent/consul/client.go:177 +0x108
created by github.com/hashicorp/nomad/command/agent.(*Agent).setupConsul
	/opt/gopath/src/github.com/hashicorp/nomad/command/agent/agent.go:718 +0x4a0



```
### Reproduction steps
download nomad 0.6.0
`mkdir -p /etc/nomad /var/lib/nomad`

Place `server.hc`l in `/etc/nomad`

Here's mine:

```
bind_addr = "0.0.0.0"
data_dir = "/var/lib/nomad"

advertise {
  # This should be the IP of THIS MACHINE and must be routable by every node
  # in your cluster
  rpc = "192.168.1.119"
}

server {
  enabled = true
  bootstrap_expect = 3
}
```

### Nomad Server logs (if appropriate)
Logs included above, running in foreground

**Comment by dadgar** [comment]
Hey @stahnma 

Thanks for reporting. Going to close as we have another report of this issue: https://github.com/hashicorp/nomad/issues/2963

Will be fixed in 0.6.1. Sorry you hit this!
