### ISSUE TITLE
[question]In-house app started by nomad, however, exception thrown when trying to connect to localhost:8500

### ISSUE THREAD

**Issue by napolenli** [hashicorp/nomad#3012]
### Nomad version
Nomad v0.5.6

### Operating system and Environment details
CentOS Linux release 7.3.1611 (Core)

### Issue
The exception was thrown, like connection timeout while trying to connect to localhost:8500, however, it is fine to connect to our mongo server through certain port even without specifying of opening that port.

### Reproduction steps
nomad run app.nomad; nomad logs -f app_id

### Nomad Client logs (if appropriate)
com.ecwid.consul.transport.TransportException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8500 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
	at com.ecwid.consul.transport.AbstractHttpTransport.executeRequest(AbstractHttpTransport.java:96)
	at com.ecwid.consul.transport.AbstractHttpTransport.makePutRequest(AbstractHttpTransport.java:62)
	at com.ecwid.consul.v1.ConsulRawClient.makePutRequest(ConsulRawClient.java:88)
	at com.ecwid.consul.v1.agent.AgentConsulClient.agentServiceRegister(AgentConsulClient.java:238)
	at com.ecwid.consul.v1.ConsulClient.agentServiceRegister(ConsulClient.java:277)

### Job file (if appropriate)
Can not provide, but it started, so it worked.

**Comment by napolenli** [comment]
When I started our app without nomad in docker mode, it works, and discovered by consul. @dadgar @mitchellh

**Comment by napolenli** [comment]
My team lead gave me the answer actually, it seems that the I need to pass some args in order to start the container with nomad, --net=host, thanks!
