### ISSUE TITLE
Nomad crash on startup

### ISSUE THREAD

**Issue by jstoja** [hashicorp/nomad#3033]
If filing a bug please include the following:

### Nomad version
`v0.5.6` (downgraded from `v0.6.0`

### Operating system and Environment details
Debian jessie (8.4)

### Issue
When starting nomad after my downgrade, it's crashing just after startup.

### Reproduction steps

1. Run 0.5.6
1. Upgrade to 0.6.0
1. Downgrade to 0.5.6
1. Launch several servers (it doesnt crash as long as it doesn't start to communicate with other nodes)

### Nomad Server logs (if appropriate)
```
Aug 16 10:58:22 lux4 systemd[1]: Started Nomad.
Aug 16 10:58:22 lux4 nomad[8597]: Loaded configuration from /etc/nomad.d/server.hcl
Aug 16 10:58:22 lux4 nomad[8597]: ==> Starting Nomad agent...
Aug 16 10:58:24 lux4 nomad[8597]: panic: failed to apply request: []byte{0xd, 0x85, 0xa5, 0x41, 

[ ... LOT OF HEXA... ]

Aug 16 10:58:24 lux4 nomad[8597]: goroutine 35 [running]:
Aug 16 10:58:24 lux4 nomad[8597]: github.com/hashicorp/nomad/nomad.(*nomadFSM).Apply(0xc4204630e0, 0xc4201c2960, 0x1a94c60, 0xed1261c50)
Aug 16 10:58:24 lux4 nomad[8597]: /opt/gopath/src/github.com/hashicorp/nomad/nomad/fsm.go:161 +0x860
Aug 16 10:58:24 lux4 nomad[8597]: github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft.(*Raft).runFSM.func1(0xc420414360)
Aug 16 10:58:24 lux4 nomad[8597]: /opt/gopath/src/github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft/fsm.go:57 +0x189
Aug 16 10:58:24 lux4 nomad[8597]: github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft.(*Raft).runFSM(0xc4200e62c0)
Aug 16 10:58:24 lux4 nomad[8597]: /opt/gopath/src/github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft/fsm.go:120 +0x2d6
Aug 16 10:58:24 lux4 nomad[8597]: github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft.(*Raft).(github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft.runFSM)-fm()
Aug 16 10:58:24 lux4 nomad[8597]: /opt/gopath/src/github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft/api.go:505 +0x2a
Aug 16 10:58:24 lux4 nomad[8597]: github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc4200e62c0, 0xc4202978c0)
Aug 16 10:58:24 lux4 nomad[8597]: /opt/gopath/src/github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft/state.go:142 +0x53
Aug 16 10:58:24 lux4 nomad[8597]: created by github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft.(*raftState).goFunc
Aug 16 10:58:24 lux4 nomad[8597]: /opt/gopath/src/github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft/state.go:143 +0x66
```

**Comment by jstoja** [comment]
Since my job do not use any ephemeral disks and that I can recreate them quickly I fixed this issue by cleaning the nomad data directory. (I have many warnings on deleted alloc folders but nvm)
If the logs do not interest you, you can close this directly.

**Comment by dadgar** [comment]
@jstoja Unfortunately you can not down grade. There are new commands that are in your Raft log that older versions of Nomad do not know how to handle which is why you are seeing the panic. You will have to clear your cluster if you want to stay on 0.5.6.
