### ISSUE TITLE
panic on arm with local consul enabled

### ISSUE THREAD

**Issue by MorphBonehunter** [hashicorp/nomad#3099]
### Nomad version
`Nomad v0.6.0`

### Operating system and Environment details
Running nomad on Arch Linux ARM
System is ODROID-U3:
```
Architecture:         armv7l
Byte Order:           Little Endian
CPU(s):               4
On-line CPU(s) list:  0,1
Off-line CPU(s) list: 2,3
Thread(s) per core:   1
Core(s) per socket:   2
Socket(s):            1
Model:                0
Model name:           ARMv7 Processor rev 0 (v7l)
CPU max MHz:          2000.0000
CPU min MHz:          200.0000
BogoMIPS:             398.45
Flags:                swp half thumb fastmult vfp edsp thumbee neon vfpv3 tls
```
I'm using precompiled binary from: https://releases.hashicorp.com/nomad/0.6.0/nomad_0.6.0_linux_arm.zip

### Issue
On start of  nomad with running consul on the same system, nomad crashes.
If i stop consul, nomad starts but does crash on shutdown.

### Reproduction steps
1. running consul:
```
nomad agent -dev -log-level=trace
    No configuration files loaded
==> Starting Nomad agent...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x11e60]

goroutine 25 [running]:
sync/atomic.storeUint64(0x116921d4, 0x1, 0x0)
	/opt/go/src/sync/atomic/64bit_arm.go:20 +0x3c
github.com/hashicorp/nomad/command/agent/consul.(*ServiceClient).markSeen(0x11692180)
	/opt/gopath/src/github.com/hashicorp/nomad/command/agent/consul/client.go:153 +0x34
github.com/hashicorp/nomad/command/agent/consul.(*ServiceClient).sync(0x11692180, 0x117072c0, 0x1161b76c)
	/opt/gopath/src/github.com/hashicorp/nomad/command/agent/consul/client.go:360 +0x594
github.com/hashicorp/nomad/command/agent/consul.(*ServiceClient).Run(0x11692180)
	/opt/gopath/src/github.com/hashicorp/nomad/command/agent/consul/client.go:177 +0x108
created by github.com/hashicorp/nomad/command/agent.(*Agent).setupConsul
	/opt/gopath/src/github.com/hashicorp/nomad/command/agent/agent.go:718 +0x4a0
```
2. consul not running:
```
nomad agent -dev -log-level=trace
    No configuration files loaded
==> Starting Nomad agent...
==> Nomad agent configuration:

                Client: true
             Log Level: trace
                Region: global (DC: dc1)
                Server: true
               Version: 0.6.0

==> Nomad agent started! Log data will stream in below:

    2017/08/25 16:10:14 [INFO] raft: Initial configuration (index=1): [{Suffrage:Voter ID:127.0.0.1:4647 Address:127.0.0.1:4647}]
    2017/08/25 16:10:14 [INFO] raft: Node at 127.0.0.1:4647 [Follower] entering Follower state (Leader: "")
    2017/08/25 16:10:14 [INFO] serf: EventMemberJoin: eleanor.global 127.0.0.1
    2017/08/25 16:10:14.616717 [INFO] nomad: starting 2 scheduling worker(s) for [service batch system _core]
    2017/08/25 16:10:14.617152 [INFO] client: using state directory /tmp/NomadClient235873869
    2017/08/25 16:10:14.617276 [INFO] nomad: adding server eleanor.global (Addr: 127.0.0.1:4647) (DC: dc1)
    2017/08/25 16:10:14.617407 [INFO] client: using alloc directory /tmp/NomadClient659805512
    2017/08/25 16:10:14.618069 [WARN] consul.sync: failed to update services in Consul: error querying Consul services: Get http://127.0.0.1:8500/v1/agent/services: dial tcp 127.0.0.1:8500: getsockopt: connection refused
    2017/08/25 16:10:14.618306 [DEBUG] server.nomad: lost contact with Nomad quorum, falling back to Consul for server list
    2017/08/25 16:10:14.618773 [ERR] consul: error looking up Nomad servers: server.nomad: unable to query Consul datacenters: Get http://127.0.0.1:8500/v1/catalog/datacenters: dial tcp 127.0.0.1:8500: getsockopt: connection refused    2017/08/25 16:10:18.672814 [INFO] client: node registration complete
    2017/08/25 16:10:14.623893 [DEBUG] client: built-in fingerprints: [arch cgroup consul cpu host memory network nomad signal storage vault env_aws env_gce]
    2017/08/25 16:10:14.624295 [INFO] fingerprint.cgroups: cgroups are available
    2017/08/25 16:10:14.624469 [DEBUG] client: fingerprinting cgroup every 15s
    2017/08/25 16:10:14.625233 [DEBUG] client: fingerprinting consul every 15s
    2017/08/25 16:10:14.625692 [DEBUG] fingerprint.cpu: frequency: 2000 MHz
    2017/08/25 16:10:14.625712 [DEBUG] fingerprint.cpu: core count: 2
    2017/08/25 16:10:14.638540 [WARN] fingerprint.network: Unable to parse Speed in output of '/usr/bin/ethtool lo'
    2017/08/25 16:10:14.638758 [DEBUG] fingerprint.network: Unable to read link speed from /sys/class/net/lo/speed
    2017/08/25 16:10:14.638800 [DEBUG] fingerprint.network: link speed could not be detected and no speed specified by user. Defaulting to 1000
    2017/08/25 16:10:14.639148 [DEBUG] fingerprint.network: Detected interface lo with IP: 127.0.0.1
    2017/08/25 16:10:14.639190 [DEBUG] fingerprint.network: Detected interface lo with IP: ::1
    2017/08/25 16:10:14.644327 [DEBUG] client: fingerprinting vault every 15s
    2017/08/25 16:10:15 [WARN] raft: Heartbeat timeout from "" reached, starting election
    2017/08/25 16:10:15 [INFO] raft: Node at 127.0.0.1:4647 [Candidate] entering Candidate state in term 2
    2017/08/25 16:10:15 [DEBUG] raft: Votes needed: 1
    2017/08/25 16:10:15 [DEBUG] raft: Vote granted from 127.0.0.1:4647 in term 2. Tally: 1
    2017/08/25 16:10:15 [INFO] raft: Election won. Tally: 1
    2017/08/25 16:10:15 [INFO] raft: Node at 127.0.0.1:4647 [Leader] entering Leader state
    2017/08/25 16:10:15.958541 [INFO] nomad: cluster leadership acquired
    2017/08/25 16:10:15.962520 [DEBUG] leader: reconciling job summaries at index: 0
    2017/08/25 16:10:16.644950 [DEBUG] fingerprint.env_aws: Error querying AWS Metadata URL, skipping
    2017/08/25 16:10:18.646879 [DEBUG] fingerprint.env_gce: Could not read value for attribute "machine-type"
    2017/08/25 16:10:18.647000 [DEBUG] fingerprint.env_gce: Error querying GCE Metadata URL, skipping
    2017/08/25 16:10:18.647314 [DEBUG] client: applied fingerprints [arch cgroup cpu host memory network nomad signal storage]
    2017/08/25 16:10:18.647661 [DEBUG] driver.exec: exec driver is enabled
    2017/08/25 16:10:18.648255 [WARN] driver.raw_exec: raw exec is enabled. Only enable if needed
    2017/08/25 16:10:18.648607 [DEBUG] client: fingerprinting exec every 15s
    2017/08/25 16:10:18.650455 [DEBUG] driver.docker: using client connection initialized from environment
    2017/08/25 16:10:18.650769 [DEBUG] client: fingerprinting rkt every 15s
    2017/08/25 16:10:18.653520 [DEBUG] driver.docker: could not connect to docker daemon at unix:///var/run/docker.sock: Get http://unix.sock/version: dial unix /var/run/docker.sock: connect: no such file or directory
    2017/08/25 16:10:18.653907 [DEBUG] client: available drivers [exec raw_exec]
    2017/08/25 16:10:18.654234 [DEBUG] client: fingerprinting docker every 15s
    2017/08/25 16:10:18.655757 [INFO] client: Node ID "436420ab-23f7-0a23-81a6-e0bde8b23061"
    2017/08/25 16:10:18.658251 [ERR] client.consul: error discovering nomad servers: client.consul: unable to query Consul datacenters: Get http://127.0.0.1:8500/v1/catalog/datacenters: dial tcp 127.0.0.1:8500: getsockopt: connection refused
    2017/08/25 16:10:18.665780 [DEBUG] client: updated allocations at index 1 (total 0) (pulled 0) (filtered 0)
    2017/08/25 16:10:18.666977 [DEBUG] client: allocs: (added 0) (removed 0) (updated 0) (ignore 0)

    2017/08/25 16:10:18.684198 [DEBUG] client: periodically checking for node changes at duration 5s
    2017/08/25 16:10:18.691114 [DEBUG] client: state updated to ready
^C==> Caught signal: interrupt
    2017/08/25 16:10:31.627444 [DEBUG] http: Shutting down http server
    2017/08/25 16:10:31.627900 [INFO] agent: requesting shutdown
    2017/08/25 16:10:31.628241 [INFO] client: shutting down
    2017/08/25 16:10:31.629300 [INFO] nomad: shutting down server
    2017/08/25 16:10:31 [WARN] serf: Shutdown without a Leave
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x11e60]

goroutine 1 [running]:
sync/atomic.loadUint64(0x11616174, 0x761c74, 0xc)
	/opt/go/src/sync/atomic/64bit_arm.go:10 +0x3c
github.com/hashicorp/nomad/command/agent/consul.(*ServiceClient).hasSeen(0x11616120, 0x1182a9c0)
	/opt/gopath/src/github.com/hashicorp/nomad/command/agent/consul/client.go:159 +0x24
github.com/hashicorp/nomad/command/agent/consul.(*ServiceClient).Shutdown(0x11616120, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/nomad/command/agent/consul/client.go:693 +0x130
github.com/hashicorp/nomad/command/agent.(*Agent).Shutdown(0x118ee2c0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/nomad/command/agent/agent.go:648 +0xfc
github.com/hashicorp/nomad/command/agent.(*Command).Run(0x1167f310, 0x116101f0, 0x2, 0x2, 0x1)
	/opt/gopath/src/github.com/hashicorp/nomad/command/agent/command.go:524 +0xacc
github.com/hashicorp/nomad/vendor/github.com/mitchellh/cli.(*CLI).Run(0x11678ea0, 0x11678ea0, 0x29, 0xd61e6c)
	/opt/gopath/src/github.com/hashicorp/nomad/vendor/github.com/mitchellh/cli/cli.go:235 +0x210
main.RunCustom(0x116101e8, 0x3, 0x3, 0x116c4f60, 0x0)
	/opt/gopath/src/github.com/hashicorp/nomad/main.go:53 +0xc68
main.Run(0x116101e8, 0x3, 0x3, 0x116000f0)
	/opt/gopath/src/github.com/hashicorp/nomad/main.go:23 +0x40
main.main()
	/opt/gopath/src/github.com/hashicorp/nomad/main.go:19 +0x64
```

**Comment by angrycub** [comment]
This appears to be the same as issue https://github.com/hashicorp/nomad/issues/2963.  Could you try the binaries attached to that issue and see if it resolves your problem.   I will close this issue; however, if your issue persists, please reply here and we can investigate it further.

**Comment by MorphBonehunter** [comment]
Sorry, i've searched only in open issues so i didn't found #2963.
I can confirm this fix my issue.
Thanks!

**Comment by angrycub** [comment]
Perfect!  Thanks for letting us know
