### ISSUE TITLE
[possible msgpack bug?] mixed width cluster overflow flap

### ISSUE THREAD

**Issue by automaticgiant** [hashicorp/nomad#3585]
### Nomad version
Output from `nomad version`
0.7.0

### Operating system and Environment details
one i386 (JXVHK31), one amd64 (deadbeef)

### Issue
logs make me think that the nomad expects msgpack ints to be from a width <= its own

### Reproduction steps
not sure yet

### Nomad Server logs (if appropriate)
```
==> /var/lib/nomad/alloc/a8535259-48ae-d33e-8ec6-2bce4d8356cf/alloc/logs/nomad.stdout.1 <==
    Loaded configuration from nomad-server.hcl
==> Starting Nomad agent...
==> Nomad agent configuration:

                Client: false
             Log Level: INFO
                Region: global (DC: dc1)
                Server: true
               Version: 0.7.0

==> Nomad agent started! Log data will stream in below:

    2017/11/26 22:48:53 [INFO] raft: Initial configuration (index=195): [{Suffrage:Voter ID:192.168.1.7:4647 Address:192.168.1.7:4647} {Suffrage:Voter ID:192.168.1.166:24432 Address:192.168.1.166:24432}]
    2017/11/26 22:48:53 [INFO] raft: Node at 192.168.1.166:24432 [Follower] entering Follower state (Leader: "")
    2017/11/26 22:48:53 [INFO] serf: EventMemberJoin: JXVHK31.global 192.168.1.166
    2017/11/26 22:48:53.380086 [INFO] nomad: starting 1 scheduling worker(s) for [service batch system _core]
    2017/11/26 22:48:53 [INFO] serf: Attempting re-join to previously known node: deadbeef.home.automaticgiant.com.global: 192.168.1.7:4648
    2017/11/26 22:48:53.385355 [INFO] nomad: adding server JXVHK31.global (Addr: 192.168.1.166:24432) (DC: dc1)
    2017/11/26 22:48:53.393628 [INFO] agent: Joining cluster...
    2017/11/26 22:48:53 [INFO] serf: EventMemberJoin: deadbeef.home.automaticgiant.com.global 192.168.1.7
    2017/11/26 22:48:53 [WARN] memberlist: Refuting an alive message
    2017/11/26 22:48:53 [INFO] serf: Re-joined to previously known node: deadbeef.home.automaticgiant.com.global: 192.168.1.7:4648
    2017/11/26 22:48:53.416606 [INFO] nomad: adding server deadbeef.home.automaticgiant.com.global (Addr: 192.168.1.7:4647) (DC: dc1)
    2017/11/26 22:48:53.429599 [INFO] agent: Join completed. Synced with 2 initial agents
    2017/11/26 22:48:53.435162 [INFO] server.nomad: successfully contacted 1 Nomad Servers
    2017/11/26 22:48:53 [WARN] raft: Failed to get previous log: 16160 log not found (last: 16157)

==> /var/lib/nomad/alloc/a8535259-48ae-d33e-8ec6-2bce4d8356cf/alloc/logs/nomad.stderr.0 <==
panic: failed to decode request: [pos 1332]: Overflow int value: 4294967295

goroutine 36 [running]:
github.com/hashicorp/nomad/nomad.(*nomadFSM).applyUpsertNode(0x1b731d40, 0x1b724001, 0x641, 0x641, 0x5, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/nomad/nomad/fsm.go:257 +0x2b9
github.com/hashicorp/nomad/nomad.(*nomadFSM).Apply(0x1b731d40, 0x1b81c560, 0x6f1e2dc9, 0x0)
	/opt/gopath/src/github.com/hashicorp/nomad/nomad/fsm.go:190 +0x22d
github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft.(*Raft).runFSM.func1(0x1b808c88)
	/opt/gopath/src/github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft/fsm.go:57 +0x112
github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft.(*Raft).runFSM(0x1b5d0000)
	/opt/gopath/src/github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft/fsm.go:120 +0x255
github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft.(*Raft).(github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft.runFSM)-fm()
	/opt/gopath/src/github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft/api.go:505 +0x20
github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft.(*raftState).goFunc.func1(0x1b5d0000, 0x1b738418)
	/opt/gopath/src/github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft/state.go:146 +0x44
created by github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft.(*raftState).goFunc
	/opt/gopath/src/github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft/state.go:144 +0x54
```

will avoid but can investigate more if compelling

**Comment by dadgar** [comment]
@automaticgiant does this happen more or less immediately when you introduce a mixed architecture server? Also is this only happening on Nomad 0.7?

**Comment by automaticgiant** [comment]
indeed, immediately. also discovered it affects clients.
070 only? maybe - i feel like i had run mixed clients before, but i've only my faulty memory to back that up.

i386 server:
```
    2017/11/27 03:58:42 [ERR] memberlist: Received invalid msgType (3) from=192.168.1.183:34248
    2017/11/27 03:58:51 [ERR] nomad.fsm: looking up node "8810f09b-0152-bd48-3ab8-9deda3224e69" failed: <nil>
    2017/11/27 03:58:57.413388 [ERR] nomad.rpc: RPC error: codec.decoder: Overflow int value: 4294967295 (&{262144 262055 1 0x1b360bd0 3 {0 0} 0x1b879ce0 {0 0} [0 1 0 2 0 0 0 1 0 0 6 46] 0x1b250700 {0 0} [0 0 0 0 0 0 0 1 0 0 0 89] 0x1b250740 {0 0} 0x1b676e80 0x1b676ec0 {0 0 <nil>} {0 0 <nil>}})
```
amd64 client
```
Nov 26 23:00:25 deadbeef.home.automaticgiant.com nomad[11591]: 2017/11/26 23:00:25.690513 [ERR] client: registration failure: 1 error(s) occurred:
Nov 26 23:00:25 deadbeef.home.automaticgiant.com nomad[11591]: * RPC failed to server 192.168.1.220:25330: rpc error: codec.decoder: Overflow int value: 4294967295
```

**Comment by dadgar** [comment]
@automaticgiant Do you by chance have a node with >= 4TB of disk?

**Comment by automaticgiant** [comment]
Hah. No. Lol. Nice try. I'll look at it more this weekend. Got some homelab
work coming up.

On Dec 5, 2017 18:03, "Alex Dadgar" <notifications@github.com> wrote:

@automaticgiant <https://github.com/automaticgiant> Do you by chance have a
node with >= 4TB of disk?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/hashicorp/nomad/issues/3585#issuecomment-349470841>,
or mute
the thread

**Comment by dadgar** [comment]
@automaticgiant Hmm okay I think I know the issue. Hopefully I will be able to get you a build soon to try out!

**Comment by automaticgiant** [comment]
I'll take it. Awesome. Thanks!

**Comment by dadgar** [comment]
@automaticgiant So I have attached a linux AMD64 build that will help me verify what I think is the problem is causing this. Would you mind running this on the client that was causing the issue and pasting the clients log output:

[nomad.zip](https://github.com/hashicorp/nomad/files/1533310/nomad.zip)

**Comment by automaticgiant** [comment]
hmm. yes. that works.
was having trouble reproducing. doesn't happen with a trusty32/64 vagrant pair, or with chromeos amd64 client.
was totally wierding me out that it was just this one box. but yeah. whatever you did seems good. do tell?
(btw, i'm totally gonna keep that Node struct dump to myself to save sanitizing trouble unless you need it)

**Comment by dadgar** [comment]
Hmm all I did was add the logging! Does the one machine still crash with the build I gave you? If it does I will likely need to see the log output

**Comment by automaticgiant** [comment]
i re-checked with plain 0.7.1 and was good to go, so something changed there.
not sure which client version i was using for the vagrant test, but it didn't exhibit with the amd64 chromebook client even though that was 0.7.0 also. so not sure.
thanks anyway!
