### ISSUE TITLE
malformed(?) go-getter source causes panic

### ISSUE THREAD

**Issue by blalor** [hashicorp/nomad#3633]
### Nomad version

    Nomad v0.7.0

### Operating system and Environment details

macOS 10.13.1

### Issue

Something about artifact source in the included jobspec causes the agent to panic when downloading artifacts.

### Reproduction steps

1. `nomad agent -dev`
1. `nomad run path/to/tester.nomad`

The nomad process will panic when the task is started.

### Nomad Server logs (if appropriate)

```
panic: runtime error: index out of range

goroutine 190 [running]:
github.com/hashicorp/nomad/vendor/github.com/hashicorp/go-getter.SubdirGlob(0xc420290fc0, 0x3c, 0xc420290eb7, 0x9, 0x0, 0x1, 0x0, 0x0)
	/Users/adadgar/Projects/go/src/github.com/hashicorp/nomad/vendor/github.com/hashicorp/go-getter/source.go:56 +0x224
github.com/hashicorp/nomad/vendor/github.com/hashicorp/go-getter.(*Client).Get(0xc420432690, 0x0, 0x0)
	/Users/adadgar/Projects/go/src/github.com/hashicorp/nomad/vendor/github.com/hashicorp/go-getter/client.go:309 +0x67e
github.com/hashicorp/nomad/client/getter.GetArtifact(0x58cad80, 0xc4205ea5d0, 0xc4201e5940, 0xc420205100, 0x79, 0x2, 0xc4205ed7b0)
	/Users/adadgar/Projects/go/src/github.com/hashicorp/nomad/client/getter/getter.go:110 +0x265
github.com/hashicorp/nomad/client.(*TaskRunner).prestart(0xc42007dba0, 0xc4200bb2c0, 0xc4204da700, 0xc4204040e0)
	/Users/adadgar/Projects/go/src/github.com/hashicorp/nomad/client/task_runner.go:990 +0x123
created by github.com/hashicorp/nomad/client.(*TaskRunner).run
	/Users/adadgar/Projects/go/src/github.com/hashicorp/nomad/client/task_runner.go:1094 +0x807
```

### Job file (if appropriate)

```hcl
job "tester" {
    datacenters = ["dc1"]

    type = "batch"

    group "tester" {
        task "tester" {
            driver = "raw_exec"
            config {
                command = "/bin/bash"
                args = [
                    "-c", "find . ! -type d",
                ]
            }

            meta {
                ref = "master"
            }

            artifact {
                mode = "dir"
                source = "https://github.com/hashicorp/nomad/archive/${NOMAD_META_ref}.zip//README.md"
                destination = "local/work"
            }
        }
    }
}
```

Discovered while reproducing #3634.

**Comment by blalor** [comment]
If you're not running in `-dev` mode, the task will panic every time the allocation is started.

**Comment by dadgar** [comment]
@blalor Thanks for reporting. I confirmed it panicked in 0.7.0 and is not panicking in 0.7.1. Instead it errors properly:

```
12/08/17 19:03:44 UTC  Failed Artifact Download  failed to download artifact "https://github.com/hashicorp/nomad/archive/${NOMAD_META_ref}.zip//README.md": subdir "README.md" not found
12/08/17 19:03:30 UTC  Downloading Artifacts     Client is downloading artifacts
12/08/17 19:03:30 UTC  Task Setup                Building Task Directory
12/08/17 19:03:30 UTC  Received                  Task received by client
```
