### ISSUE TITLE
panic log not found after server runs out of space 

### ISSUE THREAD

**Issue by dansteen** [hashicorp/nomad#3834]
### Nomad version
Nomad v0.7.1 (0b295d399d00199cfab4621566babd25987ba06e)

### Operating system and Environment details
debian 8

### Issue
Our nomad server recently ran out of disk space, after stopping nomad, fixing the issue, and bringing nomad back up, I get the following on one of our server boxes:

```
root@nomad-02f:/var/nomad# /usr/local/bin/nomad agent --config /etc/nomad.d/nomad_server.hcl
WARNING: keyring exists but -encrypt given, using keyring
    Loaded configuration from /etc/nomad.d/nomad_server.hcl
==> Starting Nomad agent...
panic: log not found

goroutine 1 [running]:
github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft.NewRaft(0xc4201aa750, 0x2037680, 0xc420051740, 0x2041620, 0xc42021a680, 0x203c1
00, 0xc4203db000, 0x2038ac0, 0xc4203db140, 0x2043600, ...)
        /opt/gopath/src/github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft/api.go:491 +0x14ef
github.com/hashicorp/nomad/nomad.(*Server).setupRaft(0xc420378b40, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/nomad/nomad/server.go:958 +0x559
github.com/hashicorp/nomad/nomad.NewServer(0xc4203783c0, 0x2032c80, 0xc42000e120, 0xc4203ae0a0, 0x0, 0x98cb15, 0xc4200e23c0)
        /opt/gopath/src/github.com/hashicorp/nomad/nomad/server.go:289 +0xc30
github.com/hashicorp/nomad/command/agent.(*Agent).setupServer(0xc4202fa100, 0xc4200e2840, 0x0)
        /opt/gopath/src/github.com/hashicorp/nomad/command/agent/agent.go:397 +0x1f6
github.com/hashicorp/nomad/command/agent.NewAgent(0xc420462500, 0x202dd80, 0xc420466ae0, 0xc4203ae280, 0x0, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/nomad/command/agent/agent.go:87 +0x206
github.com/hashicorp/nomad/command/agent.(*Command).setupAgent(0xc420413340, 0xc420462500, 0x202dd80, 0xc420466ae0, 0xc4203ae280, 0xc42049e
380, 0x37)
        /opt/gopath/src/github.com/hashicorp/nomad/command/agent/command.go:364 +0x96
github.com/hashicorp/nomad/command/agent.(*Command).Run(0xc420413340, 0xc4200100e0, 0x2, 0x2, 0x0)
        /opt/gopath/src/github.com/hashicorp/nomad/command/agent/command.go:475 +0x3ea
github.com/hashicorp/nomad/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc4203dd7c0, 0xc4203dd7c0, 0x4a, 0x1648fd0)
        /opt/gopath/src/github.com/hashicorp/nomad/vendor/github.com/mitchellh/cli/cli.go:255 +0x1eb
main.RunCustom(0xc4200100d0, 0x3, 0x3, 0xc42041eb10, 0xc420177f60)
        /opt/gopath/src/github.com/hashicorp/nomad/main.go:61 +0x1806
main.Run(0xc4200100d0, 0x3, 0x3, 0x122d8a6)
        /opt/gopath/src/github.com/hashicorp/nomad/main.go:24 +0x56
main.main()
        /opt/gopath/src/github.com/hashicorp/nomad/main.go:20 +0x63
```

My server config looks like this:

```
bind_addr = "0.0.0.0" # the default
datacenter = "awse"

data_dir  = "/var/nomad"


server {
  enabled          = true
  bootstrap_expect = 3
  encrypt          = "xxxxxx"
  rejoin_after_leave = true
}

# we use prod consul here since the staging nomad server is used to run staging services, but we don't want to have to maintain
# duplicate copies of the the data so we hook it to prod consul.
# stag consul is really just for testing consul.
consul {
  token = "xxxxxxx"
  server_auto_join = "true"
  server_service_name = "nomad-stag"
}

vault {
   enabled = true
   token = "xxxxxxx"
   create_from_role = "nomad-cluster-stag"
   address = "https://xxxxxxx:8200"
   allow_unauthenticated = "true"
}


tls {
  http = true
  rpc  = true
  ca_file = "/etc/ssl/certs/traitify.ca.pem"
  cert_file = "/etc/nomad.d/nomad.cert"
  key_file = "/etc/nomad.d/nomad.key"
}

telemetry {
  datadog_address = "127.0.0.1:8125"
  disable_hostname = "true"
  use_node_name = "false"
  publish_allocation_metrics = "true"
  publish_node_metrics = "true"
}
```

Moving the existing /var/nomad folder out of the way and replacing it with an empty folder resolved the issue.

**Comment by tgross** [comment]
We're doing some issue clean-up and this is from before the big 0.9 refactoring. Panicking on a corrupted log is arguably the correct behavior but if we'll address the details of that in https://github.com/hashicorp/nomad/issues/8097
