### ISSUE TITLE
8.4.0: driver.rkt: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by onlyjob** [hashicorp/nomad#4579]
~~~~
2018/08/14 12:37:55.659102 [DEBUG] driver.rkt: pod "file:///mnt/r/aci/debian10-zoneminder.aci" for task "zoneminder" prepared. (UUID: f7a2d6f5-6db1-44b4-a017-61a30b64f6ec)
2018-08-14T12:37:55.662+1000 [DEBUG] plugin.nomad: panic: runtime error: invalid memory address or nil pointer dereference
2018-08-14T12:37:55.662+1000 [DEBUG] plugin.nomad: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc518a3]
2018-08-14T12:37:55.662+1000 [DEBUG] plugin.nomad:
2018-08-14T12:37:55.662+1000 [DEBUG] plugin.nomad: goroutine 33 [running]:
2018-08-14T12:37:55.662+1000 [DEBUG] plugin.nomad: github.com/hashicorp/nomad/client/driver/executor.(*UniversalExecutor).configureCgroups(0xc42059a000, 0xc4202c93c0, 0x553f3e, 0xc4200cd180)
2018-08-14T12:37:55.662+1000 [DEBUG] plugin.nomad: #011/build/nomad-0.8.4+dfsg/_build/src/github.com/hashicorp/nomad/client/driver/executor/executor_linux.go:132 +0x133
2018-08-14T12:37:55.662+1000 [DEBUG] plugin.nomad: github.com/hashicorp/nomad/client/driver/executor.(*UniversalExecutor).configureIsolation(0xc42059a000, 0xc4204f40a0, 0x28)
2018-08-14T12:37:55.662+1000 [DEBUG] plugin.nomad: #011/build/nomad-0.8.4+dfsg/_build/src/github.com/hashicorp/nomad/client/driver/executor/executor_linux.go:39 +0xd6
2018-08-14T12:37:55.662+1000 [DEBUG] plugin.nomad: github.com/hashicorp/nomad/client/driver/executor.(*UniversalExecutor).LaunchCmd(0xc42059a000, 0xc4204fa7e0, 0x0, 0x18, 0x18)
2018-08-14T12:37:55.662+1000 [DEBUG] plugin.nomad: #011/build/nomad-0.8.4+dfsg/_build/src/github.com/hashicorp/nomad/client/driver/executor/executor.go:250 +0x1f2
2018-08-14T12:37:55.662+1000 [DEBUG] plugin.nomad: github.com/hashicorp/nomad/client/driver.(*ExecutorRPCServer).LaunchCmd(0xc420357cc0, 0xc4204fa7e0, 0xc4202c98c0, 0x0, 0x0)
2018-08-14T12:37:55.662+1000 [DEBUG] plugin.nomad: #011/build/nomad-0.8.4+dfsg/_build/src/github.com/hashicorp/nomad/client/driver/executor_plugin.go:126 +0x41
2018-08-14T12:37:55.662+1000 [DEBUG] plugin.nomad: reflect.Value.call(0xc4204fa2a0, 0xc420582190, 0x13, 0x1af4630, 0x4, 0xc42006ef18, 0x3, 0x3, 0xc420524080, 0x0, ...)
2018-08-14T12:37:55.662+1000 [DEBUG] plugin.nomad: #011/usr/lib/go-1.10/src/reflect/value.go:447 +0x969
2018-08-14T12:37:55.662+1000 [DEBUG] plugin.nomad: reflect.Value.Call(0xc4204fa2a0, 0xc420582190, 0x13, 0xc4204b3718, 0x3, 0x3, 0x0, 0x0, 0x0)
2018-08-14T12:37:55.662+1000 [DEBUG] plugin.nomad: #011/usr/lib/go-1.10/src/reflect/value.go:308 +0xa4
2018-08-14T12:37:55.662+1000 [DEBUG] plugin.nomad: net/rpc.(*service).call(0xc4205240c0, 0xc42050e0a0, 0xc4204f8130, 0xc4204f8140, 0xc4203a4180, 0xc4203b4c40, 0x183e420, 0xc420582928, 0x199, 0x163e7c0, ...)
2018-08-14T12:37:55.662+1000 [DEBUG] plugin.nomad: #011/usr/lib/go-1.10/src/net/rpc/server.go:384 +0x14e
2018-08-14T12:37:55.662+1000 [DEBUG] plugin.nomad: created by net/rpc.(*Server).ServeCodec
2018-08-14T12:37:55.662+1000 [DEBUG] plugin.nomad: #011/usr/lib/go-1.10/src/net/rpc/server.go:480 +0x43a
2018-08-14T12:37:55.665+1000 [DEBUG] plugin: plugin process exited: path=/usr/bin/nomad
2018-08-14T12:37:55.665+1000 [WARN ] plugin: error closing client during Kill: err="stream closed"
2018/08/14 12:37:55.665798 [WARN] client: failed to start task "zoneminder" for alloc "4c01cf9c-79dc-6447-9a73-aa863406da8c": unexpected EOF
~~~~

### Nomad version

Nomad v0.8.4

### Operating system and Environment details

Debian "amd64"; rkt-1.30.0

### Reproduction steps

`nomad job run` with job where `driver = "rkt"`.

**Comment by onlyjob** [comment]
Please disregard this bug report. The problem was caused by my immature patch to build with newer runc... Sorry.
