### ISSUE TITLE
test TestJobStatusCommand_Run panics

### ISSUE THREAD

**Issue by shoenig** [hashicorp/nomad#6799]
Seems like some CLI output got changed, and this test makes an assumption about safely tokenizing that output.
```
allocationsTableName := "Allocations\n"
allocationsTableStr := strings.Split(out, allocationsTableName)[1]
```
```
[mp command (master)] $ git pullf
Already up to date.

[mp command (master)] $ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

[mp command (master)] $ go test -run TestJobStatusCommand_Run
--- FAIL: TestJobStatusCommand_Run (3.31s)
<clipped>
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 50 [running]:
testing.tRunner.func1(0xc0001f0500)
	/usr/local/go/src/testing/testing.go:830 +0x392
panic(0x6494a20, 0x93a28a0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/hashicorp/nomad/command.TestJobStatusCommand_Run(0xc0001f0500)
	/Users/shoenig/Documents/go/src/github.com/hashicorp/nomad/command/job_status_test.go:154 +0x270e
testing.tRunner(0xc0001f0500, 0x6b5e400)
	/usr/local/go/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:916 +0x35a
exit status 2
FAIL	github.com/hashicorp/nomad/command	3.354s
```

**Comment by tgross** [comment]
I haven't been able to reproduce this, but after dumping the `out` contents during a test, it looks like this happens when there are no allocations. That should probably be failing the test much earlier.

At [`command/job_status_test.go#L129-L133`](https://github.com/hashicorp/nomad/blob/34a5a3a6a643306e5a27938a1865c83ecb8c9a59/) we have this bit:

```go
	if allocs, _, err := client.Jobs().Allocations("job2_sfx", false, nil); err == nil {
		if len(allocs) > 0 {
			nodeName = allocs[0].NodeName
		}
	}
```

Maybe we should test for `if len(allocs) == 0` and throw a `t.Fatal` there?
