### ISSUE TITLE
Nomad panic: runtime error, after renaming group

### ISSUE THREAD

**Issue by TheSpbra1n** [hashicorp/nomad#8106]
### Nomad version
Nomad v0.11.0 (5f8fe0afc894d254e4d3baaeaee1c7a70a44fdc6)

### Operating system and Environment details
Codename:	xenial

### Reproduction steps
1. `# nomad run job.hcl`
2. Rename group1 to group2
3. `# nomad run job.hcl`
4. `# nomad stop -purge jobname`

### Job file (if appropriate)
```
# job name
job "jobname" {
  region      = "global"
  datacenters = ["dev"]

  type = "service"

  group "group1" {
    count = 1

    # task
    task "task1" {
      kill_signal = "SIGTERM"
      driver = "docker"

      config {
        image        = "registry/imagename"
        network_mode = "host"
      }

      env {
        API_PORT = 5000
      }
      resources {
        network {
        }
      }
    }
  }
}
```

### Nomad Server logs (if appropriate)
```
Jun 03 21:07:37 docker1 nomad[142776]:     2020-06-03T21:07:37.132+0300 [DEBUG] nomad: memberlist: Stream connection from=[::1]:32326
Jun 03 21:07:43 docker1 nomad[142776]:     2020-06-03T21:07:43.338+0300 [DEBUG] http: request complete: method=PUT path=/v1/jobs?region=global duration=4.328262ms
Jun 03 21:07:43 docker1 nomad[142776]:     2020-06-03T21:07:43.340+0300 [DEBUG] http: request complete: method=GET path=/v1/evaluation/3ea2d35c-e8fd-f478-8dac-b8606818c607?region=global duration=227.242µs
Jun 03 21:07:43 docker1 nomad[142776]:     2020-06-03T21:07:43.341+0300 [DEBUG] http: request complete: method=GET path=/v1/evaluation/3ea2d35c-e8fd-f478-8dac-b8606818c607/allocations?region=global duration=465.996µs
Jun 03 21:07:44 docker1 nomad[142776]:     2020-06-03T21:07:44.343+0300 [DEBUG] http: request complete: method=GET path=/v1/evaluation/3ea2d35c-e8fd-f478-8dac-b8606818c607?region=global duration=280.363µs
Jun 03 21:07:44 docker1 nomad[142776]:     2020-06-03T21:07:44.344+0300 [DEBUG] http: request complete: method=GET path=/v1/evaluation/3ea2d35c-e8fd-f478-8dac-b8606818c607/allocations?region=global duration=418.463µs
Jun 03 21:07:46 docker1 nomad[142776]:     2020-06-03T21:07:46.111+0300 [DEBUG] http: request complete: method=GET path=/v1/agent/health?type=server duration=181.197µs
Jun 03 21:07:47 docker1 nomad[142776]:     2020-06-03T21:07:47.133+0300 [DEBUG] nomad: memberlist: Stream connection from=[::1]:32374
Jun 03 21:07:49 docker1 nomad[142776]:     2020-06-03T21:07:49.362+0300 [DEBUG] http: request complete: method=GET path=/v1/jobs?prefix=jobname duration=318.008µs
Jun 03 21:07:49 docker1 nomad[142776]:     2020-06-03T21:07:49.364+0300 [DEBUG] http: request complete: method=GET path=/v1/job/jobname duration=277.861µs
Jun 03 21:07:49 docker1 nomad[142776]:     2020-06-03T21:07:49.370+0300 [DEBUG] worker: dequeued evaluation: eval_id=1b4c84b4-8a03-baef-cf43-579d67556287
Jun 03 21:07:49 docker1 nomad[142776]:     2020-06-03T21:07:49.370+0300 [DEBUG] http: request complete: method=DELETE path=/v1/job/jobname?purge=false duration=4.328547ms
Jun 03 21:07:49 docker1 nomad[142776]:     2020-06-03T21:07:49.370+0300 [DEBUG] worker.service_sched: reconciled current state with desired state: eval_id=1b4c84b4-8a03-baef-cf43-579d67556287 job_id=jobname namespace=default results="Total changes: (place 0) (destructive 0) (inplace 0) (stop 1)
Jun 03 21:07:49 docker1 nomad[142776]: Deployment Update for ID "4ace3319-8366-14ea-3d1c-e935d75f9f3f": Status "cancelled"; Description "Cancelled because job is stopped"
Jun 03 21:07:49 docker1 nomad[142776]: Desired Changes for "group2": (place 0) (inplace 0) (destructive 0) (stop 1) (migrate 0) (ignore 0) (canary 0)
Jun 03 21:07:49 docker1 nomad[142776]: Desired Changes for "group1": (place 0) (inplace 0) (destructive 0) (stop 0) (migrate 0) (ignore 0) (canary 0)"
Jun 03 21:07:49 docker1 nomad[142776]:     2020-06-03T21:07:49.371+0300 [DEBUG] http: request complete: method=GET path=/v1/evaluation/1b4c84b4-8a03-baef-cf43-579d67556287 duration=212.61µs
Jun 03 21:07:49 docker1 nomad[142776]:     2020-06-03T21:07:49.372+0300 [DEBUG] http: request complete: method=GET path=/v1/evaluation/1b4c84b4-8a03-baef-cf43-579d67556287/allocations duration=193.276µs
Jun 03 21:07:49 docker1 nomad[142776]:     2020-06-03T21:07:49.373+0300 [DEBUG] worker: submitted plan for evaluation: eval_id=1b4c84b4-8a03-baef-cf43-579d67556287
Jun 03 21:07:49 docker1 nomad[142776]:     2020-06-03T21:07:49.373+0300 [DEBUG] worker.service_sched: setting eval status: eval_id=1b4c84b4-8a03-baef-cf43-579d67556287 job_id=jobname namespace=default status=complete
Jun 03 21:07:49 docker1 nomad[142776]:     2020-06-03T21:07:49.374+0300 [DEBUG] worker: updated evaluation: eval="<Eval "1b4c84b4-8a03-baef-cf43-579d67556287" JobID: "jobname" Namespace: "default">"
Jun 03 21:07:49 docker1 nomad[142776]:     2020-06-03T21:07:49.374+0300 [DEBUG] worker: ack evaluation: eval_id=1b4c84b4-8a03-baef-cf43-579d67556287
Jun 03 21:07:49 docker1 nomad[142776]:     2020-06-03T21:07:49.735+0300 [DEBUG] http: request complete: method=GET path=/v1/agent/self duration=927.249µs
Jun 03 21:07:49 docker1 nomad[142776]:     2020-06-03T21:07:49.737+0300 [ERROR] http: request failed: method=GET path=/v1/operator/raft/configuration error="Permission denied" code=403
Jun 03 21:07:49 docker1 nomad[142776]:     2020-06-03T21:07:49.737+0300 [DEBUG] http: request complete: method=GET path=/v1/operator/raft/configuration duration=175.908µs
Jun 03 21:07:50 docker1 nomad[142776]:     2020-06-03T21:07:50.372+0300 [DEBUG] http: request complete: method=GET path=/v1/evaluation/1b4c84b4-8a03-baef-cf43-579d67556287 duration=240.724µs
Jun 03 21:07:50 docker1 nomad[142776]:     2020-06-03T21:07:50.373+0300 [DEBUG] http: request complete: method=GET path=/v1/evaluation/1b4c84b4-8a03-baef-cf43-579d67556287/allocations duration=199.703µs
Jun 03 21:07:55 docker1 nomad[142776]:     2020-06-03T21:07:55.922+0300 [DEBUG] http: request complete: method=GET path=/v1/jobs?prefix=jobname duration=287.501µs
Jun 03 21:07:55 docker1 nomad[142776]:     2020-06-03T21:07:55.923+0300 [DEBUG] http: request complete: method=GET path=/v1/job/jobname duration=305.141µs
Jun 03 21:07:55 docker1 nomad[142776]: panic: runtime error: invalid memory address or nil pointer dereference
Jun 03 21:07:55 docker1 nomad[142776]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x17f190b]
Jun 03 21:07:55 docker1 nomad[142776]: goroutine 83 [running]:
Jun 03 21:07:55 docker1 nomad[142776]: github.com/hashicorp/nomad/nomad/state.(*StateStore).deleteJobFromPlugin(0xc0003becc0, 0x28, 0xc0016f2ac0, 0xc0013b83c0, 0xc0017bd8a0, 0x0)
Jun 03 21:07:55 docker1 nomad[142776]:         github.com/hashicorp/nomad/nomad/state/state_store.go:1192 +0x37b
Jun 03 21:07:55 docker1 nomad[142776]: github.com/hashicorp/nomad/nomad/state.(*StateStore).DeleteJobTxn(0xc0003becc0, 0x28, 0xc0016e8df6, 0x7, 0xc0016e8dd5, 0x7, 0xc0016f2ac0, 0x38061e0, 0xc0017bd300)
Jun 03 21:07:55 docker1 nomad[142776]:         github.com/hashicorp/nomad/nomad/state/state_store.go:1502 +0xafb
Jun 03 21:07:55 docker1 nomad[142776]: github.com/hashicorp/nomad/nomad.(*nomadFSM).handleJobDeregister(0xc0005b69a0, 0x28, 0xc0016e8dd5, 0x7, 0xc0016e8df6, 0x7, 0x1, 0xc0016f2ac0, 0xc000839a38, 0x17dbfc1)
Jun 03 21:07:55 docker1 nomad[142776]:         github.com/hashicorp/nomad/nomad/fsm.go:618 +0x1f6
Jun 03 21:07:55 docker1 nomad[142776]: github.com/hashicorp/nomad/nomad.(*nomadFSM).applyDeregisterJob.func1(0xc0016f2ac0, 0x3142c01, 0xc0016f2ac0)
Jun 03 21:07:55 docker1 nomad[142776]:         github.com/hashicorp/nomad/nomad/fsm.go:565 +0x78
Jun 03 21:07:55 docker1 nomad[142776]: github.com/hashicorp/nomad/nomad/state.(*StateStore).WithWriteTransaction(0xc0003becc0, 0xc000839b10, 0x0, 0x0)
Jun 03 21:07:55 docker1 nomad[142776]:         github.com/hashicorp/nomad/nomad/state/state_store.go:4873 +0x7b
Jun 03 21:07:55 docker1 nomad[142776]: github.com/hashicorp/nomad/nomad.(*nomadFSM).applyDeregisterJob(0xc0005b69a0, 0xc0002f0751, 0x4c, 0xcb, 0x28, 0x0, 0x0)
Jun 03 21:07:55 docker1 nomad[142776]:         github.com/hashicorp/nomad/nomad/fsm.go:564 +0x1f2
Jun 03 21:07:55 docker1 nomad[142776]: github.com/hashicorp/nomad/nomad.(*nomadFSM).Apply(0xc0005b69a0, 0xc001667a00, 0x577acc0, 0xbfae179d6862199d)
Jun 03 21:07:55 docker1 nomad[142776]:         github.com/hashicorp/nomad/nomad/fsm.go:208 +0x42d
Jun 03 21:07:55 docker1 nomad[142776]: github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft.(*Raft).runFSM.func1(0xc0016f6500)
Jun 03 21:07:55 docker1 nomad[142776]:         github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft/fsm.go:90 +0x2c1
Jun 03 21:07:55 docker1 nomad[142776]: github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft.(*Raft).runFSM.func2(0xc0016e0a00, 0x1, 0x40)
Jun 03 21:07:55 docker1 nomad[142776]:         github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft/fsm.go:113 +0x75
Jun 03 21:07:55 docker1 nomad[142776]: github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft.(*Raft).runFSM(0xc00066ef00)
Jun 03 21:07:55 docker1 nomad[142776]:         github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft/fsm.go:219 +0x42f
Jun 03 21:07:55 docker1 nomad[142776]: github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc00066ef00, 0xc000406d10)
Jun 03 21:07:55 docker1 nomad[142776]:         github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft/state.go:146 +0x55
Jun 03 21:07:55 docker1 nomad[142776]: created by github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft.(*raftState).goFunc
Jun 03 21:07:55 docker1 nomad[142776]:         github.com/hashicorp/nomad/vendor/github.com/hashicorp/raft/state.go:144 +0x66
Jun 03 21:07:55 docker1 systemd[1]: nomad.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jun 03 21:07:55 docker1 systemd[1]: nomad.service: Unit entered failed state.
Jun 03 21:07:55 docker1 systemd[1]: nomad.service: Failed with result 'exit-code'.
```

**Comment by TheSpbra1n** [comment]
Sorry, not relevant for version 0.11.1 :-)
