### ISSUE TITLE
Client v0.3.0-rc2: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by matthewvalimaki** [hashicorp/nomad#846]
```
/ # nomad agent -config /etc/nomad/conf.d/
    Loaded configuration from /etc/nomad/conf.d/_base.hcl
==> Starting Nomad agent...
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x6023a4]

goroutine 1 [running]:
panic(0x1081920, 0xc820012090)
        /usr/lib/go/src/runtime/panic.go:464 +0x3e6
github.com/hashicorp/nomad/nomad/structs.(*Job).LookupTaskGroup(0x0, 0xc820282330, 0x5, 0x5)
        /go/src/github.com/hashicorp/nomad/nomad/structs/structs.go:1026 +0x114
github.com/hashicorp/nomad/client.NewTaskRunner(0xc82010fc20, 0xc82015c580, 0xc820282860, 0xc820292660, 0xc8202902d0, 0xc820074700, 0xc82010fd60, 0xd0)
        /go/src/github.com/hashicorp/nomad/client/task_runner.go:76 +0xc4
github.com/hashicorp/nomad/client.(*AllocRunner).RestoreState(0xc820160b60, 0x0, 0x0)
        /go/src/github.com/hashicorp/nomad/client/alloc_runner.go:126 +0x3f6
github.com/hashicorp/nomad/client.(*Client).restoreState(0xc820163d40, 0x0, 0x0)
        /go/src/github.com/hashicorp/nomad/client/client.go:448 +0x544
github.com/hashicorp/nomad/client.NewClient(0xc82015c4d0, 0xc82015c4d0, 0x0, 0x0)
        /go/src/github.com/hashicorp/nomad/client/client.go:171 +0xa13
github.com/hashicorp/nomad/command/agent.(*Agent).setupClient(0xc82010fa40, 0x0, 0x0)
        /go/src/github.com/hashicorp/nomad/command/agent/agent.go:260 +0x1df
github.com/hashicorp/nomad/command/agent.NewAgent(0xc8201d6640, 0x7f7f606c8490, 0xc8202050e0, 0xc82010f9a0, 0x0, 0x0)
        /go/src/github.com/hashicorp/nomad/command/agent/agent.go:54 +0x247
github.com/hashicorp/nomad/command/agent.(*Command).setupAgent(0xc8201d01e0, 0xc8201d6640, 0x7f7f606c8490, 0xc8202050e0, 0x0, 0x0)
        /go/src/github.com/hashicorp/nomad/command/agent/command.go:286 +0xc3
github.com/hashicorp/nomad/command/agent.(*Command).Run(0xc8201d01e0, 0xc82000a220, 0x2, 0x2, 0x0)
        /go/src/github.com/hashicorp/nomad/command/agent/command.go:389 +0x597
github.com/hashicorp/nomad/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc8201563c0, 0xc8201563c0, 0x0, 0x0)
        /go/src/github.com/hashicorp/nomad/vendor/github.com/mitchellh/cli/cli.go:153 +0x5ee
main.RunCustom(0xc82000a210, 0x3, 0x3, 0xc8201bb1d0, 0xc820058058)
        /go/src/github.com/hashicorp/nomad/main.go:48 +0x47b
main.Run(0xc82000a210, 0x3, 0x3, 0x7f7f6072b028)
        /go/src/github.com/hashicorp/nomad/main.go:15 +0x4c
main.main()
        /go/src/github.com/hashicorp/nomad/main.go:11 +0x60
```

Contents of _base.hcl
```
data_dir = "/data/nomad"

disable_update_check = true
datacenters = ["dc1"]
client {
    enabled = true
    options = {
        "driver.raw_exec.enable" = "1"
    }
}
```

**Comment by dadgar** [comment]
Can you give any reproduction steps?

**Comment by matthewvalimaki** [comment]
@dadgar all I do is execute the mentioned command, couple seconds go by and I get the panic. However I believe `LookupTaskGroup` to be the culprit as I did have two allocations in the data directory. Once I did `rm -rf /data/nomad/*` wiping `alloc` and `client` I no longer get the panic.

**Comment by dadgar** [comment]
What was the version of the client before you upgraded?

**Comment by matthewvalimaki** [comment]
Latest stable: 0.2.3.

**Comment by dadgar** [comment]
Was this from the first restart of the Nomad Client transitioning from 0.2.3 to 0.3.0 or it was on 0.3.0 and you restarted again

**Comment by matthewvalimaki** [comment]
I had 0.2.3 running, killed it (kill pid) and then fired up 0.3.0.

**Comment by dadgar** [comment]
Believe #848 may have fixed this too. Can't repro
