### ISSUE TITLE
Server v0.3.0-rc2: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by matthewvalimaki** [hashicorp/nomad#847]
```
    2016/02/24 16:06:16 [DEBUG] nomad.heartbeat: node '3cab6545-96ed-1bd0-b369-629ed0b30da8' TTL expired
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x50 pc=0x6e7566]

goroutine 3373 [running]:
panic(0x1081960, 0xc820014080)
        /usr/lib/go/src/runtime/panic.go:464 +0x3e6
github.com/hashicorp/nomad/nomad.(*Node).createNodeEvals(0xc820230140, 0xc8203a1a40, 0x24, 0x4f7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/hashicorp/nomad/nomad/node_endpoint.go:632 +0x1046
github.com/hashicorp/nomad/nomad.(*Node).UpdateStatus(0xc820230140, 0xc8203a1230, 0xc820136320, 0x0, 0x0)
        /go/src/github.com/hashicorp/nomad/nomad/node_endpoint.go:189 +0x93d
github.com/hashicorp/nomad/nomad.(*Server).invalidateHeartbeat(0xc820060a80, 0xc8203a1a40, 0x24)
        /go/src/github.com/hashicorp/nomad/nomad/heartbeat.go:101 +0x3d7
github.com/hashicorp/nomad/nomad.(*Server).resetHeartbeatTimerLocked.func1()
        /go/src/github.com/hashicorp/nomad/nomad/heartbeat.go:77 +0x3f
created by time.goFunc
        /usr/lib/go/src/time/sleep.go:129 +0x3a
```

**Comment by dadgar** [comment]
Can you give any reproduction steps?

**Comment by matthewvalimaki** [comment]
@dadgar unfortunately this has happened only once so far and despite my attempts to reproduce it I have not been able to. I am seeing other heartbeats come through, nodes coming and going without issues.

**Comment by matthewvalimaki** [comment]
Just saw it again with exact same panic. This happened right before:
```
    2016/02/24 16:51:08 [DEBUG] nomad.heartbeat: node '3cab6545-96ed-1bd0-b369-629ed0b30da8' TTL expired
    2016/02/24 16:51:08 [DEBUG] worker: dequeued evaluation efa37aaa-6dcc-7e0c-5066-cecfba387244
    2016/02/24 16:51:08 [DEBUG] sched.core: eval GC: scanning before index 0 (1h0m0s)
    2016/02/24 16:51:08 [DEBUG] worker: ack for evaluation efa37aaa-6dcc-7e0c-5066-cecfba387244
    2016/02/24 16:51:08 [DEBUG] worker: dequeued evaluation 13451bb9-302e-1ad2-3c1c-5e640942096c
    2016/02/24 16:51:08 [DEBUG] sched.core: node GC: scanning before index 0 (24h0m0s)
    2016/02/24 16:51:08 [DEBUG] worker: ack for evaluation 13451bb9-302e-1ad2-3c1c-5e640942096c
    2016/02/24 16:51:08 [DEBUG] worker: dequeued evaluation 190452b1-affe-ad64-8601-0ba3df5a1a01
    2016/02/24 16:51:08 [DEBUG] sched.core: job GC: scanning before index 0 (4h0m0s)
    2016/02/24 16:51:08 [DEBUG] worker: ack for evaluation 190452b1-affe-ad64-8601-0ba3df5a1a01
```
So what I did prior:
1) 1 server, 2 nodes
2) Registered a new job (execution failed)
3) Took the 2 nodes down
4) Left server running until the exception came

Perhaps some cleanup on the server is failing?

**Comment by dadgar** [comment]
Hmm thanks! It will be a good starting point! If you have any other details or different logs please post :+1:

**Comment by dadgar** [comment]
@matthewvalimaki Do you have the full logs of the server when you upgraded

**Comment by matthewvalimaki** [comment]
@dadgar Unfortunately I do not.
