### ISSUE TITLE
Fat jar won't start

### ISSUE THREAD

**Issue by kabennett** [hashicorp/nomad#854]
I am using Spring Boot with Consul to develop a new microservice architecture.  I have a fat jar that starts up just fine via the usual jar -jar jarfilename.jar process.  With Consul running it is good to go.

However, when I start nomad and try to run the following job, I get the following error:

```
2016/02/26 11:12:04 [ERR] client: failed to complete task 'proxyService' for alloc '8215246f-69c4-4535-05e6-9c0849e92f10': Wait returned exit code 1, signal 0, and error <nil>
```
Here's the job I currently have defined.
```
job "proxyServiceJob" {
	datacenters = ["dc1"]

	update {
		stagger = "10s"
		max_parallel = 1
	}

	group "proxyServiceGroup" {
	 task "proxyService" {
  			driver = "java"

			config {
    			artifact_source = "http://localhost:8080/NomadStaging/proxy-service-0.0.1-SNAPSHOT.jar"
			}
			
			resources {
                cpu = 500
                memory = 256
            }
  		}
	}
}
```
I downloaded Nomad today and installed it (nomad_0.3.0_windows_amd64.xip), so it's the latest version. I am running an older version of Consul (Consul v0.5.2, Consul Protocol: 2), so I'm not sure if that could be related to the problem I'm having starting this jar via Nomad.

**Comment by kabennett** [comment]
I made the following changes to my job, but it still doesn't work.  I updated Consul to the latest version (including the UI) and ensured that both Consul and Nomad have the same datacenter name configured (not sure if that is necessary).
```
job "proxyServiceJob" {
	datacenters = ["dc1"]
	update {
		stagger = "10s"
		max_parallel = 1
	}
	group "proxyServiceGroup" {
		restart {
			mode = "delay"
			interval = "5m"
			attempts = 10
			delay = "25s"
		}
		task "proxyService" {
  			driver = "java"
			config {
    			artifact_source = "http://localhost:8080/NomadStaging/proxy-service-0.0.1-SNAPSHOT.jar"
    			jvm_options = ["-Xmx512m","-Xms256m"]
			}
			resources {
                cpu = 1000
                memory = 1000
                    port "http" {
                    }
            }
  		}
	}
}
```

**Comment by diptanu** [comment]
@kabennett Can we get some logs for the task please? We would need more information to help you with this.

Once you run the job, please find the allocation id of the job, and use the ```nomad fs ls <alloc-id> alloc/logs/``` and list the logs and please get us the logs from the tasks. You could get the logs from the tasks via ```nomad fs cat <alloc-id> alloc/logs/proxyService.stdout.0``` and ```nomad fs cat <alloc-id> alloc/logs/proxyService.stderr.0```

**Comment by kabennett** [comment]
stderr
```
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
	at java.lang.Thread.run(Unknown Source)
Caused by: com.ecwid.consul.transport.TransportException: java.net.SocketException: Unrecognized Windows Sockets error: 10106: create
	at com.ecwid.consul.transport.DefaultHttpTransport.executeRequest(DefaultHttpTransport.java:87)
	at com.ecwid.consul.transport.DefaultHttpTransport.makeGetRequest(DefaultHttpTransport.java:46)
	at com.ecwid.consul.v1.ConsulRawClient.makeGetRequest(ConsulRawClient.java:66)
	at com.ecwid.consul.v1.kv.KeyValueConsulClient.getKVValues(KeyValueConsulClient.java:135)
	at com.ecwid.consul.v1.kv.KeyValueConsulClient.getKVValues(KeyValueConsulClient.java:128)
	at com.ecwid.consul.v1.ConsulClient.getKVValues(ConsulClient.java:346)
	at org.springframework.cloud.consul.config.ConsulPropertySource.init(ConsulPropertySource.java:63)
	at org.springframework.cloud.consul.config.ConsulPropertySourceLocator.locate(ConsulPropertySourceLocator.java:70)
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:88)
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:638)
	at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:338)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:305)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1124)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1113)
	at com.example.ProxyServiceBootstrap.main(ProxyServiceBootstrap.java:26)
	... 6 more
Caused by: java.net.SocketException: Unrecognized Windows Sockets error: 10106: create
	at java.net.Socket.createImpl(Unknown Source)
	at java.net.Socket.getImpl(Unknown Source)
	at java.net.Socket.setSoTimeout(Unknown Source)
	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:116)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:882)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:220)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:164)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:139)
	at com.ecwid.consul.transport.DefaultHttpTransport.executeRequest(DefaultHttpTransport.java:71)
	... 20 more
```
stdout
```
ProxyService is starting. Please wait...
2016-02-26 13:56:21.130  INFO 10088 --- [           main] c.example.ProxyServiceBootstrap  : Starting ProxyServiceBootstrap v0.0.1-SNAPSHOT with PID 10088 (C:\Users\Kabennet\AppData\Local\Temp\NomadClient128651238\2b59d95f-5216-d616-1549-23043f06951b\proxyService\proxy-service-0.0.1-SNAPSHOT.jar started by Kabennet in C:\Users\Kabennet\AppData\Local\Temp\NomadClient128651238\2b59d95f-5216-d616-1549-23043f06951b\proxyService)
2016-02-26 13:56:21.137  INFO 10088 --- [           main] c.example.ProxyServiceBootstrap  : No active profile set, falling back to default profiles: default
2016-02-26 13:56:21.201  INFO 10088 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@11831155: startup date [Fri Feb 26 13:56:21 CST 2016]; root of context hierarchy
2016-02-26 13:56:21.523  INFO 10088 --- [           main] f.a.AutowiredAnnotationBeanPostProcessor : JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2016-02-26 13:56:21.548  INFO 10088 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'configurationPropertiesRebinderAutoConfiguration' of type [class org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$f537c673] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2016-02-26 13:56:27.269  INFO 10088 --- [           main] c.example.ProxyServiceBootstrap  : Started ProxyServiceBootstrap in 7.595 seconds (JVM running for 8.525)
2016-02-26 13:56:28.385  INFO 10088 --- [           main] o.a.http.impl.client.DefaultHttpClient   : I/O exception (java.net.SocketException) caught when connecting to {}->http://localhost:8500: Unrecognized Windows Sockets error: 10106: create
2016-02-26 13:56:28.385  INFO 10088 --- [           main] o.a.http.impl.client.DefaultHttpClient   : Retrying connect to {}->http://localhost:8500
2016-02-26 13:56:28.386  INFO 10088 --- [           main] o.a.http.impl.client.DefaultHttpClient   : I/O exception (java.net.SocketException) caught when connecting to {}->http://localhost:8500: Unrecognized Windows Sockets error: 10106: create
2016-02-26 13:56:28.386  INFO 10088 --- [           main] o.a.http.impl.client.DefaultHttpClient   : Retrying connect to {}->http://localhost:8500
2016-02-26 13:56:28.386  INFO 10088 --- [           main] o.a.http.impl.client.DefaultHttpClient   : I/O exception (java.net.SocketException) caught when connecting to {}->http://localhost:8500: Unrecognized Windows Sockets error: 10106: create
2016-02-26 13:56:28.386  INFO 10088 --- [           main] o.a.http.impl.client.DefaultHttpClient   : Retrying connect to {}->http://localhost:8500
2016-02-26 13:56:28.391 ERROR 10088 --- [           main] o.s.boot.SpringApplication               : Application startup failed

com.ecwid.consul.transport.TransportException: java.net.SocketException: Unrecognized Windows Sockets error: 10106: create
	at com.ecwid.consul.transport.DefaultHttpTransport.executeRequest(DefaultHttpTransport.java:87) ~[consul-api-1.1.6.jar!/:na]
	at com.ecwid.consul.transport.DefaultHttpTransport.makeGetRequest(DefaultHttpTransport.java:46) ~[consul-api-1.1.6.jar!/:na]
	at com.ecwid.consul.v1.ConsulRawClient.makeGetRequest(ConsulRawClient.java:66) ~[consul-api-1.1.6.jar!/:na]
	at com.ecwid.consul.v1.kv.KeyValueConsulClient.getKVValues(KeyValueConsulClient.java:135) ~[consul-api-1.1.6.jar!/:na]
	at com.ecwid.consul.v1.kv.KeyValueConsulClient.getKVValues(KeyValueConsulClient.java:128) ~[consul-api-1.1.6.jar!/:na]
	at com.ecwid.consul.v1.ConsulClient.getKVValues(ConsulClient.java:346) ~[consul-api-1.1.6.jar!/:na]
	at org.springframework.cloud.consul.config.ConsulPropertySource.init(ConsulPropertySource.java:63) ~[spring-cloud-consul-config-1.0.0.M5.jar!/:1.0.0.M5]
	at org.springframework.cloud.consul.config.ConsulPropertySourceLocator.locate(ConsulPropertySourceLocator.java:70) ~[spring-cloud-consul-config-1.0.0.M5.jar!/:1.0.0.M5]
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:88) ~[spring-cloud-context-1.1.0.M4.jar!/:1.1.0.M4]
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:638) [spring-boot-1.3.1.RELEASE.jar!/:1.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:338) [spring-boot-1.3.1.RELEASE.jar!/:1.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:305) [spring-boot-1.3.1.RELEASE.jar!/:1.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1124) [spring-boot-1.3.1.RELEASE.jar!/:1.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1113) [spring-boot-1.3.1.RELEASE.jar!/:1.3.1.RELEASE]
	at com.example.ProxyServiceBootstrap.main(ProxyServiceBootstrap.java:26) [proxy-service-0.0.1-SNAPSHOT.jar!/:0.0.1-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_74]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_74]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_74]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_74]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53) [proxy-service-0.0.1-SNAPSHOT.jar!/:0.0.1-SNAPSHOT]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_74]
Caused by: java.net.SocketException: Unrecognized Windows Sockets error: 10106: create
	at java.net.Socket.createImpl(Unknown Source) ~[na:1.8.0_74]
	at java.net.Socket.getImpl(Unknown Source) ~[na:1.8.0_74]
	at java.net.Socket.setSoTimeout(Unknown Source) ~[na:1.8.0_74]
	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:116) ~[httpclient-4.5.1.jar!/:4.5.1]
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177) ~[httpclient-4.5.1.jar!/:4.5.1]
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304) ~[httpclient-4.5.1.jar!/:4.5.1]
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611) ~[httpclient-4.5.1.jar!/:4.5.1]
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446) ~[httpclient-4.5.1.jar!/:4.5.1]
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:882) ~[httpclient-4.5.1.jar!/:4.5.1]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71) ~[httpclient-4.5.1.jar!/:4.5.1]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:220) ~[httpclient-4.5.1.jar!/:4.5.1]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:164) ~[httpclient-4.5.1.jar!/:4.5.1]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:139) ~[httpclient-4.5.1.jar!/:4.5.1]
	at com.ecwid.consul.transport.DefaultHttpTransport.executeRequest(DefaultHttpTransport.java:71) ~[consul-api-1.1.6.jar!/:na]
	... 20 common frames omitted
```

**Comment by diptanu** [comment]
@kabennett Looks like Nomad is able to start the the Java process, but Java is having some issue with opening a port.

After looking up on the web, it looks like setting the ```SystemRoot``` env var before starting the Nomad client should solve it.

**Comment by kabennett** [comment]
@diptanu I saw that too, but I haven't gotten that to work yet (been trying). What do I need to add to my job to properly set this env var?

**Comment by diptanu** [comment]
@kabennett So I don't think this has to be a job env var. The script which starts nomad client, should set that env var first and then launch nomad client.

**Comment by diptanu** [comment]
@kabennett I think in Windows you could set system wide env var, and then restarting Windows should probably work too.

**Comment by kabennett** [comment]
@diptanu I am running nomad in dev mode (nomad agent -dev), so when you refer to launching the nomad client, I assume launching nomad in dev mode is fine.  I am setting 'SystemRoot' to 'C:\Windows' as I saw in a few posts after searching Google. Good idea about restarting Windows - hadn't done that yet.

**Comment by diptanu** [comment]
@kabennett Yeah running Nomad in dev mode is fine. Set that env var system wide and on the terminal before launching Nomad just to be safe.

**Comment by kabennett** [comment]
@diptanu Tried all of that, and it still is failing with the same error.

**Comment by diptanu** [comment]
@kabennett Can you please share the jar with us? It would be nice if the jar has no dependencies, like a normal spring boot hello world app may be? Unfortunately, we are very busy at the moment, so it would take us some time to get to it.

**Comment by kabennett** [comment]
[helloWorldService.txt](https://github.com/hashicorp/nomad/files/151453/helloWorldService.txt)

@diptanu Thanks for taking a look at this. Nothing I've tried so far has worked, and again, I am able to start up the attached jar via the command line just fine.  You can test via http://localhost:8081/greeting/{name} as the REST service is a simple GET.


[hello-world-service-0.0.1-SNAPSHOT.zip](https://github.com/hashicorp/nomad/files/151449/hello-world-service-0.0.1-SNAPSHOT.zip)

**Comment by kabennett** [comment]
@diptanu I got it working with the attached job description. I ended up having to put the SystemRoot environment variable in the job. In fact, I don't have this specified as a Windows environment variable on my machine. From a command line, 'echo %SystemRoot%' returns 'c:\WINDOWS', so I'm wondering if Nomad isn't picking up all of the environment variables on Windows.
[helloWorldService.txt](https://github.com/hashicorp/nomad/files/151863/helloWorldService.txt)

**Comment by dadgar** [comment]
@kabennett Nomad does a raw fork exec, while launching something from bash will set the environment variables of the new process to that of the bash session. Nomad does not do that so your application is only receiving the set of environment variables you are passing as well as Nomad specific environment variables (https://www.nomadproject.io/docs/jobspec/environment.html)

**Comment by dadgar** [comment]
Closing as it has been resolved.
