### ISSUE TITLE
panic during nomad operator debug

### ISSUE THREAD

**Issue by tgross** [hashicorp/nomad#8794]
Ran into the following panic in a Nomad agent running in dev-mode, while running `nomad operator debug -node-id :id`. Commit was the current `master` as of https://github.com/hashicorp/nomad/commit/cce82a2e17a48541aedb68a28b904b41bc93e313

```
    2020-08-31T15:34:33.602-0400 [ERROR] http: http: panic serving 127.0.0.1:60187: reflect.Set: value of type structs.HostDataRequest is not assignable to type structs.QueryOptions
goroutine 6477 [running]:
net/http.(*conn).serve.func1(0xc00042d5e0)
        net/http/server.go:1800 +0x139
panic(0x60cbf60, 0xc00145b880)
        runtime/panic.go:975 +0x3e3
reflect.Value.assignTo(0x66face0, 0xc000f24400, 0x199, 0x69593bd, 0xb, 0x682dfa0, 0x0, 0x9e167d0, 0x0, 0x10)
        reflect/value.go:2411 +0x426
reflect.Value.Set(0x682dfa0, 0xc0009b1d40, 0x199, 0x66face0, 0xc000f24400, 0x199)
        reflect/value.go:1539 +0xbd
github.com/hashicorp/nomad/helper/codec.(*InmemCodec).ReadRequestBody(0xc00037fd00, 0x6531a20, 0xc0009b1d40, 0xc0009b1d01, 0x6531a20)
        github.com/hashicorp/nomad/helper/codec/inmem.go:25 +0x175
net/rpc.(*Server).readRequest(0xc000819310, 0x6f71580, 0xc00037fd00, 0xc00037fd00, 0x20, 0x18, 0xc00007ec00, 0x9e167d0, 0x0, 0x18, ...)
        net/rpc/server.go:562 +0x297
net/rpc.(*Server).ServeRequest(0xc000819310, 0x6f71580, 0xc00037fd00, 0x6494c80, 0x86cd701)
        net/rpc/server.go:486 +0x77
github.com/hashicorp/nomad/client.(*Client).ClientRPC(0xc0003d6000, 0x695574b, 0xa, 0x5f908a0, 0xc000114510, 0x5fc0820, 0xc000245640, 0x3b, 0x40)
        github.com/hashicorp/nomad/client/rpc.go:37 +0xb9
github.com/hashicorp/nomad/command/agent.(*HTTPServer).AgentHostRequest(0xc0004dc2d0, 0x6f5a400, 0xc0009b1ce0, 0xc000f28100, 0x40d1176, 0x5f4d50c9, 0x23db8cd8, 0x23728aa496849)
        github.com/hashicorp/nomad/command/agent/agent_endpoint.go:730 +0x5ea
github.com/hashicorp/nomad/command/agent.(*HTTPServer).wrap.func1(0x6f5a400, 0xc0009b1ce0, 0xc000f28100)
        github.com/hashicorp/nomad/command/agent/http.go:448 +0x176
net/http.HandlerFunc.ServeHTTP(0xc0005b6900, 0x6f5a400, 0xc0009b1ce0, 0xc000f28100)
        net/http/server.go:2041 +0x44
net/http.(*ServeMux).ServeHTTP(0xc00024f2c0, 0x6f5a400, 0xc0009b1ce0, 0xc000f28100)
        net/http/server.go:2416 +0x1a5
github.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1(0x6f61f40, 0xc00013c1c0, 0xc000f28100)
        github.com/NYTimes/gziphandler@v1.0.1/gzip.go:277 +0x1e6
net/http.HandlerFunc.ServeHTTP(0xc00046aa20, 0x6f61f40, 0xc00013c1c0, 0xc000f28100)
        net/http/server.go:2041 +0x44
net/http.serverHandler.ServeHTTP(0xc00036c460, 0x6f61f40, 0xc00013c1c0, 0xc000f28100)
        net/http/server.go:2836 +0xa3
net/http.(*conn).serve(0xc00042d5e0, 0x6f70780, 0xc00037fb40)
        net/http/server.go:1924 +0x86c
created by net/http.(*Server).Serve
        net/http/server.go:2962 +0x35c

```

**Comment by tgross** [comment]
Looks like the param for the client-side of the RPC is wrong. PR incoming.

**Comment by tgross** [comment]
Fixed by https://github.com/hashicorp/nomad/pull/8795
