### ISSUE TITLE
UI acceptance test flake

### ISSUE THREAD

**Issue by tgross** [hashicorp/nomad#9154]
I've seen a handle of cases of this in the last few days:
https://app.circleci.com/pipelines/github/hashicorp/nomad/12579/workflows/f7997391-9591-4028-8476-962425c00a92/jobs/111252

```
Acceptance | job deployments: when open, a deployment shows a list of all task groups and their respective stats - Chrome 86.0
Name
Expected:
    port-g-0

Result:
    card-g-1

Source:
    at _callee7$ (http://localhost:7357/ui/assets/tests.js:6555:24)
    at tryCatch (http://localhost:7357/ui/assets/vendor.js:411:40)
    at Generator.invoke [as _invoke] (http://localhost:7357/ui/assets/vendor.js:685:22)
    at Generator.prototype.<computed> [as next] (http://localhost:7357/ui/assets/vendor.js:444:21)
    at asyncGeneratorStep (http://localhost:7357/ui/assets/tests.js:6277:105)
    at _next (http://localhost:7357/ui/assets/tests.js:6279:196)
```

**Comment by DingoEatingFuzz** [comment]
I believe these have been addressed by #9234 and #9244
