### ISSUE TITLE
Nomad panics if peers.json file exits, nukes database

### ISSUE THREAD

**Issue by thetooth** [hashicorp/nomad#9774]
### Nomad version
Nomad v1.0.1 (c9c68aa55a7275f22d2338f2df53e67ebfcb9238)

### Operating system and Environment details
Ubuntu 18 LTS as VM

### Issue
If the raft protocol fails due to any reason (in our case all nodes were rebooted for maintenance), then the cluster cannot be recovered if a peers.json file is used. The only way to get the cluster back up is to wipe the configuration and start from scratch.

I have tested this on 1.0.1, 1.0, 0.12.9 and 0.11.2. The issue is not present in 0.11.2 or earlier versions but is on the 0.12 line and later.

Can be reproduced by setting up a 3 server cluster, stopping a single node cause a consensus issue. Then placing a peers.json file formatted for raft version 1/2 pointing to all 3 nodes.

```
==> Starting Nomad agent...
 agent.plugin_loader: skipping external plugins since plugin_dir doesn't exist: plugin_dir=/var/nomad/plug
 agent: detected plugin: name=exec type=driver plugin_version=0.1.0
 agent: detected plugin: name=qemu type=driver plugin_version=0.1.0
 agent: detected plugin: name=java type=driver plugin_version=0.1.0
 agent: detected plugin: name=docker type=driver plugin_version=0.1.0
 agent: detected plugin: name=raw_exec type=driver plugin_version=0.1.0
 agent: detected plugin: name=nvidia-gpu type=device plugin_version=0.1.0
 nomad: found peers.json file, recovering Raft configuration...
panic: failed to apply request: []byte{0x48, 0x81, 0xaa, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0
goroutine 1 [running]:
github.com/hashicorp/nomad/nomad.(*nomadFSM).Apply(0xc00037e070, 0xc000c82d20, 0xc000c82d20, 0x0)
        github.com/hashicorp/nomad/nomad/fsm.go:315 +0x1b17
github.com/hashicorp/raft.RecoverCluster(0xc000037680, 0x39f2c00, 0xc00037e070, 0x3a26aa0, 0xc0006e0240, 0
        github.com/hashicorp/raft@v1.1.3-0.20200211192230-365023de17e6/api.go:351 +0x4e5
github.com/hashicorp/nomad/nomad.(*Server).setupRaft(0xc0003df200, 0x0, 0x0)
        github.com/hashicorp/nomad/nomad/server.go:1330 +0x11ce
github.com/hashicorp/nomad/nomad.NewServer(0xc0003def00, 0x39e1740, 0xc0001aee78, 0x39b09e0, 0xc0001aee80,
        github.com/hashicorp/nomad/nomad/server.go:387 +0xbe5
github.com/hashicorp/nomad/command/agent.(*Agent).setupServer(0xc000360780, 0x0, 0x0)
        github.com/hashicorp/nomad/command/agent/agent.go:687 +0x2ad
github.com/hashicorp/nomad/command/agent.NewAgent(0xc000504c00, 0x3a4f040, 0xc00063c000, 0x39b6140, 0xc000
        github.com/hashicorp/nomad/command/agent/agent.go:135 +0x217
github.com/hashicorp/nomad/command/agent.(*Command).setupAgent(0xc000377c70, 0xc000504c00, 0x3a4f040, 0xc0
        github.com/hashicorp/nomad/command/agent/command.go:474 +0xb0
github.com/hashicorp/nomad/command/agent.(*Command).Run(0xc000377c70, 0xc000194170, 0x1, 0x1, 0x0)
        github.com/hashicorp/nomad/command/agent/command.go:657 +0x4c5
github.com/mitchellh/cli.(*CLI).Run(0xc0000d9e00, 0xc0000d9e00, 0xc00011d140, 0x37)
        github.com/mitchellh/cli@v1.1.0/cli.go:260 +0x1cf
main.RunCustom(0xc000194160, 0x2, 0x2, 0xc000182058)
        github.com/hashicorp/nomad/main.go:142 +0x4a5
main.Run(...)
        github.com/hashicorp/nomad/main.go:87
main.main()
        github.com/hashicorp/nomad/main.go:83 +0x65
nomad.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
nomad.service: Failed with result 'exit-code'.
```

After removing the peers.json file, instead of getting consensus errors the same panic occurs and all nodes in the cluster enter a restart loop.

```
nomad.raft: restored from snapshot: id=1792-403064-1610195892407
 nomad.raft: initial configuration: index=406063 servers="[{Suffrage:Voter ID:192.168.0.242:4647 Address:192.168.0.242:4647} {Suffrage:Voter ID:192.168.0.154:4647 Address:192.168.0.154:4647} {Suffrage:Voter ID:192.168.0.244:4647 Address:192.168.0.244:4647} {Suffrage:Voter ID:192.168.0.245:4647 Address:192.168.0.245:4647} {Suffrage:Voter ID:192.168.0.246:4647 Address:192.168.0.246:4647}]"
 nomad: serf: Ignoring previous leave in snapshot
 nomad: serf: Ignoring previous leave in snapshot
 nomad: serf: Ignoring previous leave in snapshot
 nomad: serf: Ignoring previous leave in snapshot
 nomad: serf: Ignoring previous leave in snapshot
 nomad: serf: Ignoring previous leave in snapshot
 nomad: serf: Ignoring previous leave in snapshot
 nomad: serf: Ignoring previous leave in snapshot
 nomad: serf: Ignoring previous leave in snapshot
 nomad: serf: EventMemberJoin: mars.global 192.168.0.244
 nomad: starting scheduling worker(s): num_workers=4 schedulers=[_core, service, batch, system]
 client: using state directory: state_dir=/var/nomad/client
 client: using alloc directory: alloc_dir=/var/nomad/alloc
 nomad.raft: entering follower state: follower="Node at 192.168.0.244:4647 [Follower]" leader=
 nomad: serf: Attempting re-join to previously known node: earth.global: 192.168.0.245:4648
 nomad: serf: Attempting re-join to previously known node: ps-mtc-hsvr-2.global: 192.168.0.242:4648
 nomad: adding server: server="mars.global (Addr: 192.168.0.244:4647) (DC: mtc1)"
 nomad: serf: Attempting re-join to previously known node: venus.global: 192.168.0.246:4648
 client.fingerprint_mgr.cgroup: cgroups are available
 nomad: serf: Attempting re-join to previously known node: magic.global: 192.168.0.154:4648
 nomad: serf: Failed to re-join any previously known node
 client.fingerprint_mgr.network: unable to parse speed: path=/sbin/ethtool device=net0
 client.fingerprint_mgr.network: unable to parse speed: path=/sbin/ethtool device=lo
 client.fingerprint_mgr.network: unable to parse speed: path=/sbin/ethtool device=net0
 client.fingerprint_mgr.network: unable to parse speed: path=/sbin/ethtool device=docker0
 client.fingerprint_mgr.vault: Vault is available
 nomad.raft: heartbeat timeout reached, starting election: last-leader=
 nomad.raft: entering candidate state: node="Node at 192.168.0.244:4647 [Candidate]" term=2038
nomad.raft: failed to make requestVote RPC: target="{Voter 192.168.0.242:4647 192.168.0.242:4647}" error="dial tcp 192.168.0.242:4647: connect: connection refused"
nomad.raft: failed to make requestVote RPC: target="{Voter 192.168.0.154:4647 192.168.0.154:4647}" error="dial tcp 192.168.0.154:4647: connect: connection refused"
nomad.raft: failed to make requestVote RPC: target="{Voter 192.168.0.245:4647 192.168.0.245:4647}" error="dial tcp 192.168.0.245:4647: connect: connection refused"
nomad.raft: failed to make requestVote RPC: target="{Voter 192.168.0.246:4647 192.168.0.246:4647}" error="dial tcp 192.168.0.246:4647: connect: connection refused"
 nomad.raft: Election timeout reached, restarting election
 nomad.raft: entering candidate state: node="Node at 192.168.0.244:4647 [Candidate]" term=2039
nomad.raft: failed to make requestVote RPC: target="{Voter 192.168.0.242:4647 192.168.0.242:4647}" error="dial tcp 192.168.0.242:4647: connect: connection refused"
nomad.raft: failed to make requestVote RPC: target="{Voter 192.168.0.154:4647 192.168.0.154:4647}" error="dial tcp 192.168.0.154:4647: connect: connection refused"
nomad.raft: failed to make requestVote RPC: target="{Voter 192.168.0.245:4647 192.168.0.245:4647}" error="dial tcp 192.168.0.245:4647: connect: connection refused"
nomad.raft: failed to make requestVote RPC: target="{Voter 192.168.0.246:4647 192.168.0.246:4647}" error="dial tcp 192.168.0.246:4647: connect: connection refused"
 nomad: serf: EventMemberJoin: magic.global 192.168.0.154
 nomad: adding server: server="magic.global (Addr: 192.168.0.154:4647) (DC: mtc1)"
 nomad.raft: Election timeout reached, restarting election
 nomad.raft: entering candidate state: node="Node at 192.168.0.244:4647 [Candidate]" term=2040
nomad.raft: failed to make requestVote RPC: target="{Voter 192.168.0.242:4647 192.168.0.242:4647}" error="dial tcp 192.168.0.242:4647: connect: connection refused"
nomad.raft: failed to make requestVote RPC: target="{Voter 192.168.0.245:4647 192.168.0.245:4647}" error="dial tcp 192.168.0.245:4647: connect: connection refused"
nomad.raft: failed to make requestVote RPC: target="{Voter 192.168.0.246:4647 192.168.0.246:4647}" error="dial tcp 192.168.0.246:4647: connect: connection refused"
 nomad: serf: EventMemberJoin: earth.global 192.168.0.245
 nomad: adding server: server="earth.global (Addr: 192.168.0.245:4647) (DC: mtc1)"
 nomad: serf: EventMemberJoin: venus.global 192.168.0.246
 nomad: adding server: server="venus.global (Addr: 192.168.0.246:4647) (DC: mtc1)"
 nomad: serf: EventMemberJoin: ps-mtc-hsvr-2.global 192.168.0.242
 nomad: adding server: server="ps-mtc-hsvr-2.global (Addr: 192.168.0.242:4647) (DC: mtc1)"
 nomad.raft: Election timeout reached, restarting election
 nomad.raft: entering candidate state: node="Node at 192.168.0.244:4647 [Candidate]" term=2041
 nomad.raft: election won: tally=3
 nomad.raft: entering leader state: leader="Node at 192.168.0.244:4647 [Leader]"
 nomad.raft: added peer, starting replication: peer=192.168.0.242:4647
 nomad.raft: added peer, starting replication: peer=192.168.0.154:4647
 nomad.raft: added peer, starting replication: peer=192.168.0.245:4647
 nomad.raft: added peer, starting replication: peer=192.168.0.246:4647
 nomad: cluster leadership acquired
 nomad.raft: pipelining replication: peer="{Voter 192.168.0.154:4647 192.168.0.154:4647}"
 nomad.raft: pipelining replication: peer="{Voter 192.168.0.242:4647 192.168.0.242:4647}"
 nomad.raft: pipelining replication: peer="{Voter 192.168.0.246:4647 192.168.0.246:4647}"
 nomad.raft: pipelining replication: peer="{Voter 192.168.0.245:4647 192.168.0.245:4647}"
panic: failed to apply request: []byte{0x48, 0x81, 0xaa, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0xd3, 0x16, 0x59, 0x13, 0x6f, 0x2e, 0xe8, 0x55, 0x9a}
goroutine 26 [running]:
github.com/hashicorp/nomad/nomad.(*nomadFSM).Apply(0xc00031cc40, 0xc0010039f0, 0x5273e40, 0xbff7599e8a998bcf)
	github.com/hashicorp/nomad/nomad/fsm.go:315 +0x1b17
github.com/hashicorp/raft.(*Raft).runFSM.func1(0xc000ef2500)
	github.com/hashicorp/raft@v1.1.3-0.20200211192230-365023de17e6/fsm.go:90 +0x2c2
github.com/hashicorp/raft.(*Raft).runFSM.func2(0xc000416000, 0x40, 0x40)
	github.com/hashicorp/raft@v1.1.3-0.20200211192230-365023de17e6/fsm.go:113 +0x75
github.com/hashicorp/raft.(*Raft).runFSM(0xc00030f500)
	github.com/hashicorp/raft@v1.1.3-0.20200211192230-365023de17e6/fsm.go:219 +0x3c4
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc00030f500, 0xc0001f6030)
	github.com/hashicorp/raft@v1.1.3-0.20200211192230-365023de17e6/state.go:146 +0x55
created by github.com/hashicorp/raft.(*raftState).goFunc
	github.com/hashicorp/raft@v1.1.3-0.20200211192230-365023de17e6/state.go:144 +0x66
nomad.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
nomad.service: Failed with result 'exit-code'.
```

**Comment by tgross** [comment]
Hi @thetooth! Generally speaking you shouldn't need to do a manual recovery with peers.json from a rolling server restart. Just for clarification, were all three nodes stopped and had an identical peers.json file at the time you started the first server node back up?

**Comment by thetooth** [comment]
That's correct, I'm not sure why it didn't work as you're right in that we have done plenty of rolling restarts without the use of a peers file, however this involved 3 of the 5 of the nodes going offline at the same time.

I had to wipe the config to get us up and running again but I did try a few different scenarios, basically with or without the peers file each node started in isolation would result in the same panic, meaning they had all picked up the same bad message.

I'm not sure if this means anything but we were also upgrading from 0.11.2 -> 1.0.1 at the same time, the first attempt was indeed a rolling restart but the cluster started having consensus errors, well to be precise it was saying all had to been upgraded in order to retrieve "temporary license metadata". So the entire hypervisor was taken down for a image upgrade too.

**Comment by tgross** [comment]
Oof, that's rough. Sorry to hear that. Let me mark this for investigation and we'll see if we can come up with a reproduction for it.

**Comment by tgross** [comment]
Just wanted to give a status update here... I've tried to replicate what you're seeing and haven't succeeded so far with a 3-node cluster. I've even tried starting with a 0.11.2 cluster and upgrading to 1.0.1 

So then I tried looking at the panic in more detail. The panic you're hitting is coming from the [fsm.Apply](https://github.com/hashicorp/nomad/blob/v1.0.1/nomad/fsm.go#L193-L316) method. It's checking the first byte of the raft entry, and if it doesn't recognize the entry then it's going to reject it and intentionally panic. Here's the error message:

```
panic: failed to apply request: []byte{0x48, 0x81, 0xaa, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0
```

But if we look at the [valid messages](https://github.com/hashicorp/nomad/blob/v1.0.1/nomad/structs/structs.go#L58-L107), you'll note that byte `0x48` should be message type ID 72... which is well into the range used by Nomad Enterprise. That's the `TmpLicenseUpsertRequestType` message, which suggests to me that one of the nodes that you've added is a Nomad OSS server.

I was able to replicate this by running a 3 node cluster of Nomad Enterprise, and then trying to downgrade one of the server nodes to Nomad OSS. I get the same panic:

```
panic: failed to apply request: []byte{0x48, 0x81, 0xaa, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0xd3, 0x16, 0x60, 0x4a, 0xd1, 0xf6, 0xfe, 0x8b, 0x21}

goroutine 15 [running]:
github.com/hashicorp/nomad/nomad.(*nomadFSM).Apply(0xc0002e4bd0, 0xc000508640, 0x5273e40, 0xbffed2e0ecc4ee73)
        github.com/hashicorp/nomad/nomad/fsm.go:315 +0x1b17
github.com/hashicorp/raft.(*Raft).runFSM.func1(0xc000314690)
        github.com/hashicorp/raft@v1.1.3-0.20200211192230-365023de17e6/fsm.go:90 +0x2c2
github.com/hashicorp/raft.(*Raft).runFSM.func2(0xc000190200, 0x6, 0x40)
        github.com/hashicorp/raft@v1.1.3-0.20200211192230-365023de17e6/fsm.go:113 +0x75
github.com/hashicorp/raft.(*Raft).runFSM(0xc000759800)
        github.com/hashicorp/raft@v1.1.3-0.20200211192230-365023de17e6/fsm.go:219 +0x3c4
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc000759800, 0xc0002c4190)
        github.com/hashicorp/raft@v1.1.3-0.20200211192230-365023de17e6/state.go:146 +0x55
created by github.com/hashicorp/raft.(*raftState).goFunc
        github.com/hashicorp/raft@v1.1.3-0.20200211192230-365023de17e6/state.go:144 +0x66
```

Can you confirm that you haven't tried to roll back from ENT to OSS here?

**Comment by tgross** [comment]
At this point we're pretty confident of the cause of this one and haven't heard back. I'm going to close the issue but if you have additional information that suggests this isn't the case, please feel free to reopen. Thanks!
